### ISSUE TITLE
[Feature] Add github action to connect with docker hub, add docker compose

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1008]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

1.add Dockerfile documents
2.add CI documents
3.add docker compose documents

### Usage Scenario

1.Have official images on docker hub for users to experiment
2.Easy to deploy the streamx environment locally through docker compose

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
supported
