### ISSUE TITLE
 [Feature] Add forced deletion of the job

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/streampark#1009]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When an exception occurs during job deployment, add forced deletion of the job [Flink on Kubernetes]

当作业部署（Flink on K8s Application mode）过程中出现异常，增加强制删除Job deployment。

### Usage Scenario

When the job deployment fails, the state will always process initializing, and you can increase the job
The deployment status is used to determine whether the job is deployed successfully. If it fails, a "Stop" button is provided.

当作业部署失败后，状态会一直处理 initializing，可以增加job
deployment 状态来判断作业是否部署成功，若失败的情况，提供“停止”按钮

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
supported
