### ISSUE TITLE
[Bug] Wrong FS: hdfs://tennameservice:8020/data/flink/..., expec ted: hdfs://tennameservice

### ISSUE THREAD

**Issue by syb853553110** [apache/streampark#1017]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在StreamX页面删除savepoint目录的时候，报错：
com.streamxhub.streamx.console.base.exception.ServiceException: Wrong FS: hdfs://tennameservice:8020/data/flink/stream/callv6-data-anasysis/savepoint/savepoint-c02fb5-8d1d0b7d839d, expec
ted: hdfs://tennameservice
hadoop的配置文件中配置的是 hdfs://tennameservice, stream中配置的也是hdfs://tennameservice
任务详情中的savepoint目录是 hdfs://tennameservice:8020/开头的，这时候删除savepoint目录会报错
而通过hdfs dfs命令, 使用hdfs://tennameservice和hdfs://tennameservice:8020都是正常的

### StreamX Version

1.2.3

### Java Version

1.8

### Flink Version

1.14.4

### Scala Version of Flink

2.12

### Error Exception

```log
com.streamxhub.streamx.console.base.exception.ServiceException: Wrong FS: hdfs://tennameservice:8020/data/flink/stream/callv6-data-anasysis/savepoint/savepoint-c02fb5-8d1d0b7d839d, expec
ted: hdfs://tennameservice
```

### Screenshots

![Uploading image.png…]()

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangbool** [comment]
same problem here
