### ISSUE TITLE
[Feature] Automate Ops based on `Flink Kubernetes Operator`

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1018]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Through the front-end a submit, you can operate the flink cluster to complete the corresponding work, for example: change the concurrency from 2 to 4, after the front-end submit, the back-end k8s cluster will automatically complete, store the state-->cancel flink job -> modify the configuration -> restart the task based on the state.

### Usage Scenario

Fully automated operations and maintenance

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qingfei1994** [comment]
Hi,  may I know if this feature is working in progress?

**Comment by wolfboys** [comment]
It's been too long since we made any progress. Feel free to propose a motion again.
