### ISSUE TITLE
[Feature] How to use RestApi ? Has document abut RestApi ?

### ISSUE THREAD

**Issue by waywtdcc** [apache/streampark#1027]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Feature] How to use RestApi ? Has document abut RestApi ?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xuchang-66** [comment]
you can use the  swagger document if you've already deployed sreamx-1.2.3，e.g http://yourip:10000/swagger-ui.html.
