### ISSUE TITLE
[Feature] sql submit task dependency jar package reuse

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1032]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the process of practice, I found that I need to constantly check the maven dependencies to copy and paste, which is too much trouble
<img width="858" alt="图片" src="https://user-images.githubusercontent.com/60029759/168103650-3ad37378-71a4-4ffb-ae3b-29f8f2a60b9e.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
solved in new version
