### ISSUE TITLE
branch [master] does not exist or authentication error,please check

### ISSUE THREAD

**Issue by rafaelxie** [apache/streampark#1038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When a user first login streamx web console, enter project update page, then submit , showing alert info :
branch [master] does not exist
or authentication error,please check
I've checked the source code, the problem should occur in this file "/views/flink/project/Edit.vue", because this vue page first load, the variable brancheList is empty list, although function handleSubmit calls function handleBranches, but function handleBranches runs with async mode, so brancheList is still empty, lead to what i mentioned error.

### StreamX Version

1.2.3-release branch build

### Java Version

1.8

### Flink Version

1.12.2

### Scala Version of Flink

2.11.12

### Error Exception

```log
branch [master] does not exist
or authentication error,please check
```

### Screenshots

![image](https://user-images.githubusercontent.com/46079067/168566713-9c06e5db-6cfc-4327-af11-f5ea33b0d731.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
we are looking forward to you fix this bug

**Comment by wolfboys** [comment]
fixed
