### ISSUE TITLE
[Bug] NullPointerException  on java.util.concurrent.FutureTask.report(FutureTask.java:122)

### ISSUE THREAD

**Issue by hehetown** [apache/streampark#1042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

NullPointerException 
java.util.concurrent.FutureTask.report(FutureTask.java:122)

### StreamX Version

streamx-console-service-1.2.3

### Java Version

openjdk1.8

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
Development Mode：Flink SQL
Execution Mode：kubernetes application
Flink Version：flink-1.13.6
Kubernetes Namespace: default
java.lang.NullPointerException 
java.util.concurrent.FutureTask.report(FutureTask.java:122)
java.util.concurrent.FutureTask.get(FutureTask.java:206)
com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$$anonfun$3.apply(BuildPipeline.scala:167)
com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$$anonfun$3.apply(BuildPipeline.scala:162)
scala.util.Try$.apply(Try.scala:192)
com.streamxhub.streamx.flink.packer.pipeline.BuildPipeline$class.launch(BuildPipeline.scala:162)
com.streamxhub.streamx.flink.packer.pipeline.impl.FlinkK8sApplicationBuildPipeline.launch(FlinkK8sApplicationBuildPipeline.scala:46)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
the key information of the error was not provided

**Comment by wolfboys** [comment]
the key information of the error was not provided

**Comment by wolfboys** [comment]
Answered
