### ISSUE TITLE
[Feature] knox proxy cluster

### ISSUE THREAD

**Issue by atovk** [apache/streampark#1044]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

in cdp has knox proxy support. for security some cluster open it. then :

example :
### yarn 
url diff by yarn config file yarn-site.xml

origin : http://cdpsit01.example.cn:8088

this proxy-prefix changed by 
knox proxy prefix : https://cdpsit02.example.cn:8443/gateway/cdp-proxy/yarn

### Usage Scenario

spark also has knox proxy

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
done
