### ISSUE TITLE
Streamx submits FlinkSQL as an application. Does not support both Application. yml and sql.yml during the Application phase?  

### ISSUE THREAD

**Issue by guohuawei** [apache/streampark#1045]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

streamx 以应用的形式提交flinksql，在application 阶段 streamx不支持同时选中application.yml和sql.yml 吗？

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.3.6

### Scala Version of Flink

2.11

### Error Exception

```log
streamx 以应用的形式提交flinksql，在application 阶段 streamx不支持同时选中application.yml和sql.yml 吗？
```

### Screenshots

![image](https://user-images.githubusercontent.com/15900069/169676100-1c73f022-7ccc-4da2-bfb7-cbe4d2e6bec9.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please use the latest version
