### ISSUE TITLE
[Bug] project Item list cannot be flipped

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#1048]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Open the home page, click the project menu to view the list, and click the next page, which does not take effect

### StreamX Version

streamx-1.2.3

### Java Version

1.8.0_162

### Flink Version

1.14.3

### Scala Version of Flink

2.11

### Error Exception

```log
Unable to translate, no other exceptions are prompted
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by muchunjin** [comment]
@wolfboys If you haven't done this bug, assign it to me. My brother group has a front-end team. I guarantee to submit PR next Monday. Now we have no PR, find a simple bug and contribute on

**Comment by wolfboys** [comment]
> @wolfboys If you haven't done this bug, assign it to me. My brother group has a front-end team. I guarantee to submit PR next Monday. Now we have no PR, find a simple bug and contribute on

ok
