### ISSUE TITLE
Flink on K8s

### ISSUE THREAD

**Issue by 391518331** [apache/streampark#1057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Streamx 1.2.3 how to configure Flink home, Flink version, and Flink cluster in the Flink on k8s mode、Thanks

### StreamX Version

1.2.3

### Flink Version

flink:1.13.2

### Scala Version of Flink

2.11

### Error Exception

```log
Streamx 1.2.3 how to configure Flink home, Flink version, and Flink cluster in the Flink on k8s mode、Thanks
```

### Screenshots

Streamx 1.2.3 how to configure Flink home, Flink version, and Flink cluster in the Flink on k8s mode、Thanks

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
supported
