### ISSUE TITLE
Available Task Slots Display as 0

### ISSUE THREAD

**Issue by 391518331** [apache/streampark#1083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Available Task Slots Display as 0

### StreamX Version

Laterst

### Flink Version

1.13.2

### Scala Version of Flink

2.11

### Error Exception

```log
Available Task Slots
0
Task Slots 0 Task Managers 0
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhbdesign** [comment]
同样的问题，解决了吗

**Comment by zhbdesign** [comment]
同样的问题，解决了吗

**Comment by niumy0701** [comment]
I also encountered the same issue in version 2.1.6. Can reopen this issue? @wolfboys 
It should be dynamically obtained based on the Flink API for the overview, why do we need to cache it for judgment?

<img width="1063" height="851" alt="Image" src="https://github.com/user-attachments/assets/6037b70a-ee08-484b-8d20-62f9f369200c" />
