### ISSUE TITLE
[Bug] After yarn restarts, run application in yarn not through streamx, streamx mapping wrong yarn application

### ISSUE THREAD

**Issue by ChenlingXie** [apache/streampark#1095]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After yarn restarts, run application in yarn not through streamx, streamx mapping wrong yarn application

### StreamX Version

1.2.3

### Flink Version

1.13.1

### Scala Version of Flink

2.11

### Error Exception

```log
No
```

### Screenshots

<img width="880" alt="28aad26011545644ea407135180a14f" src="https://user-images.githubusercontent.com/11712168/173271375-90d08fe4-b00c-4e0a-9edd-d94ff08bbde1.png">
<img width="413" alt="eac3c315418cfc01647edf573215951" src="https://user-images.githubusercontent.com/11712168/173271381-3ea41ae5-f452-4f88-bc72-291d5f7ec13d.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chuangehh** [comment]
Streamx maps through applicationid and jobid
You can use the streamx mapping function

streamx 通过applicationId 和 jobid 映射
你可以使用streamx 映射功能来解决
