### ISSUE TITLE
[Bug] Modify Parallelism and Task Slots, restart the application, the values of Total TaskManager and Total Slots unchanged

### ISSUE THREAD

**Issue by ChenlingXie** [apache/streampark#1096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Modify Parallelism and Task Slots, restart the application, the values of Total TaskManager and Total Slots unchanged

### StreamX Version

1.2.3

### Flink Version

1.13.1

### Scala Version of Flink

2.11

### Error Exception

```log
No
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chuangehh** [comment]
Modify the screenshot of the page
修改页面截个图

**Comment by medivh666** [comment]
相同的问题，taskmanger里面啥也没有
