### ISSUE TITLE
[Bug] Yarn application status failed, streamx shows running

### ISSUE THREAD

**Issue by ChenlingXie** [apache/streampark#1097]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Yarn application status failed, streamx shows running

### StreamX Version

1.2.3

### Flink Version

1.13.1

### Scala Version of Flink

2.11

### Error Exception

```log
No
```

### Screenshots

![image](https://user-images.githubusercontent.com/11712168/173272548-04a5d391-9f93-4f18-b69f-4b1cc050046d.png)
![image](https://user-images.githubusercontent.com/11712168/173272578-385f2a10-f370-4b83-9edc-cf47d4432817.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by waywtdcc** [comment]
➕1  I also encountered this problem.

**Comment by ysn2233** [comment]
same problem here

**Comment by chuangehh** [comment]
same problem
