### ISSUE TITLE
[Bug] Dashboard cannot display metric values

### ISSUE THREAD

**Issue by JoshTseeee** [apache/streampark#1104]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I upgraded streamx to version 1.2.4 (build from dev) today, and replaced the 1.2.3 (release-1.2.3) yml with the current version to start, and found that some metric values ​​on the dashboard could not be displayed, and the values ​​in the http interface were all zero.

### StreamX Version

1.2.4(dev)

### Java Version

1.8

### Flink Version

1.13.6

### Scala Version of Flink

2.12

### Error Exception

```log
I added a few lines of logs to the FlinkTrackingTask.java. After recompiling and starting, I found that there were applications data in TRACKING_MAP before executing stopTracking. After executing the stopTracking method(), TRACKING_MAP was emptied, and in the schedule tracking method, TRACKING_MAP is always Empty, the application cannot get the latest status and the dashboard can not display the metrics.
```

### Screenshots

<img width="1382" alt="iShot_2022-06-14_12 28 23" src="https://user-images.githubusercontent.com/26848111/173495104-f8e1a0ab-06eb-4964-a223-f2106444db78.png">
<img width="2371" alt="image" src="https://user-images.githubusercontent.com/26848111/173495120-62647a9d-70c6-49c9-9d61-bb4e0a47d9c3.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
