### ISSUE TITLE
[Bug] use catalog syntax parsing failed

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#1128]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

when `use catalog` syntax is used in the Flink SQL job, which causes the SQL verification to fail and the job cannot save the submission

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by helloworld969** [comment]
This problem seems to have not been solved in version 1.2.3

**Comment by wolfboys** [comment]
> This problem seems to have not been solved in version 1.2.3

The latest code fixed this bug
