### ISSUE TITLE
[Bug] When streamx stops a task, start savepoint, but the savepoint path is not required

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#1144]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When streamx stops a task, start savepoint, but the savepoint path is not required. If you do not specify a savepoint path to stop, the task will fail to stop and cannot be stopped again. You can only go to yarn to stop

### StreamX Version

1.2.3

### Java Version

jdk1.8

### Flink Version

1.14.3

### Scala Version of Flink

2.11

### Error Exception

```log
Background prompt savepoint path is not specified.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chuangehh** [comment]
same problem

**Comment by macksonmu** [comment]
When savepoint is on, custom savepoint is set as mandatory in the front end

**Comment by muchunjin** [comment]
@wolfboys When savepoint is on, custom savepoint is set as required in the front end. Is it OK?

**Comment by wolfboys** [comment]
When stopping, if enable savepoint policy as follows:

1. Specifying the savepoint path will keep the savepoint to the path specified by the user
2. If the savepoint path is not specified, it will be kept to the default path, and the configuration will be read (state.savepoints.dir)
----

停止时如果用户开启savepoint 策略如下:

1. 指定了savepoint path 会将 savepoint 保持到用户指定的路径下
2. 未指定 savepoint path 则会保持到 默认的路径下, 会读取配置(state.savepoints.dir)

**Comment by muchunjin** [comment]
@wolfboys ok

**Comment by muchunjin** [comment]
@wolfboys Through the test, when state.savepoints.dir is set in the configuration file flink-conf.yaml. After dir, this bug no longer appears, the job stops normally, and savepiont is normally guaranteed in state savepoints. In the path set by the dir parameter, I think this bug can be closed

**Comment by muchunjin** [comment]
@wolfboys 通过测试，当在配置文件flink-conf.yaml中设置state.savepoints.dir后，此bug不在出现，作业正常停止，savepiont正常保障在state.savepoints.dir参数设置的路径中，那么此bug我认为可以关闭了

**Comment by muchunjin** [comment]
@wolfboys 当没有指定Custom SavePoint又没有在Flink的配置文件中设置state.savepoints.dir时，可以提示必须指定Custom SavePoint或者设置state.savepoints.dir，这样可以防止停止任务出现失败的情况，是否可以？

When custom savepoint is not specified and state.savepoints.dir is not set in Flink's configuration, you can prompt that you must specify custom savepoint or set state.savepoints.dir, which can prevent the failure of stopping the task. Is it OK?

**Comment by wolfboys** [comment]
> 

Yes, it's better to do so. see Applicationserviceimpl.java 912 to 941 lines for more detail.

----
可以, 这样做比较好, 具体代码可以看看 ApplicationServiceImpl.java 912 到 941 行

**Comment by muchunjin** [comment]
> > 
> 
> Yes, it's better to do so. see Applicationserviceimpl.java 912 to 941 lines for more detail.
> 
> 可以, 这样做比较好, 具体代码可以看看 ApplicationServiceImpl.java 912 到 941 行

ok
