### ISSUE TITLE
[Bug] When Flink SQL is in the run mode of Yarn application, the job of Yarn fails, but it is still running in the state of streamx

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#1234]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Flink SQL在YARN application运行模式下，yarn的作业失败了，但是在StreamX的状态还是running

When Flink SQL is in the run mode of Yarn application, the job of Yarn fails, but it is still running in the state of streamx

### StreamX Version

1.2.4

### Java Version

jdk8

### Flink Version

1.14.3

### Scala Version of Flink

2.11

### Error Exception

```log
When Flink SQL is in the run mode of Yarn application, the job of Yarn fails, but it is still running in the state of streamx
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by waywtdcc** [comment]
+1

**Comment by waywtdcc** [comment]
@wolfboys

**Comment by hxh-plzshowme** [comment]
有解决吗？
