### ISSUE TITLE
[Bug] When stopping a job on streamx, if savepoint is not selected, but state.savepoints.dir is not set in the dynamic parameters or the flick-conf.yml configuration file. state.savepoints.dir will be prompted is not set.

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#1235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在StreamX上停止作业时，如果没有选择做savepoint，但是动态参数或flink-conf.yml配置文件中没有设置state.savepoints.dir时，会提示state.savepoints.dir没有设置，这个是之前的PR衍生的bug

When stopping a job on streamx, if savepoint is not selected, but state.savepoints.dir is not set in the dynamic parameters or the flick-conf.yml configuration file. state.savepoints.dir will be prompted is not set. This is a bug derived from PR before

### StreamX Version

1.2.4

### Java Version

jdk8

### Flink Version

1.14.3

### Scala Version of Flink

2.11

### Error Exception

```log
When stopping a job on streamx, if savepoint is not selected, but state.savepoints.dir is not set in the dynamic parameters or the flick-conf.yml configuration file. state.savepoints.dir will be prompted is not set. This is a bug derived from PR before
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by muchunjin** [comment]
The latest code has fixed this problem

**Comment by wolfboys** [comment]
> The latest code has fixed this problem

see https://github.com/streamxhub/streamx/pull/1238

**Comment by wolfboys** [comment]
fixed
