### ISSUE TITLE
[Bug] streamx配置yarn session模式界面显示问题

### ISSUE THREAD

**Issue by tomoson123** [apache/streampark#1258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

1、Setting->Flink Cluster->Add new -> Execution Mode 选择 yarn session ,填写Address和其他信息保存后，回头再编辑Address显示为空
2、Application添加->Development Mode选择Flink SQL，Execution Mode选择yarn session，Yarn Session ClusterId选择新建的yarnCluster，但是界面提示红色的Flink Cluster is required字体，填写完全后无法Submit

### StreamX Version

1.2.3

### Java Version

java8

### Flink Version

1.14.4

### Scala Version of Flink

2.12

### Error Exception

```log
1、添加yarn session环境，Address显示为空
2、Application新建填写完全后无法Submit
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
please use english
