### ISSUE TITLE
[Bug] In setting the TAB of FlinkHome, there is no place to configure FLINK_HOME.

### ISSUE THREAD

**Issue by Su1024** [apache/streampark#1261]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在Seting菜单中  选择FlinkHome 的 TAB ，页面没有配置 FLINK_HOME的地方。 查看前端控制台 存在报错。

### StreamX Version

1.2.4

### Java Version

1.8

### Flink Version

1.13.1

### Scala Version of Flink

2.12

### Error Exception

```log
[Vue warn]: Do not use built-in or reserved HTML elements as component id: code

found in
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Su1024** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/23012179/180119953-fb31e71f-7133-4e8f-a5f4-ac7b4bcb0c44.png">
<img width="1785" alt="image" src="https://user-images.githubusercontent.com/23012179/180119980-89b0a5cd-1cad-4289-bac1-8bc26b5e10a2.png">

**Comment by wolfboys** [comment]
has no title. please use english.

**Comment by Su1024** [comment]
> has no title. please use english.

sorry i forgot
