### ISSUE TITLE
[Bug] flink version missing after the first time submit 

### ISSUE THREAD

**Issue by xj90713** [apache/streampark#1282]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The flink version information was set when it was created for the first time. After saving and submitting, the flink version information is gone. And the  Execution Mode is remote.As shown below.
![image](https://user-images.githubusercontent.com/32934873/181186889-6541a156-19be-4e2f-a543-861ea2c0f0a0.png)

![image](https://user-images.githubusercontent.com/32934873/181186762-26260fab-14d9-4fef-abed-2e7b2f58aa6f.png)

### StreamX Version

1.2.4

### Java Version

Java 11

### Flink Version

flink-1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
look 【What happened】
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
