### ISSUE TITLE
[Bug] Flink Job Failure Cannot Trigger Alarm

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#1298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Alarms are configured in the flink job, such as mail, etc. But after the job fails,  there is a great chance that the alarm cannot be triggered.

### StreamX Version

1.2.4

### Java Version

JDK 1.8

### Flink Version

Flink 1.14.4

### Scala Version of Flink

2.11

### Error Exception

```log
nothing
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by youyangkou** [comment]
@xujiangfeng001 Please describe the deployment mode of the Flink job, is yarn or k8s ,Thanks.

**Comment by xujiangfeng001** [comment]
> @xujiangfeng001请描述一下 Flink 作业的部署方式，是 yarn 还是 k8s，谢谢。



> @xujiangfeng001 Please describe the deployment mode of the Flink job, is yarn or k8s ,Thanks.

yarn application mode
