### ISSUE TITLE
[Feature] Auto create route when rest-service.exposed.type is clusterIP

### ISSUE THREAD

**Issue by KyleZhang0536** [apache/streampark#1314]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When deploying flink task in k8s application mode and rest-service.exposed.type is clusterIP, streamx only create k8s service. Then, the "Flink Web UI" button redirect to an address such as {service}.{namespace}:8081. However, this address is accessible only in cluster.

### Usage Scenario

User can access Flink web UI when they use k8s application mode and rest-service.exposed.type is clusterIP.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KyleZhang0536** [comment]
Another plan is using streamx's route

**Comment by MonsterChenzhuo** [comment]
@KyleZhang0536 I don't quite understand what you mean, streamx already supports the ingress configuration.
