### ISSUE TITLE
[Bug] flink1.14，when start flink job , status always in starting

### ISSUE THREAD

**Issue by waywtdcc** [apache/streampark#1319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

flink1.14，when start flink job , status always in starting,but job has error.
use yarn application mode.

### StreamX Version

1.2.4

### Java Version

1.8

### Flink Version

1.14.5

### Scala Version of Flink

2.11

### Error Exception

```log
flink1.14，when start flink job , status always in starting,but job has error.
use yarn application mode.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Shmilyqjj** [comment]
I had the same problem on streamX 1.2.3 with flink 1.12

**Comment by msftgitsklsd** [comment]
StreamX 1.2.4 is not released, how this happen

**Comment by Shmilyqjj** [comment]
> I had the same problem on streamX 1.2.3 with flink 1.12

I had solved this problem.

When requesting yarn web proxy server, cookie:checked_<applicationId>=true is required to request app information in my yarn cluster,so this step can not get app information,and streamX will tracking app status with yarn rest api,but when it is requesting yarn rest api, streamX uses the wrong url(yarn.web-proxy.address), the correct url is activeRMIp:8088, so I modified related codes, then it worked well.

**Comment by wolfboys** [comment]
fixed
