### ISSUE TITLE
Use parallel builds to speed up building progress by build.sh

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#1320]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Use parallel builds to Speed up build time by build.sh

### StreamX Version

none

### Flink Version

 none

### Scala Version of Flink

none

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
We are looking forward to your contribution 😁
