### ISSUE TITLE
Collect suggestions for StremaX rename

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#1335]
StreamX will be renamed, We appreciate your support!

The name rules are as follows :

- The name is easy to understand

 - It is best to have a name with the meaning of stream

- The name cannot be the same as the existing project name

- The name is not registered as a trademark

Thank you!

----

大家好：

StreamX 将被重新命名，感谢你的支持!

名称规则如下：

1) 这个名字很容易理解
2) 最好是一个具有流处理(stream)含义的名称
3) 不能与已有项目名称相同
4) 该名字未被注册成商标

谢谢大家

**Comment by allenwod** [comment]
StreamBridge--it means a bridge connecting different data sources by streaming

**Comment by SoberChina** [comment]
- StreamZoo

- StreamRocks

- StreamReins

**Comment by lianxiaobao** [comment]
StreamCompute

**Comment by youyangkou** [comment]
StreamManner
StreamAir

**Comment by youyangkou** [comment]
StreamAir

**Comment by chuangehh** [comment]
StreamTik  
StreamFly
StreamBok

**Comment by monrg** [comment]
HyperStream

**Comment by KWIGNIS** [comment]
streambot、stream wave、stream vortex、stream firefly（流萤）、firefly stream（萤流）、stream start（流始）、stream current、stream weaving、stream lot、stream fabric

**Comment by wolfboys** [comment]
StreamPark

**Comment by wolfboys** [comment]
Streamful

**Comment by wolfboys** [comment]
StreamRay

**Comment by wolfboys** [comment]
StreamWalk

**Comment by wolfboys** [comment]
Streamify

**Comment by wolfboys** [comment]
Streamful

**Comment by MonsterChenzhuo** [comment]
Freighter

**Comment by msftgitsklsd** [comment]
StreamIdea

**Comment by wolfboys** [comment]
thanks everyone, finnally, the new name is: StreamPark

**Comment by forrestnie** [comment]
StreamPark
