### ISSUE TITLE
[Bug]Changing the name of the base image in k8s mode does not trigger a rebuild of the image

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1342]
The task was submitted and found that the base image was missing the jar package, I added the jar again and regenerated the base image, I modified the history of the base image name, this task is not re-type the image. The task will not retype the image.

有任务提交上去发现基础镜像少jar包，我重新添加jar后，重新生成了基础镜像，我修改历史的基础镜像名称，这个任务是不会重新打镜像的。导致提交上去还是依旧报错。
<img width="1026" alt="图片" src="https://user-images.githubusercontent.com/60029759/184049106-2cb69e97-b9ca-4607-90e3-ec826511561f.png">

**Comment by youyangkou** [comment]
Is this because there is already a mirror on K8S node, and your pod pull strategy is not always up-to-date?
这个是不是因为K8S node上面已经有镜像了，你pod拉取策略不是每次都拉最新导致的？

**Comment by MonsterChenzhuo** [comment]
@youyangkou 不是这个原因，已经配置了
<img width="676" alt="图片" src="https://user-images.githubusercontent.com/60029759/184098209-1e4b85a0-0960-4222-8a85-f03c13a0fc38.png">
