### ISSUE TITLE
[Feature]Support flinksql and gitlab to play through

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1355]
Support flinksql and gitlab to play through
When a flinksql task with the name dwd_first_f_d is created, a dwd_first_f_d folder will be synchronized under the specified project in gitlab, and inside the folder will be, dwd_first_f_d.sql file, which is used to record the sql, and application.yaml configuration file to record configuration information.
We can generate a gitlab project file from streamx, and we can also generate a streamx project by loading a file from gitlab

**Comment by Su1024** [comment]
looks great

**Comment by Su1024** [comment]
How to pull the content modified on gitlab
