### ISSUE TITLE
[improve] After flink 1.15.1 drop support for Scala 2.11.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#1371]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

We should plan how to support feature and old version of flink.

### StreamX Version

none

### Flink Version

none

### Scala Version of Flink

none

### Error Exception

```log
none
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, At present, the default is Flink version 1.5.0 or above, which is not supported by Scala 2.11
