### ISSUE TITLE
[Feature][K8S] Namespace Management

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1397]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Streamx Platform Namespaces let you share the platform between multiple teams, applications or use cases in a secure and easy way. Logging profiles and deployment defaults make it easy to distribute best practices within the organization while preserving the autonomy of your teams.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lvshaokang** [comment]
The namespace means that multi-tenant concept?

**Comment by youyangkou** [comment]
Does managing namespace only refer to making it easier for users to develop choices, or is it the idea of letting streamx do K8S ns rights management?
