### ISSUE TITLE
[Bug] StreamX "Session Flink Cluster" cannot view flink log

### ISSUE THREAD

**Issue by yebukong** [apache/streampark#1416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When creating a flink k8s native session cluster with streamx, the Flink cluster can be started normally, but the log cannot be viewed. When viewing the mounting of Flink config, it is found that only the "flink-conf.yaml" file is mounted, and the "log4j-console.properties, logback-console.xml" file is missing . The same problem exists in the yarn session mode.

在用StreamX创建一个flink k8s native Session集群时，flink集群可以正常启动，但是日志无法查看，在查看flink config挂载情况时发现只挂载了"flink-conf.yaml"文件，缺失了"log4j-console.properties,logback-console.xml"文件。yarn session 模式也有相同的问题.

Recurrence steps：
1.Menu path ： StreamX - Setting - Flink Cluster
![image](https://user-images.githubusercontent.com/26626551/185602433-3b9e6a28-6217-471b-a5f7-98b182b53269.png)
2.k8s native Session cluster Config
![image](https://user-images.githubusercontent.com/26626551/185602697-8fe4d1b0-d3ca-401f-ba8d-b960cb13db10.png)
3.cannot  view jobmanager log
![image](https://user-images.githubusercontent.com/26626551/185602927-716fb3ca-65b5-4526-a469-da66e68cccb9.png)
4.jobmanager container std log
![image](https://user-images.githubusercontent.com/26626551/185602976-d99462ef-51c9-4a4d-8f22-5aa685e80320.png)
5.flink config
![image](https://user-images.githubusercontent.com/26626551/185603250-bcbcf6a8-4455-4f3e-942f-ad05a2216c79.png)

### StreamX Version

1.2.3

### Java Version

1.8

### Flink Version

1.14.5

### Scala Version of Flink

2.11

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thank you for your feedback, which is already being solved

**Comment by yebukong** [comment]
> Thank you for your feedback, which is already being solved

@wolfboys 

When creating a flink k8s native session cluster with streampark2.0.0 .This problem still exists.But flink yarn session can view logs normally.
上述问题在k8s native session模式下依然存在，不过flink yarn session下日志可以正常查看

StreamX Version ： 2.0.0
Java Version ： 1.8
Flink Version ： 1.14.5
Scala Version of Flink ： 2.11

![image](https://user-images.githubusercontent.com/26626551/202660725-0ce66297-f415-4881-b369-462e6bd11db5.png)
![image](https://user-images.githubusercontent.com/26626551/202660846-1652a2cc-13ee-4910-a8d0-f82812546783.png)
![image](https://user-images.githubusercontent.com/26626551/202661395-cea997ca-19bd-41bd-ada0-ce131b93c697.png)
![image](https://user-images.githubusercontent.com/26626551/202661525-7222e87d-cca1-4dea-b753-772991e45c37.png)
![image](https://user-images.githubusercontent.com/26626551/202664055-ca60e6fe-d8f9-4484-8d9a-34f3280ab7b6.png)
