### ISSUE TITLE
[Bug] User Privilege Control does not support job isolation

### ISSUE THREAD

**Issue by conorzhao** [apache/streampark#1424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Users can mutually operate jobs created by other users, and the platform has no operation audit records, so it is difficult to ensure job security.

### StreamX Version

1.2.3

### Flink Version

all version

### Scala Version of Flink

all version

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
There is no plan to complete this function in the short term. If you have idea, we welcome contributions

**Comment by 1996fanrui** [comment]
Hi @wolfboys , job permission, team permission and audit log are important for user. I can contribute these features.

**Comment by wolfboys** [comment]
HI @1996fanrui  about team permission , you can see: https://github.com/apache/incubator-streampark/pull/1517 
This PR function is half implemented, and the contributor will not continue, so it is rolled back, 
job permission and team permission, you can open a special propsol to track these.
