### ISSUE TITLE
[Bug] The mapping state is abnormal

### ISSUE THREAD

**Issue by conorzhao** [apache/streampark#1429]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

If streamx loses the job connection, you can perform mapping remapping, but when mapping is in progress, the job on yarn is killed, then this state is always mapping and will not change.

It is recommended that when the mapping fails to work (retry a certain number of times), the status is updated to failed
### StreamX Version

1.2.3

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
The mapping state is abnormal
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thank you for your feedback, and we are following up to fix this issus

**Comment by wolfboys** [comment]
fixed.
