### ISSUE TITLE
[Bug] Execute mysql-schema.sql, there will be old users who do not know to clear the data of 'streamx' database

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/streampark#1492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mysql-schema.sql
```
create database if not exists  `streamx`  default character set utf8mb4 collate utf8mb4_unicode_ci ;
use `streamx`;
```

Premise: 
my mysql already exists Name the database with 'streamx'

I use mysql as the data source of streamx, and configure the application-mysql.yml of `streamx-console-service` to access the 'streamx0831' database.

When I execute `mysql-schema.sql` of the latest dev branch, according to the previous DDL release habits of streamx, it only operates DDL and does not delete the DB library, so I neglected to check `mysql-schema.sql` execute content. In the end I lost the data of the original streamx library. If this is production level, it may allow developers to make mistakes.

前提：我的mysql已经存在 以'streamx'命名数据库，我使用mysql当做streamx的数据源，并且将`streamx-console-service`的application-mysql.yml 配置访问'streamx0831'数据库。

当我执行 最新dev分支的mysql-schema.sql，按照以前的streamx的DDL发版习惯，仅只会操作DDL，并不会对DB库做删除操作，所以我忽略了检查 `mysql-schema.sql`执行内容。 最后我丢失了原有的streamx库的数据。 若这是生产级别，可能会让开发人员犯错

### StreamX Version

v1.2.4

### Flink Version

v1.14.5

### Scala Version of Flink

2.12

### Error Exception

```log
The original data is cleared
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
