### ISSUE TITLE
[Feature] Code format，translate ZH to EN

### ISSUE THREAD

**Issue by lvshaokang** [apache/streampark#1522]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Code format，translate ZH to EN

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good job!

**Comment by lvshaokang** [comment]
follow #1560

**Comment by lvshaokang** [comment]
closed
