### ISSUE TITLE
[Feature] Add tags to jobs for easy retrieval and archiving

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/streampark#1525]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add tags to jobs for easy retrieval and archiving

`Retrieve tags`

<img width="476" alt="图片" src="https://user-images.githubusercontent.com/7881241/188497602-e5bbd00a-07b7-4521-9853-617e339af695.png">

`Add tags`
<img width="736" alt="图片" src="https://user-images.githubusercontent.com/7881241/188497725-b1a4a782-a3e3-425c-9226-323463d85796.png">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
great features, good job😁
