### ISSUE TITLE
[Bug] when the streampark precess not kinit keytab before startup

### ISSUE THREAD

**Issue by atovk** [apache/streampark#1539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when the streampark precess not kinit keytab before startup, the jvm cant get current TGT, 

```scala
// lazy get current tgt, but tgt is null, return tgtRefreshTime is 0
  private[this] lazy val tgtRefreshTime: Long = {
    val user = UserGroupInformation.getLoginUser
    val method = classOf[UserGroupInformation].getDeclaredMethod("getTGT")
    method.setAccessible(true)
    tgt = method.invoke(user).asInstanceOf[KerberosTicket]
    Option(tgt) match {
      case Some(value) =>
        val start = value.getStartTime.getTime
        val end = value.getEndTime.getTime
        ((end - start) * 0.90f).toLong
      case _ => 0
    }
  }

```
then init the renew tgt task.schedule init fail... this delay and period cant be less 0;
throw exceltion: **IllegalArgumentException("Non-positive period.")** , **IllegalArgumentException("Negative delay.")**

### StreamPark Version

1.2.3/1.2.4

### Java Version

1.8

### Flink Version

all

### Scala Version of Flink

all

##### Timer.class
```java

public void schedule(TimerTask task, long delay, long period) {
    if (delay < 0)
        throw new IllegalArgumentException("Negative delay.");
    if (period <= 0)
        throw new IllegalArgumentException("Non-positive period.");
    sched(task, System.currentTimeMillis()+delay, -period);
}

```

```log
throw exceltion: 
IllegalArgumentException("Non-positive period."), 
IllegalArgumentException("Negative delay.")
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by atovk** [comment]
@wolfboys maybe we can let the tgtRefreshTime default return greater than 0

**Comment by wolfboys** [comment]
return an appropriate value? How about 2 hours?
