### ISSUE TITLE
[Bug] upgrade to hadoop 2.10.2 (fixes some security issues)

### ISSUE THREAD

**Issue by pjfanning** [apache/streampark#1545]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

See https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common

2.10.2 has just 1 CVE while 2.10.1 has 3

### StreamPark Version

dev branch

### Flink Version

n/a

### Scala Version of Flink

n/a

### Error Exception

```log
n/a
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
LGTM
