### ISSUE TITLE
[Bug]  Tags and orther column display incorrectly when tag is empty

### ISSUE THREAD

**Issue by youyangkou** [apache/streampark#1552]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When tags of Application is empty, each column of data in the job row of the home page is displayed incorrectly.

### StreamPark Version

1.2.4/dev

### Java Version

1.8

### Flink Version

1.13

### Scala Version of Flink

2.11

### Error Exception

```log
TypeError:Cannot read properties of null(reading 'split')
```

### Screenshots

![image](https://user-images.githubusercontent.com/33364356/189069538-e5552f2e-b760-4f44-99e6-1fc169ab9ec0.png)
![image](https://user-images.githubusercontent.com/33364356/189069560-49a4c680-fa0f-4add-b0dd-a283db904080.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
indeed a bug, thanks for you fix it.
