### ISSUE TITLE
[Feature] enable CodeQL static code analysis

### ISSUE THREAD

**Issue by pjfanning** [apache/streampark#1555]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

It's possible to turn on CodeQL analysis for a Github project with just a few clicks.

It will scan your code for security weaknesses and suggest changes.

https://codeql.github.com/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
thanks for your suggestion, emmmm, LGTM.com will be shut down in December 2022, recommend that we use GitHub code scanning instead. As an interim solution, we can try it.

**Comment by pjfanning** [comment]
@wolfboys If you look at https://github.com/apache/incubator-streampark/security - there should be 'Code scanning alerts' option that you can enable. This is only visible to project members (I can't see it but I can see it on projects that I own or am a project member of). The people who developed LGTM.com were hired by Github and you don't need to use LGTM.com any more.

**Comment by wolfboys** [comment]
Thank you very much for your suggestion, some configurations, I need time to learn and use. our project just joined the apache incubator, we have to learn in many places, I don’t know how other projects do it, whether there are better other ways

**Comment by wolfboys** [comment]
@pjfanning PTAL https://github.com/apache/incubator-streampark/pull/1558

**Comment by pjfanning** [comment]
looks good - the run even found a few issues
