### ISSUE TITLE
[Bug] 发送告警的邮箱是否开启SSL切换不好使

### ISSUE THREAD

**Issue by lwzhangMr** [apache/streampark#1562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

发送告警的邮箱是否开启SSL 配置切换不好使，其他配置应该也会有问题。问题代码如下：
![image](https://user-images.githubusercontent.com/31753959/189310626-1a1ca69c-094a-4d42-b4c6-6214a4269165.png)
当页面修改配置后，内存中的hash变量改了，但是其他引用实例中已经有值，不会再重新赋值了。所以配置未生效。

### StreamPark Version

1.2.4

### Java Version

1.8

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
alert.email.ssl item  modification does not take effect
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @lwzhangMr , thanks for your feedback. After analyzed, I think it's a bug. Would you like to fix it?
