### ISSUE TITLE
[Bug] The versionId always is 100k when copy a new application

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1565]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The versionId always is 100k when copy a new application, it is caused by #1354 

<img width="994" alt="image" src="https://user-images.githubusercontent.com/38427477/189492304-a18799d3-76df-4827-9489-7ee51eba443b.png">

### StreamPark Version

The latest dev branch

### Flink Version

*

### Scala Version of Flink

*

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. this bug has been fixed, see: https://github.com/apache/incubator-streampark/pull/1559

**Comment by 1996fanrui** [comment]
Thanks for your reminder, I close it now.
