### ISSUE TITLE
[Bug] Flink version don't be changed after change flink home

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Flink version don't be changed after change flink home.

For example, flink home is changed from /opt/flink/1.16-SNAPSHOT to /opt/flink/flink-1.15.2, but the flink version don't be changed. It affects the flink version in the application page.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/38427477/189494932-fe0ccf03-5bf6-46a4-922a-6022f4355786.png">

![image](https://user-images.githubusercontent.com/38427477/189494988-80606aad-4c1e-4e3b-a6af-39b84222274b.png)

### StreamPark Version

the latest dev branch.

### Flink Version

*

### Scala Version of Flink

*

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lvshaokang** [comment]
Thanks for you feedback, @1996fanrui 
@wolfboys PTAL.
