### ISSUE TITLE
[Bug] There is memory leak inside CheckpointProcessor 

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1569]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The checkPointCache inside CheckpointProcessor is just put and get, all data are not removed anywhere.

### StreamPark Version

the latest dev branch

### Flink Version

*

### Scala Version of Flink

*

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
thanks for your suggestion, welcome to improve this issue.

**Comment by 1996fanrui** [comment]
Yeah, I am working on this.
