### ISSUE TITLE
[Bug] Fix the wrong duration

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

It show the `1h -26m`, but it should show the `34m`.

![image](https://user-images.githubusercontent.com/38427477/189811151-73c7612c-4ac7-4491-ad4b-2f7be2c63292.png)

![image](https://user-images.githubusercontent.com/38427477/189811168-3862e888-ba06-4634-a622-eb0001b9ae27.png)

### StreamPark Version

The latest dev branch

### Flink Version

All

### Scala Version of Flink

All

### Error Exception

```log
*
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
I try to fix it

**Comment by caicancai** [comment]
I want to try to fix it

**Comment by youyangkou** [comment]
> I want to try to fix it

sorry,this bug has been fixed and this issue has been closed.
