### ISSUE TITLE
[Improve] failed to execute all unit tests

### ISSUE THREAD

**Issue by lvyanquan** [apache/streampark#1597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Failed to execute 'mvnw clean package' under the directory of this project, the execution will be blocked as following:
```
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ streampark-console-service ---
[INFO] Surefire report directory: /Users/admin/IdeaProjects/incubator-streampark/streampark-console/streampark-console-service/target/surefire-reports
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running CompletableFutureTest
Force cancel future.
The future is cancelled.
Future is timed out.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.107 sec - in CompletableFutureTest
Running RefreshCacheTest
2022-09-14 00:05:20
The future is done.
The future is done.
2022-09-14 00:05:30
2022-09-14 00:05:40
2022-09-14 00:05:50
2022-09-14 00:06:00
2022-09-14 00:06:10
......
```

### StreamPark Version

1.2.4

### Java Version

1.8

### Flink Version

1.14

### Scala Version of Flink

2.12

### Error Exception

```log
@Test
    public void task() throws InterruptedException {
        System.out.println(DateUtils.format(new Date(), DateUtils.fullFormat(), TimeZone.getDefault()));
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                System.out.println(DateUtils.format(new Date(), DateUtils.fullFormat(), TimeZone.getDefault()));
            }
        }, 1000 * 10, 1000 * 10);
        Thread.sleep(Long.MAX_VALUE);
    }
```
this method doesn't exit.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Most open-source projects skip test when package: `mvnw clean package -DskipTests`

**Comment by lvyanquan** [comment]
Yeah, it's not a bug that blocks main process and will have no effort on use of the product. But I think unit test is still a way to improve code quality and code review. 
---- separate line ----
Sorry. Then I found we actually skip these two modules in gitHub action check, in action of "Maven Package Test", we use
```
Run mvn -B test -pl '!streampark-plugin/streampark-jvm-profiler,!streampark-console/streampark-console-service' -am
```
So this class won't block the gitHub action of test, but I think it's still unnecessary.  

I will close this issue later if no other opinion is proposed.

**Comment by wolfboys** [comment]
Thanks for your feedback, look at it this way, there is really no need this testcase
