### ISSUE TITLE
The VVR version of Aliyun Flink is not supported

### ISSUE THREAD

**Issue by fantasticKe** [apache/streampark#1603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="513" alt="image" src="https://user-images.githubusercontent.com/29895551/190136321-ac1b9750-800d-43bb-a1ae-f6426f2ca7f7.png">

### StreamPark Version

1.2.3

### Flink Version

1.13

### Scala Version of Flink

2.11

### Error Exception

```log
The current Scala version of StreamX is 2.11.12, but the scala version of Flink to be added is 2.11-1.13-vvr-4.0.12, which does not match, Please check
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @fantasticKe , thanks for your feedback.

I think the root cause is StreamPark parse the scala version from flink-dist_(.*)-(.*).jar. And the second `(.*)` is the scala version.

You can try to rename the flink-dist_(.*)-(.*).jar inside VVR version, change the second `(.*)` to 2.11. I think it can work after change.

**Comment by fantasticKe** [comment]
yes,i got it. thx

**Comment by fantasticKe** [comment]
> Hi @fantasticKe , thanks for your feedback.
> 
> I think the root cause is StreamPark parse the scala version from flink-dist_(._)-(._).jar. And the second `(.*)` is the scala version.
> 
> You can try to rename the flink-dist_(._)-(._).jar inside VVR version, change the second `(.*)` to 2.11. I think it can work after change.

yes,i got it. thx

**Comment by wolfboys** [comment]
supported
