### ISSUE TITLE
[build] speed up build progress.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#1610]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, The compile progress have custom too much time and need to speed up.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
I have tested on my local, after tuning performance can reduce 1/3 time when compiling this project.

**Comment by wolfboys** [comment]
> I have tested on my local, after tuning performance can reduce 1/3 time when compiling this project.

good job👍
