### ISSUE TITLE
[Bug] default password is wrong

### ISSUE THREAD

**Issue by selectbook** [apache/streampark#1614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The default password in user guide is streamx, but in a resent pr I saw the password was changed to streampark. So the user guide document should change the default password to streampark.

### StreamPark Version

1.2.4

### Java Version

1.8

### Flink Version

1.14

### Scala Version of Flink

2.12

### Error Exception

```log
SignIn failed, authentication error
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinzhuxiansheng** [comment]
Someone has submitted a pr to fix a similar issue and it has been merged into dev. Pull the latest code, initialize DB data
refer:  https://github.com/apache/incubator-streampark/pull/1612

**Comment by selectbook** [comment]
@xinzhuxiansheng I mean the user guide doc should modify the default password. And the documentation on the official website doesn't seem to be in the source code, I can't find it.

**Comment by 1996fanrui** [comment]
Hi @selectbook 

The user guide doc  is maintained in [streampark-website](https://github.com/apache/incubator-streampark-website). You can update it there.

**Comment by selectbook** [comment]
ok, I have updated it

**Comment by 1996fanrui** [comment]
@selectbook please help close this issue, thanks.
