### ISSUE TITLE
[Task Scheduling] Support scheduling database SQL

### ISSUE THREAD

**Issue by ChenpiDog** [apache/streampark#1627]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, the landing scenarios of Flink are limited. Batch processing still requires the help of database SQL and other technologies. It is expected that the scheduled scheduling function of database SQL can be added.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @ChenpiDog , I'm sorry, I don't understand your mean:`Batch processing still requires the help of database SQL and other technologies.`.
 
Do you want to schedule your Flink Batch job with other scheduling frameworks? If yes, you can follow this issue. #640

**Comment by ChenpiDog** [comment]
@1996fanrui For example, MySQL and Greenplum SQL statements.

**Comment by ChenpiDog** [comment]
@1996fanrui It is hoped that streampark can schedule database sql to achieve unified scheduling and management of batch tasks and stream processing tasks, otherwise, additional tools such as airflow will have to be used.

**Comment by ChenpiDog** [comment]
> Hi @ChenpiDog , I'm sorry, I don't understand your mean:`Batch processing still requires the help of database SQL and other technologies.`.
> 
> Do you want to schedule your Flink Batch job with other scheduling frameworks? If yes, you can follow this issue. #640

I mean that the batch processing capability of flink is limited, and the database sql used in production does batch processing.
