### ISSUE TITLE
[Proposal] Support team feature

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1629]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Task list

-  #1729 
- #1753 
- #1807 
- #1754 
-  #1730 
-  #1731 
-  #1732
-  #1827 
- #1844 
- #1845 
- #1880 
- #1847 

### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Background: 

Currently, StreamPark doesn't support team, so all projects and applications will be showed in the same pages. For some companies, there are too many departments or teams. For ease of use and security, they shouldn't view the applicaton list of other teams.

## Solution

Support the team feature, the team as the _**workspace**_ in the WebUI. 

User needs to choose a team first.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/38427477/194462674-25d23d39-76de-4276-a8dd-4756e64339cb.png">

### The relationship between app, project and team

- Each project can only belong to one team.
- Each app can only belong to one team.
- The front end only shows a list of projects and apps for the current team. 
- The app or project is created by default also belong to the current team.

Database table: `t_flink_app` and `t_flink_project`, they're old tables, we need to add the new filed team_id. These 2 tables need to add index for team_id, because WebUI usually query app or project list by teamId.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/38427477/194463009-e51c051b-1b90-49b8-887d-60201741fad4.png">

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/38427477/194462931-7128de59-fd07-4169-9176-a69106a210d8.png">

### Team management

Create/Modify/Delete/View team information.

Database table: `t_team`, it's a new table. We need to create a default team.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/38427477/194463077-b8db09bc-cc41-4743-a14c-f810b3eca280.png">

### Member management

Add a Member management page, and the features are as follows:

- Manage the list of members within a Team, that is, which members of the current team?
- Manage the roles of each member of the team, that is, what is the role of the members in the current team?

Database table: `t_user_role`, it's an old table, we need to add the new filed: team_id.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/38427477/194463162-6c0ee893-1861-4529-aa53-39a9dd4e6088.png">

Note: 

- Each user can belong to multiple teams
- Each team can have multiple users
- Each user can have different roles in different teams, for example: userA is team_admin in team1, userA is developer in team2

> Note: User must choose the team in 3 pages: Application, Project and Member Management.

### Role management 

We just set whether new user is system admin during creating a new user. The other roles will be management in the team management page.

> Note: System admin is the super admin for all teams.

Database table: `t_user`, it's an old table, we need to add the new filed: user_type.

Database table: `t_role`, it's an old table, we need to add a new role: team_admin.  It will be the super admin inside team(manage team members, operate all apps and projects).

<img width="649" alt="image" src="https://user-images.githubusercontent.com/38427477/194463330-0b42619d-d304-4026-9aa8-dec277fe501d.png">

### Compatibility mechanism:

- All old apps and projects will be migrated to the default team.
- All old developers will be granted to the default team developer.

### ER model

The fields highlighted in the diagram are relational fields.

![Team Management ER HL](https://user-images.githubusercontent.com/38427477/190847179-744195df-b276-4019-90c7-f44c60de3dd2.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 1996fanrui** [comment]
Hi @wolfboys , I have sorted out the team feature. Please help take a look in your free time, thanks a lot.

If it's ok, I will start develop the backend code, and try to develop front end. I will let you know, if I need your help.

**Comment by lvshaokang** [comment]
Hi @1996fanrui, Thanks for you feedback! This is a nice proposal.  
Could you offer the ER model about the team feature to describe their relation in more detail?

**Comment by 1996fanrui** [comment]
Hi @lvshaokang , thanks for your nice suggestion, I have updated the ER model, PTAL in your free time, thanks a lot~

**Comment by wolfboys** [comment]
It looks good, The team here is actually the concept of workspace.  There are a few issues that need to be clarified
1) one project or job only belong to one team?
2) What is the affiliation between users and teams, one to one?
3) Do we need an association table between team and user (team and job)?

**Comment by 1996fanrui** [comment]
> It looks good, The team here is actually the concept of workspace. There are a few issues that need to be clarified

@wolfboys , thank you for reviewing the solution. I have updated the doc for these questions. 

> 1. one project or job only belong to one team?

- Each project can only belong to one team.
- Each app can only belong to one team.


> 2. What is the affiliation between users and teams, one to one?

- Each user can belong to multiple teams
- Each team can have multiple users
- Each user can have different roles in different teams, for example: userA is team_admin in team1, userA is developer in team2

> 3. Do we need an association table between team and user (team and job)?

Add the team_id to these tables:
- `t_flink_app`
- `t_flink_project`
- `t_user_role`

**Comment by wolfboys** [comment]
done
