### ISSUE TITLE
[Bug] When Flink is started in the on yarn mode, the total task and running task indicators are not accurately obtained

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#1632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When Flink is started in the on yarn mode, when the job becomes running, the task is still starting. At this time, the task has not yet become running, so StreamPark will not obtain the total task and running task quantity accurately

### StreamPark Version

1.2.3

### Java Version

jdk 1.8

### Flink Version

1.14.3

### Scala Version of Flink

2.11

### Error Exception

```log
When Flink is started in the on yarn mode, when the job becomes running, the task is still starting. At this time, the task has not yet become running, so StreamPark will not obtain the total task and running task quantity accurately
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
@macksonmu please close this issue
