### ISSUE TITLE
[Bug] When the version of streampark is defined as a variable, there will be problems when relying on third-party services

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/streampark#1636]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When the version of streampark is defined as a variable,
```
  <groupId>org.apache.streampark</groupId>
  <artifactId>streampark</artifactId>
  <packaging>pom</packaging>
  <version>${reversion}</version>
```
there will be problems when relying on third-party services !

Execute the package command of streampark (mvn clean install -DskipTests -Denv=prod) which will install the jar to the local maven repository. So look at the pom.xml of the local warehouse streampark jar, its version has also become a variable

<img width="345" alt="图片" src="https://user-images.githubusercontent.com/7881241/190904100-050b9e30-d709-4fce-b280-37304db8fac3.png">

<img width="1153" alt="图片" src="https://user-images.githubusercontent.com/7881241/190904077-00378553-94fa-4721-93f3-42744420c389.png">

### StreamPark Version

1.2.4

### Flink Version

1.14.5

### Scala Version of Flink

2.12

### Error Exception

```log
`In the streamx-quickstart project`

Cannot resolve org.apache.streampark:streampark:pom:${reversion} was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced

The end result is missing dependencies in the streamx-quickstart project
```

### Screenshots

![图片](https://user-images.githubusercontent.com/7881241/190904227-355f9e0e-4536-4ba5-aa40-7c8f91506c2c.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinzhuxiansheng** [comment]
@wolfboys  Change version to a specific value (eg `dev-SNAPSHOT`)

**Comment by wolfboys** [comment]
> @wolfboys Change version to a specific value (eg `dev-SNAPSHOT`)

There is a issue. you can refer to other Apache projects, such as the solutions in Flink

**Comment by lvshaokang** [comment]
I will be look at later. cc @wolfboys
