### ISSUE TITLE
[Bug] The main method caused an error: StreamTableEnvironment can not run in batch mode for now, please use TableEnvironment.

### ISSUE THREAD

**Issue by yinshan612** [apache/streampark#1642]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After I changed the mode of the built-in sqldemo from streaming to batch, I reported an error

### StreamPark Version

1.2.4

### Flink Version

1.13.5

### Scala Version of Flink

2.12

### Error Exception

```log
After I changed the mode of the built-in sqldemo from streaming to batch, I reported an error
```

### Screenshots

![f41f711301c0b3462875617213041de](https://user-images.githubusercontent.com/85284614/190943836-1ecdd9da-e805-478c-bf36-88a035f8cb27.jpg)
![ba019eaf5598ec5b1f51e7642021f50](https://user-images.githubusercontent.com/85284614/190943844-3092a9a7-16bb-4af8-aff9-aed6bf1331f7.jpg)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback,  It's a bug, we'll fix it quickly
