### ISSUE TITLE
[Bug] extractProgramArgs parsing args parameter error

### ISSUE THREAD

**Issue by fantasticKe** [apache/streampark#1649]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I pass the parameter to flink with --name "xx xx xxx",  com.streamxhub.streamx.flink.submit.`trait`.FlinkSubmitTrait.extractProgramArgs parse --name "xx, xx, xxx"

![Uploading image.png…]()

### StreamPark Version

1.2.3

### Flink Version

1.13

### Scala Version of Flink

2.11

### Error Exception

```log
error args
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi  @fantasticKe , your image is broken, please upload it again.
