### ISSUE TITLE
[ci] build optimization

### ISSUE THREAD

**Issue by wuchunfu** [apache/streampark#1682]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

build optimization

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinzhuxiansheng** [comment]
@wuchunfu   Thank you for your feedback, can you introduce the idea of optimization?

**Comment by wuchunfu** [comment]
> @wuchunfu Thank you for your feedback, can you introduce the idea of optimization?

@xinzhuxiansheng At present, the effect does not seem to be too obvious. I will do this later when I need it. I will close this issue first.
