### ISSUE TITLE
[Feature] Support Team Management

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1729]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support Team Management, this is the first subtask of #1629 .

This issue includes team management, team member management, all old projects and apps will be migrated to the default team.

### Related issues

#1629

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Great feature, looking forward to it.
