### ISSUE TITLE
vim /xxx/incubator-streampark/deploy/docker/docker-compose.yaml have a space

### ISSUE THREAD

**Issue by believe-future** [apache/streampark#1748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

have a space

### StreamPark Version

Version: 1.2.4 

### Flink Version

flink1.14.5

### Scala Version of Flink

scala_2.12

### Error Exception

```log
volumes:
      - flink1.14.5:/  streampark/flink/flink1.14.5
    restart: unless-stopped
have a space?
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinzhuxiansheng** [comment]
@MonsterChenzhuo  I remember you have fixed this
