### ISSUE TITLE
[Feature] Improve the team related front-end

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1753]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Sorted out some front-end improvements to improve user experience:

1. When the user only belongs to one team, StreamPark can help the user select the team by default
2. When a user belongs to multiple teams, StreamPark can help the user to select the last used team by default
3. After the team is changed, the front end needs to execute the logic after login (due to different team permissions may be different)
4. The teamId is stored in storage, and there is a bug: when the second front-end page is opened and another team is selected, the team displayed on the first page will not change, but the teamId of the requesting back-end will change.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @wolfboys , I sorted out some front-end improvements here, thanks for your help~

**Comment by wolfboys** [comment]
> Hi @wolfboys , I sorted out some front-end improvements here, thanks for your help~

ok, I will join, Let's do it together

**Comment by MonsterChenzhuo** [comment]
<img width="1436" alt="图片" src="https://user-images.githubusercontent.com/60029759/194692874-3f5f962c-e28e-49b7-95bf-c876da9552a3.png">
There are three options, and no matter which one I click, it still defaults to `default`.
<img width="1261" alt="图片" src="https://user-images.githubusercontent.com/60029759/194692886-4085c012-3678-4ee0-9035-8c70b3c7dbe9.png">

**Comment by MonsterChenzhuo** [comment]
<img width="1184" alt="图片" src="https://user-images.githubusercontent.com/60029759/194693447-9c957bb0-dfea-4611-be51-fbb75c0c9469.png">
