### ISSUE TITLE
[Improve] Project compilation failure related issues improvement 

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#1765]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

then Execute build.sh to compile the project, finally failed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
Hi @wolfboys , I want to find out the problem, pls assign to me.

**Comment by wolfboys** [comment]
> Hi @wolfboys , I want to find out the problem, pls assign to me.

done

**Comment by GOODBOY008** [comment]
Because of local machine's `JAVA_HOME` was setted with `JRE`'s path , so build with `maven wrapper` occurs the error with message  `No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
`.

**Comment by wolfboys** [comment]
fixed
