### ISSUE TITLE
[Bug] Docker-compose deployment unavailable

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#1783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

With several major changes to streampark docker-compose is no longer available and we need to update it accordingly, including the documentation：

1. Support for multiple data sources to solve the following scenarios.
a.Newcomer experience function --> h2 data
b.Company rapid deployment-->mysql, pgsql database

2. Support multi-mode submission.
a.remote mode-->test and trial
b.k8s mode commit --> production use

3.Rapid deployment capability with just one line of command

4.Complete documentation support

### StreamPark Version

1.2.4

### Flink Version

1.14

### Scala Version of Flink

2.12

### Error Exception

```log
无
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by MonsterChenzhuo** [comment]
1.https://issues.apache.org/jira/browse/INFRA-23756 docker hub apply ✅
2.https://issues.apache.org/jira/browse/INFRA-23754 github action whitelist apply✅
3.https://issues.apache.org/jira/browse/INFRA-23764 add Actions secrets✅

**Comment by wolfboys** [comment]
👍 good job

**Comment by MonsterChenzhuo** [comment]
<img width="1437" alt="图片" src="https://user-images.githubusercontent.com/60029759/195776863-98b81b46-2706-48a6-b03a-5dacdf5ef00e.png">
https://hub.docker.com/r/apache/streampark/tags
