### ISSUE TITLE
[Bug][console]MySQL datasource cannot be used normally

### ISSUE THREAD

**Issue by shangeyao** [apache/streampark#1784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver

### StreamPark Version

1.2.4

### Java Version

1.8.0_345

### Flink Version

1.15.2

### Scala Version of Flink

2.12

### Error Exception

```log
java.lang.IllegalStateException: Cannot load driver class: com.mysql.cj.jdbc.Driver
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lvshaokang** [comment]
Hi @shangeyao, thanks for you feedback.
The license of mysql dependency is an category-x[1], which is not expected by the asf-project.
If you want to use mysql as the database, you can place the mysql driver under the lib.

[1] https://apache.org/legal/resolved.html#category-x
