### ISSUE TITLE
[Build] Use multiple java version build check.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#1802]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Use multi java version build check.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
@wolfboys Currently , I want to add java 8 and 11 as ci build check.

**Comment by wolfboys** [comment]
> @wolfboys Currently , I want to add java 8 and 11 as ci build check.

okay.
