### ISSUE TITLE
[Feature] Improve the  search_owner when query the app list

### ISSUE THREAD

**Issue by 1996fanrui** [apache/streampark#1827]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

After the team is supported, search_owner should only show users of the current team.

![image](https://user-images.githubusercontent.com/38427477/195364209-061e30db-8341-40dd-bc7e-8a45e851be8c.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @wolfboys , I have a question. 

There are some applications belong to admin. Should we show all app owner for current team?

![4FE099D9-4168-4B71-AF53-BFC098FA0BEA](https://user-images.githubusercontent.com/38427477/195609093-cca06944-9231-412b-91c4-9cfb98a7b559.png)

**Comment by wolfboys** [comment]
> Hi @wolfboys , I have a question.
> 
> There are some applications belong to admin. Should we show all app owner for current team?
> 
> ![4FE099D9-4168-4B71-AF53-BFC098FA0BEA](https://user-images.githubusercontent.com/38427477/195609093-cca06944-9231-412b-91c4-9cfb98a7b559.png)

This job is a special case, not belonging to any owner, otherwise other team members can not see it.
