### ISSUE TITLE
[Bug] Docker compose tag is lastest, but docker hub tag is dev.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#1897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

`TAG` defined in file `/opt/incubator-streampark/deploy/docker/.env` is `latest` , but in docker hub is `dev`.
<img width="992" alt="企业微信截图_16666638193790" src="https://user-images.githubusercontent.com/13617900/197665591-0e24aec4-4a65-4381-b70f-ade71588b85f.png">

### StreamPark Version

lastest

### Java Version

1.8

### Flink Version

1.14

### Scala Version of Flink

2.12

### Error Exception

```log
[root@GreenCloud docker]# docker-compose up -d
Creating network "docker_streampark" with driver "bridge"
Creating volume "docker_flink" with default driver
Pulling streampark-server (apache/streampark:latest)...
ERROR: manifest for apache/streampark:latest not found: manifest unknown: manifest unknown
```

### Screenshots

<img width="423" alt="企业微信截图_1666663896554" src="https://user-images.githubusercontent.com/13617900/197665719-95d04466-7c70-455d-b265-3b20736887e4.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
@wolfboys Pls assigne to me , I'm willing to fix this issue.

**Comment by wolfboys** [comment]
> @wolfboys Pls assigne to me , I'm willing to fix this issue.

done.
