### ISSUE TITLE
[Bug] Flink cluster status cannot be updated

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#1906]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I open a yarn session cluster, if the container fails in yarn for some reason, StreamPark cannot perceive the change of the yarn session.

### StreamPark Version

1.2.4-SNAPSHOT

### Java Version

1.8

### Flink Version

1.14.4

### Scala Version of Flink

2.12

### Error Exception

```log
no
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xujiangfeng001** [comment]
@wolfboys Hello, I think it is necessary to monitor the Flink cluster. I don't know what your opinion is?

**Comment by RocMarshal** [comment]
@xujiangfeng001 Thanks for the driving this. 
good proposal👍, and I'd like to make it pluggable, because the pluggable mechanism give the space to users for selection.
Please let's know what's your opinions. Thanks  a lot.
CC @wolfboys

**Comment by RocMarshal** [comment]
hello, @xujiangfeng001 Would you like to support the feature?  thx~

**Comment by xujiangfeng001** [comment]
> @xujiangfeng001 Thanks for the driving this. good proposal👍, and I'd like to make it pluggable, because the pluggable mechanism give the space to users for selection. Please let's know what's your opinions. Thanks a lot. CC @wolfboys

Sorry, I don't quite understand what needs to be done. Can you elaborate?

**Comment by xujiangfeng001** [comment]
> hello, @xujiangfeng001 Would you like to support the feature? thx~

Hello, this function is in my plan. I will improve this function as soon as possible.

**Comment by RocMarshal** [comment]
The issue migrated into https://github.com/apache/incubator-streampark/issues/2425
