### ISSUE TITLE
[Bug] docker-compose.yaml Startup problems

### ISSUE THREAD

**Issue by senlizishi** [apache/streampark#1918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Execute the Docker Compose build command
`docker-compose up -d`
The container is always in the restraining state
![image](https://user-images.githubusercontent.com/24784791/198459521-02b4d2db-0b70-479e-9585-76b159328b1a.png)
View the container log and find that there is a permission problem
![image](https://user-images.githubusercontent.com/24784791/198459308-aec6501e-2ccd-40b3-b0da-b6513212cd75.png)

My current solution is to use Docker Compose Add privileged=true to the yaml file to increase permissions
![0d2d81696f134c6b7275cfa70a7c13f](https://user-images.githubusercontent.com/24784791/198464281-a2ceee0e-4025-4028-b831-faa729ec37f5.jpg)

### StreamPark Version

branch dev

### Java Version

openjdk 11

### Flink Version

1.14.5

### Scala Version of Flink

2.12

### Error Exception

```log
Cannot find bin/streampark.sh
The file is absent or does not have execute permission
This file is needed to run this program
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, looks good, looking forward to you fix it

**Comment by senlizishi** [comment]
> Thanks for your feedback, looks good, looking forward to you fix it

done.
