### ISSUE TITLE
[Bug] After run build.sh file husky.sh will be modified.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#1935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

 After run build.sh file husky.sh will be modified.

### StreamPark Version

1.2.4

### Flink Version

1.15

### Scala Version of Flink

2.11

### Error Exception

```log
After run build.sh file husky.sh will be modified.
```

### Screenshots

![0E79_VRWB{ })V~(`LN{%PH](https://user-images.githubusercontent.com/13617900/199054168-9a41a52d-e99a-4e8d-b2c8-096f6d2c791d.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
