### ISSUE TITLE
[Bug] Problems found during new front-end testing

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#1939]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Check box selected after resolution
- [x] 01.When you select the password saved by the browser during login, a white box will be displayed
- [x] 02.When the server returns an exception during login, the exception pop-up displayed on the front end is incomplete
- [x] 03.When the browser debug is opened during login, the login button is masked, which is unfriendly when clicked
- [x] 04.Applcaiton's tag, owner, type and other searches do not take effect
- [x] 05.When adding variables, the input box of variable code is changed to textarea
- [x] 06.When adding a variable, if you enter characters in the variable code input box consistently, you will be prompted "please enter variable code" when you reach a certain length. This should not be prompted
- [x] 07.When viewing variable details, the attribute name is issued as a newline
- [x] 08.The positions of the search button and reset button need to be interchanged
- [x] 09.Read only permission of variables cannot be added when editing roles
- [x] 10.When switching teams, the page is refreshed and jumps to other pages
- [x] 11.When creating an application, when I click the Validate SQL button, the validation result is not displayed
- [x] 12.When creating an application, when the sql error occurs, it does not respond when the submit button is clicked
- [x] 13.When creating a project, the branch selection box disappears when trying to search for a branch
- [x] 14.When creating a project, if the git url, user, password, and branch are all correct, it prompts that the git verification fails, but in fact the interface returns the verification success
- [x] 15.Flink SQL history version does not display records, but the interface returns normally
- [x] 16.When editing the application, the values of Project and Module are not displayed
- [x] 17.In the variable management module, the user does not have the permission of Depend apps, but can see the button and prompt 404 after clicking the button
- [x] 18.Under the application details page, switch to Option Logs, and then click the link under the application Id column, instead of being challenged to the yarn page, it jumps to the ip deployed by streampark
- [x] 19.When creating an application, the window corresponding to args is too small. It is recommended to increase the size and add a full-screen button.
- [x] 20.Click on the application details page and switch to Option Logs. The Start Status, Option Time, and Operation columns are too wide, resulting in incomplete display of the Application Id JobManager URL column.
- [x] 21.Under the Firefox browser, when the full screen button is clicked in the sql edit box, there is no real full screen, only three quarters of the screen, no problem under Google browser
- [x] 22.When adding a user, the length limit of the username is too short
- [x] 23.When a role only gives the project view permission, the user with this role can see the project delete button, and when the delete button is clicked, it directly jumps to the login page
- [x] 24.When a role only gives application view permissions, users with this role can see the application's launch button
- [x] 25.Don't show see build log button when you don't have project build permission

### StreamPark Version

1.2.4

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
refer to what happened
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
These seem to have been fixed in the latest version of the code

1.When you select the password saved by the browser during login, a white box will be displayed

4.Applcaiton's tag, owner, type and other searches do not take effect

6.When adding a variable, if you enter characters in the variable code input box consistently, you will be prompted "please enter variable code" when you reach a certain length. This should not be prompted

10. When switching teams, the page is refreshed and jumps to other pages
