### ISSUE TITLE
[Add User] Wrong style of drop-down box options

### ISSUE THREAD

**Issue by green241** [apache/streampark#1947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

normal:
![image](https://user-images.githubusercontent.com/14801784/199430497-5e42d22c-1964-40da-ba41-18552d2dc718.png)

however, After scrolling up the mouse， it shows as following:
![image](https://user-images.githubusercontent.com/14801784/199430789-c3b19548-0ef2-4680-9057-84f96f6c62da.png)

surprise, After scrolling down the mouse, it shows as following:
![image](https://user-images.githubusercontent.com/14801784/199431002-49a5a83c-0dab-4f4f-ad5c-9f412a4ee34f.png)

### StreamPark Version

dev branch.

### Java Version

![image](https://user-images.githubusercontent.com/14801784/199431253-23d404bb-dfd3-40c2-96f8-6168c8bc1ef4.png)

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
Not involved, referring "What happened" module.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Thank you for your feedback, this is due to the dropdown box rendered into the body of the page, causing a positioning error, we will fix him in the new version. Of course, you can also change it yourself by doing the following

streampark-console/streampark-console-webapp/src/views/system/user/UserAdd.vue

Add a property to the select component of the User Type form item

	:getPopupContainer="(triggerNode) => triggerNode.parentNode"

The sample

	<a-form-item
        label="User Type"
        v-bind="formItemLayout">
        <a-select
          mode="single"
          :getPopupContainer="(triggerNode) => triggerNode.parentNode"
          :allow-clear="false"
          style="width: 100%"
          v-decorator="['userType',{rules: [{ required: true, message: 'please select user type' }]}]">
          <a-select-option
            v-for="userType in userTypeData"
            :key="userType">
            {{ userType }}
          </a-select-option>
        </a-select>
      </a-form-item>

**Comment by green241** [comment]
Thanks for your deatil reply, I will have a try.



---- Replied Message ----
| From | Sizhu ***@***.***> |
| Date | 11/02/2022 16:28 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [apache/incubator-streampark] [Add User] Wrong style of drop-down box options (Issue #1947) |

Thank you for your feedback, this is due to the dropdown box rendered into the body of the page, causing a positioning error, we will fix him in the new version. Of course, you can also change it yourself by doing the following

streampark-console/streampark-console-webapp/src/views/system/user/UserAdd.vue

Add a property to the select component of the User Type form item

:getPopupContainer="(triggerNode) => triggerNode.parentNode"


The sample

<a-form-item
    label="User Type"
    v-bind="formItemLayout">
    <a-select
      mode="single"
      :getPopupContainer="(triggerNode) => triggerNode.parentNode"
      :allow-clear="false"
      style="width: 100%"
      v-decorator="['userType',{rules: [{ required: true, message: 'please select user type' }]}]">
      <a-select-option
        v-for="userType in userTypeData"
        :key="userType">
        {{ userType }}
      </a-select-option>
    </a-select>
  </a-form-item>
