### ISSUE TITLE
[Bug]When Add Variable , Error check pop-up box

### ISSUE THREAD

**Issue by green241** [apache/streampark#1983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After pulling the latest code and testing the "Add Variable" module, I found that the following pop-up box appears when the variable value input box gets focus.
![image](https://user-images.githubusercontent.com/14801784/200465121-04e773c8-541a-430b-8d57-7a3cd15e7e18.png)

### StreamPark Version

dev(1.2.4), old UI.
![image](https://user-images.githubusercontent.com/14801784/200465200-da2604f2-c9e3-4560-a21a-e9d17ad8d517.png)

### Java Version

1.8.0_333

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
Please refer "What happened" module.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Thank you for your feedback, we are considering to abandon the webapp front-end UI, so some subsequent changes are not synchronized in this directory. If you find a problem in the new ui directory, please give us your feedback again.We apologize for any inconvenience this may cause you.

**Comment by green241** [comment]
oka, I see. Thanks for sizhu's detail reply.
