### ISSUE TITLE
[Bug]User details interface gender is not properly displayed.

### ISSUE THREAD

**Issue by green241** [apache/streampark#1998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

the gender of modify page ,
![image](https://user-images.githubusercontent.com/14801784/200988696-be635f87-961b-405d-a007-779c7a2acec8.png)
however, the detail page as following,
![image](https://user-images.githubusercontent.com/14801784/200988908-b980d72d-cbdf-4532-b93e-07c2c275e9a8.png)

### StreamPark Version

dev

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
refer the "What happened"
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Thank you for your feedback, we will fix the problem immediately
