### ISSUE TITLE
[Improve] Enhance the tests of 'streampark-console' module.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2014]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Main Objective in the Improvement：
- Supplement unit test cases of streampark console.

#### Present situation: 
At present, there are few test cases for streampark console based on JUnit5(Jupiter).
To make a long story short for no test cases:
  - As a part of the development specification, test cases are indispensable. 
  - It is not conducive to the long-term evolution of the project. 
  - When changing the current module, it is difficult to find potential problems.

### Choose Test Suites(If the improvement was accepted)

JUnit5 & Mockito [& AssertJ]

#### Why JUNIT5?

1. Released in 2017, JUnit 5 has become more and more popular among Java projects. With quite a lot of new features such as extension model, advanced parameterized test, and better support of lambda functions, JUnit 5 presents more convenience and flexibility to developers.
2. Support integration with many frameworks, such as Spring, Testcontainers, etc
[JUnit5 Official website](https://junit.org/junit5/)

#### About Mock

Why Mockito instead of Powermock?

- Mockito supports Junit5
- Powermock works based on Junit4, https://github.com/powermock/powermock
- Mockito's community is more active than Powermock. https://github.com/mockito/mockito

#### Assertion API
- JUnit5 Assertion API: is the built-in API of JUnit5. If We use 'JUnit5 Assertions' to work, we can reduce some learning costs.
- [AssertJ](https://joel-costigliola.github.io/assertj/index.html): AssertJ can perform the same functions as JUnit5 Assertion, and has many APIs based on stream coding, which makes it more elegant.

### Integration test problems and other module test problems.
Maybe we also need to consider the test suites selection based on the sections.

### E2E test 
There is an [issue](https://github.com/apache/incubator-streampark/issues/1381) described the E2E test plan  

### Any suggestion and idea is appreciated!
- About other test suites, TestNG...
- Or anything important for the improvment.

### Usage Scenario

N.A

### E2E test 
There is an [issue](https://github.com/apache/incubator-streampark/issues/1381) described the E2E test plan  

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
CC @wolfboys @1996fanrui @MonsterChenzhuo

**Comment by wolfboys** [comment]
Very good proposal 👍👍,  welcome to contributions

**Comment by MonsterChenzhuo** [comment]
+1 Very good proposal

**Comment by RocMarshal** [comment]
I encountered two case have to solve to support the integration test enhancement.

1. Error is reported when initializing app.home resources in the run `EnvInitializer#storageInitialize`.
The main error is that the file does not exist and the target directory is empty when initializing the copy of `lib, plugins, client and other directories`.

There are two solutions from me:

1). copy the mock manually folders and files in the `resources` directory to the path set by `app.home` before the EnvInitializer class executes the` run` method

2).  set a `System properties` to mark whether `EnvInitializer#run`  really need to  execute the logic of the method body

Other try:  to use `mockito` to spy the `EnvInitializer#run`, but the idea  is not feasible due to the feature of ApplicationRunner.

In the long item, if automated testing is carried out in as wide a range as possible, the files in `app.home` must not be implemented with mocks, but need a real `app.home` and its' resource, which is same as the production Env.

In the short term, I prefer to mock, and support the rapid improvement of the test part.

2. When integrating `test-containers`, it is intended to reuse the mysql sql file (but the current mysql sql file is not under `resources`, so it cannot be reused).

Can the `sql scripts file` of `mysql&postgresql` be placed in the `resources folder`,  then we could change the  descriptions content of  `assembly` to reach the same packaging-effect with original implementation ? Or we can add a new sql-file for test-cases, which could cause some redundant sql lines.

Looking forward to your suggestions. 
CC @wolfboys @MonsterChenzhuo @1996fanrui

**Comment by RocMarshal** [comment]
> 1. Error is reported when initializing app.home resources in the run `EnvInitializer#storageInitialize`.
>    The main error is that the file does not exist and the target directory is empty when initializing the copy of `lib, plugins, client and other directories`.

We will use preview policy 2 , do some public init logic in `SpringTestBase` , and make some test class to inherit SpringTestBase.

**Comment by RocMarshal** [comment]
> 2\. When integrating `test-containers`, it is intended to reuse the mysql sql file (but the current mysql sql file is not under `resources`, so it cannot be reused).

We'd prefer use embed h2 as the DB level in test. so the problem was dicarded.

**Comment by wolfboys** [comment]
> > 2. When integrating `test-containers`, it is intended to reuse the mysql sql file (but the current mysql sql file is not under `resources`, so it cannot be reused).
> 
> We'd prefer use embed h2 as the DB level in test. so the problem was dicarded.

yes, h2 DB is better for testing.
