### ISSUE TITLE
[Bug] The mapping task cannot be cancel

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#2029]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

First, I re-associated a lost flink task to the streampark platform via the maping function, then when I clicked cancel, I found that the task was not canceled and the status of streampark changed from running to failed

After mapping, the job status became Failed when the job was canceled (the actual job was still running), and the status changed to canceled only after I deleted the deployment in the k8s management console
![图片](https://user-images.githubusercontent.com/60029759/202599012-261f4df7-16ef-4681-a5fd-2e86869ce422.png)
![图片](https://user-images.githubusercontent.com/60029759/202599025-64f7b2c1-0eec-47d5-b19a-1a012400b6de.png)

### StreamPark Version

2.0.0

### Flink Version

1.4.5

### Scala Version of Flink

2.11

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
@MonsterChenzhuo  thanks a lot for your feedback,  I will take a look asap.

**Comment by Su1024** [comment]
@MonsterChenzhuo  Is the missing flink task generated by streampark or a flink task submitted manually？
