### ISSUE TITLE
[Bug] When the user logs in, it prompts that there is no permission

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#2030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When creating a user, the user's team_id in the t_user table is filled with the current team, but other teams are selected when assigning roles. At this time, the user will be prompted to log in without permission. 

The specific operation steps are as follows:
1. Create an account `test` in `team A`
2. Switch to `team B` and add a developer role to the `test` account
3. Use the `test` account to log in, at this time it prompts no permission

### StreamPark Version

2.0.0

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
Prompt no permission
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
@macksonmu , thanks a lot for your feedback, it's really a bug. I will take a look asap.
