### ISSUE TITLE
[Bug] When the application is in the running state, it is not a gesture when the mouse moves to the application name

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#2039]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When the application is in the running state, it is not a gesture when the mouse moves to the application name.

### StreamPark Version

2.0.0

### Java Version

jdk8

### Flink Version

flink1.14

### Scala Version of Flink

2.12

### Error Exception

```log
When the application is in the running state, it is not a gesture when the mouse moves to the application name
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Hi @macksonmu , This problem seems to have been solved before, if you have time to retest whether there are still problems,Thank you！！！
