### ISSUE TITLE
[Bug] An exception occurred in the wechat alarm test

### ISSUE THREAD

**Issue by Trgree** [apache/streampark#2043]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Prompt "internal server error: No bean named 'WE_COMAlertNotifyServiceImpl' available" when tesing wechat alarm.

### StreamPark Version

2.0.0

### Java Version

1.8

### Flink Version

1.12.0

### Scala Version of Flink

2.11

### Error Exception

```log
internal server error: No bean named 'WE_COMAlertNotifyServiceImpl' available
```

### Screenshots

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1509500/202436406-c32ceb5b-57e8-4d43-8e7e-c87471e45c8d.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Fixed in #2046
