### ISSUE TITLE
[Bug] Login error

### ISSUE THREAD

**Issue by jefftlin** [apache/streampark#2049]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![企业微信截图_1668698358571](https://user-images.githubusercontent.com/57786627/202485908-ceae06a1-ec4e-46d9-8bdc-44c0651ef3f8.png)

### StreamPark Version

1.2.3

### Java Version

1.8

### Flink Version

null

### Scala Version of Flink

2.11.2

### Error Exception

```log
Login error with admin / streampark
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
1.2.3 default password: streamx
