### ISSUE TITLE
[Bug] Ldap login successful, routing failed

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#2051]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/60029759/202600434-be57307b-d249-464a-a66e-1273b9345360.png">

<img width="1431" alt="图片" src="https://user-images.githubusercontent.com/60029759/202599520-e44b2058-8712-4a27-af7f-3fd17051178c.png">

{"data":{"user":{"userId":"100002","username":"chenzy15","password":"********","email":null,"userType":"USER","status":"1","createTime":"2022-11-17 16:13:13","modifyTime":"2022-11-17 23:12:12","lastLoginTime":"2022-11-17 23:12:12","sex":"1","description":null,"avatar":"default.jpg","sortField":null,"sortOrder":null,"createTimeFrom":null,"createTimeTo":null,"id":"xow0boU2OOSRY4Z2jefL","salt":"********","nickName":"chenzy15","lastTeamId":"100000"},"permissions":["app:create","app:flameGraph","savepoint:delete","app:launch","app:start","notebook:submit","app:view","app:detail","project:build","app:update","backup:delete","app:cancel","conf:delete","app:clean","project:create","backup:rollback","project:view"],"token":"b702a408028cbf3ff5d8049ae73d1c3fb28c5fd9c4d2526984fc16c56a3b6ec11bb1eb4193dd95a4bda47eac2a36a7c8b74a63a3597aa86d94ce18cf0783d88dee5edb5208b0848f1c336fc59570842b3a314116147127ad57632f86095afaff98c90a61130a6aa3e3ddcd5072695a8b9dccdcfa1765e9489974c134cab5c3ca8afd706b0cc7ce89fee79025fc5c028caa75168f01c288dfc0c52566e4d277a5","expire":"2022-11-18 23:12:26"}}

{"code":"200","data":[{"id":"100000","teamName":"default","description":null,"createTime":"2022-11-17 15:22:58","modifyTime":"2022-11-17 15:22:58","sortField":null,"sortOrder":null,"createTimeFrom":null,"createTimeTo":null}],"status":"success"}

### StreamPark Version

2.0.0

### Flink Version

1.4.5

### Scala Version of Flink

2.12

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Hi @MonsterChenzhuo  Thank you for your feedback，I observed that after you logged in with ldap, the /menu/router interface gave an exception alarm. I suggest you look at the back-end log of the /menu/router interface. If there is no log on the back-end, you can see whether the currently logged in user data is abnormal.   I hope it can help you solve this problem
