### ISSUE TITLE
[Bug] Set the configuration `kubernetes.container.image.pull-policy: Always` to the platform default

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#2054]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Set the configuration `kubernetes.container.image.pull-policy: Always` to the platform default.
There are too many new students that spend a lot of time because of this parameter

### StreamPark Version

2.0.0

### Flink Version

1.14.5

### Scala Version of Flink

2.12

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good idea
