### ISSUE TITLE
[improve] One optimization point

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#2118]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<img width="1047" alt="图片" src="https://user-images.githubusercontent.com/60029759/204980374-627f4828-804e-4c12-a0da-b9ee361edcbb.png">
newApp.setArgs(StringUtils.isNotEmpty(appParam.getArgs()) ? appParam.getArgs() : oldApp.getArgs());

This modification may be better

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
