### ISSUE TITLE
[Bug] cannot login web console

### ISSUE THREAD

**Issue by pengyuan** [apache/streampark#2122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/2572263/205240162-868315b5-2121-4003-ba8d-817349f111b3.png">

### StreamPark Version

1.2.3

### Java Version

1.8

### Flink Version

1.14.5

### Scala Version of Flink

2.12

### Error Exception

```log
如图
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by green241** [comment]
Maybe you can have a try as following:
1. check the browser console log, if error log message appear?
2. clear the table  `t_user` && reinsert the data of this table which script name is `mysql-data.sql`.
