### ISSUE TITLE
[Bug] No delete button after mirror build failure

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#2138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

<img width="1154" alt="图片" src="https://user-images.githubusercontent.com/60029759/206189958-ec427ff5-d389-4d51-8d7f-de93cdc5682f.png">
<img width="506" alt="图片" src="https://user-images.githubusercontent.com/60029759/206189976-76a29f26-47b0-4718-9cd9-f565f92389b4.png">
<img width="794" alt="图片" src="https://user-images.githubusercontent.com/60029759/206189988-cde7d8d7-b3c3-435c-ba04-04afccc55e8b.png">
As of now, this problem belongs to an accidental occurrence, but after it appeared, I found that the image was never built successfully and I could not delete this task. At the moment I can only re-execute the build process by creating a new task, but the task in question will only remain on the page forever.

### StreamPark Version

2.0.0

### Flink Version

1.14.5

### Scala Version of Flink

2.11

### Error Exception

```log
null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
cc @MonsterChenzhuo Does this issue still exist in the latest code? Please test it

**Comment by MonsterChenzhuo** [comment]
@wolfboys  I haven't encountered it for the time being.

**Comment by MonsterChenzhuo** [comment]
The code is up to date, and now the mirroring is built successfully.There has been no failure to build the image for a long time.

**Comment by wolfboys** [comment]
fixed in new version
