### ISSUE TITLE
[Bug]  Dynamic Properties Error

### ISSUE THREAD

**Issue by daixiaoyu** [apache/streampark#2160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When we use multiple dynamic properties, we cannot pass the correct parameter to k8s when we submit, but we can pass only one parameter normally

### StreamPark Version

2.0

### Java Version

1.8

### Flink Version

1.16

### Scala Version of Flink

2.12

### Error Exception

```log
![image](https://user-images.githubusercontent.com/10663476/207799425-24ddd1fc-f388-454b-b198-5e3213963bc6.png)
```

### Screenshots

![image](https://user-images.githubusercontent.com/10663476/207799425-24ddd1fc-f388-454b-b198-5e3213963bc6.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
