### ISSUE TITLE
[Bug] The default team cannot be deleted

### ISSUE THREAD

**Issue by daixiaoyu** [apache/streampark#2164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The default team cannot be deleted

### StreamPark Version

2.0.0

### Java Version

1.8

### Flink Version

1.16.0

### Scala Version of Flink

2.12

### Error Exception

```log
The default team cannot be deleted
```

### Screenshots

<img width="816" alt="image" src="https://user-images.githubusercontent.com/10663476/207880383-7c9d0ba7-7416-4b93-a244-53ae4a1a0150.png">
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/10663476/207880498-1d2055f9-2181-45ec-bbf8-1852d35ced40.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @daixiaoyu , as the alert message: `Please delete the projects`, you can check whether there is still project.

Your picture is application page.
