### ISSUE TITLE
[Bug] Duration Display Error

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#2167]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The yarn session task in Streampark failed to run. The duration displays an error. Steps:

1. The Yarn session task is normal when it is started for the first time
2. During the second startup, the yarn session mode task failed

### StreamPark Version

2.0.0

### Java Version

1.8

### Flink Version

1.15.0

### Scala Version of Flink

2.12

### Error Exception

```log
nothing
```

### Screenshots

![00180374d347d225ffdc35009ede9c6](https://user-images.githubusercontent.com/104614523/208050717-1701a24b-f51b-4afe-b71c-c3f36b5d28d6.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
please test in latest version
