### ISSUE TITLE
[Bug] when package the project, it appears "Cannot resolve org.apache.bahir:flink-connector-redis_2.12:1.0 " problem

### ISSUE THREAD

**Issue by green241** [apache/streampark#2180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when package the project, it appears "Cannot resolve org.apache.bahir:flink-connector-redis_2.12:1.0 " problem.
![image](https://user-images.githubusercontent.com/14801784/208367173-27384c16-57aa-4aff-8fc6-5b89cf7e2bbc.png)

probably case:
when choose the scala version 2.12, flink-connector-redis only support the version of 1.1.0 , click [here](https://mvnrepository.com/artifact/org.apache.bahir/flink-connector-redis).

### StreamPark Version

2.0.0

### Java Version

1.8

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
refer the 'What happened' module.
```

### Screenshots

![image](https://user-images.githubusercontent.com/14801784/208367173-27384c16-57aa-4aff-8fc6-5b89cf7e2bbc.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
build project, just run: `sh $root/build.sh`
