### ISSUE TITLE
[Feature] Maintain external link under Setting module

### ISSUE THREAD

**Issue by saLeox** [apache/streampark#2191]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Maintain external link under Setting module, including ADD, UPDATE, LIST, DELETE operation.

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/23732067/210077807-7abd1bc9-773e-4c24-9411-ffde4ea401cc.png">

### Usage Scenario

When user intend to embed some external link related to Flink.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ziqiang-wang** [comment]
For metrics reporting and statistical monitoring, I recommend that you refer to prometheus as provided by the Flink website for metrics reporting and then grafana monitoring without the platform having to implement this feature separately.

**Comment by saLeox** [comment]
> For metrics reporting and statistical monitoring, I recommend that you refer to prometheus as provided by the Flink website for metrics reporting and then grafana monitoring without the platform having to implement this feature separately.

Hi @ziqiang-wang, we already have prometheus and grafana stack to monitor each Flink job, and user still need to jump to grafana and retrieve the Flink job accordingly.
Ideally, there should be a badge in Flink application detail page, to display the metrics link, which user able to know everything about Flink within this platform.
Further more, I also discuss with other member from community. As a result, we intend to have a setting for badge, so that user can customize the badge shown in detail page, including metrics page, logging page (es & kibana), and etc.

**Comment by ziqiang-wang** [comment]
It's a nice feature.
See if the community adopts and implements this new feature.

**Comment by ziqiang-wang** [comment]
> > For metrics reporting and statistical monitoring, I recommend that you refer to prometheus as provided by the Flink website for metrics reporting and then grafana monitoring without the platform having to implement this feature separately.
> 
> Hi @ziqiang-wang, we already have prometheus and grafana stack to monitor each Flink job, and user still need to jump to grafana and retrieve the Flink job accordingly. Ideally, there should be a badge in Flink application detail page, to display the metrics link, which user able to know everything about Flink within this platform. Further more, I also discuss with other member from community. As a result, we intend to have a setting for badge, so that user can customize the badge shown in detail page, including metrics page, logging page (es & kibana), and etc.

It's a nice feature.
See if the community adopts and implements this new feature.

**Comment by RocMarshal** [comment]
@saLeox Hi.  Would you help to add a page in the site as the usage guide for users?  Thx you
