### ISSUE TITLE
[Bug] have error in hadoop 3.0 compile

### ISSUE THREAD

**Issue by lpn666** [apache/streampark#2194]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When compile in hadoop 3 , I got error after I  startup the program.

### StreamPark Version

dev

### Java Version

jdk 1.8

### Flink Version

1.14

### Scala Version of Flink

2.11

### Error Exception

```log
nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
```
![image](https://user-images.githubusercontent.com/26716574/209753027-67abbcfc-d463-44c4-95b0-5e9c6ef58998.png)

### Screenshots

here  is pom file 
![image](https://user-images.githubusercontent.com/26716574/209742697-de6cbd9d-d71c-4056-bc6a-c8621f65d515.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lpn666** [comment]
@wolfboys why close the issue?  Did I do something wrong?

**Comment by wolfboys** [comment]
> @wolfboys why close the issue? Did I do something wrong?

The default Hadoop version has been tested and supports Hadoop 2/3 at the same time. If you modify the Hadoop version yourself, it may cause version incompatibility. This part of the working community does not undertake related questions and answers.

**Comment by lpn666** [comment]
okay, thanks anyway.
