### ISSUE TITLE
[Feature] flinksql应用可以从本地文件或者git中拉取填充

### ISSUE THREAD

**Issue by denglhh** [apache/streampark#2203]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

通过streampark创建flinksql任务时，flinksql脚本只能手工编写或复制黏贴进去，不能从本地文件中导入或者git中拉取
希望有相关功能，这样可以很好的基于git等多团队开发以及旧项目的迁移部署到streampark中

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
use English
