### ISSUE TITLE
配置flink cluster时，flink versioin选不到值

### ISSUE THREAD

**Issue by midoll3** [apache/streampark#2206]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/31194732/209924215-736ece0c-b434-441a-92e2-264fac9bbabc.png)

### StreamPark Version

version：2.0.0

### Flink Version

还没有配置

### Scala Version of Flink

-

### Error Exception

```log
-
```

### Screenshots

![image](https://user-images.githubusercontent.com/31194732/209924427-bdedd162-5543-426c-b63a-11f2414f2fc3.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
please use English, Please refer to the relevant docs to learn how to use
