### ISSUE TITLE
[Feature] When deleting savepoint records, delete hdfs files at the same time.

### ISSUE THREAD

**Issue by ziqiang-wang** [apache/streampark#2210]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When savepoint records are deleted, the corresponding hdfs files are not deleted at the same time.

I want to synchronize and delete files from the hdfs to clean up unnecessary files.

![image](https://user-images.githubusercontent.com/107013241/209951766-11dd93f1-d46a-43e2-9800-d242051fd147.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Hi, @wolfboys May I get the ticket to support the feature? Thx.
CC @ziqiang-wang

**Comment by wolfboys** [comment]
> Hi, @wolfboys May I get the ticket to support the feature? Thx. CC @ziqiang-wang

That's great. assigned this issue to you

**Comment by ziqiang-wang** [comment]
> Hi, @wolfboys May I get the ticket to support the feature? Thx. CC @ziqiang-wang

@RocMarshal 
Thank you for your hard work.

**Comment by RocMarshal** [comment]
Hi, @wolfboys @ziqiang-wang .
I checked the deletion logic of checkpoints located on HDFS. And I found it worked.
I delete the chk-4 by operating savepoint interface on the  platform.
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/64569824/214830300-36ade5cb-7193-4300-9738-36e9df074447.png">


The corresponding code segement as follows: 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/64569824/214830520-3801bfb8-ebf6-4666-95e5-faa6cf6b5a23.png">

Could you help to double-check for the feature ?
CC @wolfboys @ziqiang-wang . Thanks.

**Comment by ziqiang-wang** [comment]
> Hi, @wolfboys @ziqiang-wang . I checked the deletion logic of checkpoints located on HDFS. And I found it worked. I delete the chk-4 by operating savepoint interface on the platform. <img alt="image" width="1136" src="https://user-images.githubusercontent.com/64569824/214830300-36ade5cb-7193-4300-9738-36e9df074447.png">
> 
> The corresponding code segement as follows:
> 
> <img alt="image" width="1101" src="https://user-images.githubusercontent.com/64569824/214830520-3801bfb8-ebf6-4666-95e5-faa6cf6b5a23.png">
> 
> Could you help to double-check for the feature ? CC @wolfboys @ziqiang-wang . Thanks.

It's work OK, when I was testing before, I forgot to refresh the page for viewing HDFS.
@RocMarshal
