### ISSUE TITLE
[Feature] Team add number, can direct select

### ISSUE THREAD

**Issue by ziqiang-wang** [apache/streampark#2214]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When I add a Member in the Member Management interface, I can easily select a user instead of asking me to enter a user name.

### Related issues

![image](https://user-images.githubusercontent.com/107013241/210061715-7d4a8530-c676-4fce-9157-c7e69e7bde87.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 1996fanrui** [comment]
Hi @RocMarshal , do you have time to do this feature before Chinese New Year?

**Comment by RocMarshal** [comment]
@1996fanrui 
Of course. My pleasure. thanks so much for the ping.
