### ISSUE TITLE
[Feature] use apache sshd to replace jsch

### ISSUE THREAD

**Issue by datasophon** [apache/streampark#2247]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In GitUtils class , replace jsch with apache sshd to solve the link failure problem

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Looking forward to your contribution

**Comment by wolfboys** [comment]
supported
