### ISSUE TITLE
[Feature] Supports multi Flink version of integration with Flink SQL gateway

### ISSUE THREAD

**Issue by SteNicholas** [apache/streampark#2276]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

StreamPark is supporting to integrate with Flink SQL gateway, which should support multi Flink version at least Flink 1.16.

### Usage Scenario

The integration with Flink SQL gateway.

### Related issues

#2274

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jiabao-Sun** [comment]
Can I take this task?

**Comment by SteNicholas** [comment]
@wolfboys, could you please assign this ticket to @Jiabao-Sun?

**Comment by wolfboys** [comment]
> @wolfboys, could you please assign this ticket to @Jiabao-Sun?

done.

**Comment by wolfboys** [comment]
Since there has been no progress for too long, feel free to propose again.
