### ISSUE TITLE
通过streampark平台提交的flink job 无法做checkpoint ，checkpoint path 是hdfs地址，请问该如何进行配置

### ISSUE THREAD

**Issue by An1990** [apache/streampark#2296]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Caused by: java.util.concurrent.CompletionException: org.apache.flink.util.FlinkRuntimeException: Failed to create checkpoint storage at checkpoint coordinator side.
Caused by: org.apache.flink.core.fs.UnsupportedFileSystemSchemeException: Cannot support file system for 'hdfs' via Hadoop, because Hadoop is not in the classpath, or some classes are missing from the classpath.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
use english

**Comment by An1990** [comment]
hadoop  classpath已经配置

配置文件如下：
export HADOOP_HOME=/opt/cloudera/parcels/CDH/lib/hadoop
export FLINK_HOME=/data/flink
export HADOOP_CLASSPATH=`hadoop classpath`

# streamx
export STREAMX_HOME=/data/streamx/streamx
export PATH=/data/streamx/streamx/bin:$PATH:/data/flink/bin

export HADOOP_CONF_DIR=/etc/hadoop/conf
#export HADOOP_COMMON_HOME=/opt/cloudera/parcels/CDH/lib/hadoop
export HIVE_HOME=$HADOOP_HOME/../hive
export HBASE_HOME=$HADOOP_HOME/../hbase
export HADOOP_HDFS_HOME=$HADOOP_HOME/../hadoop-hdfs
export HADOOP_MAPRED_HOME=$HADOOP_HOME/../hadoop-mapreduce
export HADOOP_YARN_HOME=$HADOOP_HOME/../hadoop-yarn

**Comment by An1990** [comment]
傻逼 你不是中国人？

**Comment by wolfboys** [comment]
> 傻逼 你不是中国人？

Your words and actions are a serious violation of open source culture, abusive and personal attacks, please unfollow  StreamPark WeChat Official Account , quit the streampark user group, and never use StreamPark.

---

你的言行严重违背了开源文化,辱骂和人身攻击, 请自动取关 StreamPark公众号, 自动退出streampark用户群, 永远不要使用StreamPark.
