### ISSUE TITLE
[Feature] Support yarn label quick-set for yarn-application execution mode.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2299]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

# Background:
  Now, `Streampark` only support yarn queue quick-config for yarn-application execution mode in edit/create application page.
  This is a common management method that  users tag the yarn nodes with corresponding labels to sort the cluster resource, such as rich-CPU, rich-IO resource, to schedule the applications appropriately.
  However,  users want to specified the yarn label, users need set it by `yarn.application.node-label` key in `Dynamic Properties` input-text, which is not friendly enough for using.

# Intention:
  Improve the convenience of high-frequency key `yarn.application.node-label`

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/64569824/216805099-eb65b2c8-8201-44ea-9db8-05264b2088fa.png">

# How
  
- Reuse the `Yarn queue` input, and make the input text ruled by `({queue-name})[@({label-1}[, {label-2}]...)]`format.  
    - Examples:  
      - `queue-q1`: It represents the target queue is `queue-q1`.  
      - `queue-q1@`: Invalid setting.  
      - `queue-q1@label-1`: It represents the target queue is `queue-q1` with `label-1` for `yarn.application.node-label` key.  
      - `queue-q1@label-1, label-2`: It represents the target queue is `queue-q1` with `label-1,label-2` for `yarn.application.node-label` key.   

- The `Backend` arrange the configuration for the current application based on the `Yarn queue` value.  

# About improvement of yarn-queue [In the long-term, not in the current issue]
If this is meaningful for improving usability in `yarn-application` execution mode, 
IMO, Maybe we could introduce the queue-resource-manage feature in the long term. After that, There will be  some advantage:
- Keeping the available yarn-queues in `streampark` is helpful to keep the boundary between `Streampark` and `yarn-cluster`.
  - Prevent queue abuse.
  - Prevent failed submission caused by non-existent queue.
- Make it easier for users to perceive and to user the available yarn queues.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
great features, Looking forward to we complete this feature together

**Comment by RocMarshal** [comment]
Thanks @wolfboys for the reply~
Maybe it's more appropriate to drive a new issue for yarn-queue-resource management feature.

And the current issue described in the title could start implement now due to the small change range.

Please let me know what's your opinion?
