### ISSUE TITLE
[Bug] illegal file type, Only standard jar files supported

### ISSUE THREAD

**Issue by Observe-secretly** [apache/streampark#2309]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

# Operate
When creating a flanksql task, some jar package files are not recognized.
</br>
@wolfboys  You can try to find [org.apache.logging.log4j.log4j.log4j-1.2-api.2.17.1](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-1.2-api/2.17.1) in the mvnrepository.com. Download it and upload it to reproduce the problem.

# How to solve it
Append `504B03040A000808` to line 53 of the FileUtils.scala file

# Suggestion
The header enumeration is placed as configuration information in the application.yml file

### StreamPark Version

StreamPark RC6

### Java Version

1.8

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
2023-02-07 19:42:13 | INFO  | qtp546271589-48 | org.apache.streampark.console.base.handler.GlobalExceptionHandler:68] api exception：illegal file type, Only standard jar files supported
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
maybe is bug. you can test this code, if pass, you can submit a PR
```
  def isJarFileType(input: InputStream): Boolean = {
    if (input == null) {
      throw new RuntimeException("The inputStream can not be null")
    }
    val headerHex = Utils.tryWithResource(input) { in =>
      val b = new Array[Byte](6)
      in.read(b, 0, b.length)
      bytesToHexString(b)
    }
    val jarFileTypes: mutable.Seq[String] = mutable.Seq(
      "504B03040A00",
      "504B03041400"
    )
    jarFileTypes.contains(headerHex)
  }
```
