### ISSUE TITLE
[Bug] After switching groups, the monitoring dashboard information is not switched correctly.

### ISSUE THREAD

**Issue by green241** [apache/streampark#2315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After switching groups, the monitoring dashboard information is not switched correctly.

Firstly, I created two flink tasks with the user admin in default group.
![image](https://user-images.githubusercontent.com/14801784/217754746-4d40ba30-519d-4582-9467-ffb2851c154d.png)

However ,when switching the group from default to test which I had creeated, the monitoring dashboard showing as following,

![image](https://user-images.githubusercontent.com/14801784/217754972-822d2517-2745-4d8a-b5cb-b3792ed2c32b.png)

Therefore, I feel it is a bug ,please check it.

**2023.2.16 add: this issue only appears in kubernetes mode , yarn mode is normal.**

### StreamPark Version

2.0.0

### Java Version

1.8.0_181

### Flink Version

1.14.3

### Scala Version of Flink

2.12

### Error Exception

```log
Referring the "what happened" module.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please use the latest version to test it

**Comment by green241** [comment]
> Please use the latest version to test it

After testing the latest code of the two branches of release-2.0.0 and dev respectively, it is found that the problem still exists .

But looking at the code comments, it seems that the job status statistics are excluded in k8s mode (the reason is not clear yet)， as following 
![image](https://user-images.githubusercontent.com/14801784/219743718-ca575dd9-3927-41a0-97f5-445514fa4a30.png)

**Comment by Kick156** [comment]
I want to try to repair it. Can you assign it to me

**Comment by wolfboys** [comment]
> I want to try to repair it. Can you assign it to me

done

**Comment by green241** [comment]
[PR](https://github.com/apache/incubator-streampark/pull/2376)
