### ISSUE TITLE
[Bug] No alert msg on FE when updating application with exception.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2325]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

- I can't sure that the case type was known for community because my glance at the 2.0.0 edition preview.

- No alert msg on FE when updating application with exception (It only affects the user experience and is not strictly a bug.
May be  design missing  or classical bugs in the current edition but not exception interceptor catch mechanism missing )

- A solution to fix the case  
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/64569824/218296169-e793ead1-0da6-4bf5-b343-7e5ee411a139.png">

After the change:

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/64569824/218296298-225a4b92-79dc-46c9-8afd-fb8c10ceaccb.png">

### StreamPark Version

N.A 

### Java Version

1.8

### Flink Version

N.A

### Scala Version of Flink

2.12

### Error Exception

```log
N.A
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
We need to inform users of more operational  error info, not just the backend record error logs, Welcome to improve this part

**Comment by RocMarshal** [comment]
@wolfboys Thx. brother~.
I'll paste the docs I sorted out here. 
Then try to fix the corresponding lines.
finally Add a mini-section into the community contribute part to describe a rule for Devs & Reviewers.

**Comment by RocMarshal** [comment]
# Current exception process strategy
There are two kinds of exception.
- The exceptions inherited from `AbstractApiException` was introduced to remind the hint message to users when users use platform with illegal data or input such as `Application name already exited.`, `illegal arguments`, ...  The intention of the exceptions is remind the users to use feature correctly. The exceptions notification samples like the follows:
  <img width="682" alt="image (1)的副本" src="https://user-images.githubusercontent.com/64569824/219830469-b1f5e7f0-a3d0-406f-9d57-afbfef626af9.png">


- The other exceptions not the sub-class of `AbstractApiException` ,which  represents the server internal error. The exceptions will notify by the following notification.
 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/64569824/219830394-f6fba818-099d-49ce-b838-57a7e5c8357a.png">


# Issues existed in the current edition
There is a problem in the try catch block where some exceptions are just logged but not re-throwed, resulting in both exceptions strategy not being triggered.

# How to solve
Collate whether there are try - catch cases in the controller's corresponding interface that have not been re-thrown, then fix its.


# How to avoid 

Make a overview of exception process strategy for `streampark-console-service`.
Describe in the following document: Tentatively, try catch exceptions are handled strictly from two perspectives (reviewers, developers).   Be careful about ignoring exceptions, and in general you must re-throw the exception

![image](https://user-images.githubusercontent.com/64569824/219830681-7219b335-c8a6-4c21-a570-fd994b8e7dbe.png)

**Comment by RocMarshal** [comment]
any suggestions is appreciated. thank you.  Please correct me if I'm wrong in some comprehension
