### ISSUE TITLE
[Bug] files that are mentioned in the docker installation manual are missing

### ISSUE THREAD

**Issue by neverchanje** [apache/streampark#2345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

n/a

### Scala Version

2.11.x

### StreamPark Version

n/a

### Flink Version

n/a

### deploy mode

None

### What happened

I'm not sure if this is the right place for document issues.

I tried the installation steps in your English-version document and failed. The files are missing. The links in your Chinese docs are correct.  

Eng version:

```
wget https://raw.github.com/apache/incubator-streampark/blob/dev/deploy/docker/docker-compose.yaml
wget https://raw.github.com/apache/incubator-streampark/blob/dev/deploy/docker/.env
docker-compose up -d
```

Chn version:

```
wget https://raw.githubusercontent.com/apache/incubator-streampark/dev/deploy/docker/docker-compose.yaml
wget https://raw.githubusercontent.com/apache/incubator-streampark/dev/deploy/docker/.env
docker-compose up -d
```
 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
