### ISSUE TITLE
[Bug] try to deploy streamx2.0 aka streampark , however sign in error

### ISSUE THREAD

**Issue by wh279813** [apache/streampark#2349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.0

### Flink Version

1.14.5

### deploy mode

None

### What happened

After calling sign in api , with response 200 OK, but doesn't any rediection , maybe something goes wrong on front-end website

### Screenshots

![image](https://user-images.githubusercontent.com/7261859/220282729-52f9b6ad-b763-432c-8503-809af3c31e37.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wh279813** [comment]
Streamx idea is amazing , do you guys have a chat group ? Very glad to join the team

**Comment by wh279813** [comment]
node version v16.17.0, everything goes fine on streamx version 1.2.3

**Comment by wolfboys** [comment]
> Streamx idea is amazing , do you guys have a chat group ? Very glad to join the team

Please see the README, Follow our WeChat Official Account

**Comment by wolfboys** [comment]
Please clear the browser cache and make sure the username and password (admin/streampark) are correct
