### ISSUE TITLE
[Bug] Error link for the documents about Docker Quick Tutorial

### ISSUE THREAD

**Issue by hk-lrzy** [apache/streampark#2356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

-

### Flink Version

-

### deploy mode

None

### What happened

<img width="970" alt="截屏2023-02-22 18 03 08" src="https://user-images.githubusercontent.com/14176134/220587947-73d3f50d-32c7-410b-b902-3678994f9326.png">
When i follow the document try to download `docker-compose.yaml`, it show the 404 code.

### Error Exception

```log
-
```

### Screenshots

```
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2023-02-22 17:53:37 错误 404：Not Found。
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed. more detail: https://github.com/apache/incubator-streampark-website/pull/184
