### ISSUE TITLE
[Bug] login:SignIn failed, authentication error

### ISSUE THREAD

**Issue by rusonding** [apache/streampark#2361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.0.0

### Flink Version

1.14.5-scala_2.12

### deploy mode

None

### What happened

![image](https://user-images.githubusercontent.com/21210508/220849542-2ffec77a-6b1c-4470-86dc-008234e71922.png)
![image](https://user-images.githubusercontent.com/21210508/220849598-148cce74-97be-4fe8-b6f1-5e55b7c6404d.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rusonding** [comment]
version: '3.8'
services:
  streampark-console:
    image: apache/streampark:v2.0.0

**Comment by mymmyy** [comment]
new version auth is:
admin/streampark
