### ISSUE TITLE
[Bug]The token was expected to have 3 parts

### ISSUE THREAD

**Issue by denglhh** [apache/streampark#2370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.0_312

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.13.2

### deploy mode

yarn-application

### What happened

Debug the/link/app/start interface through the api, and prompt:The token was expected to have 3 parts, but got 1.
Response status：401

example（Token is copied from Token manager）：
curl -X POST -H  "Accept:*/*" -H  "BearerToken:b702a408028cbf3ff5d8049ae73d1c3fb28c5fd9c4d2526984fc16c56a3b6ec11bb1eb4193dd95a4bda47eac2a36a7c8547ce484e71549e6d981028ff63885b97d4741ae0b72e39fba233420306a95b668ca2a65dce636759e7eeac3866732b1aa5353f9366fc988690286a41efc913cc2c9915ea773b572f5d73d1a7ed150a0a49fd8f5353df4faf0f69cb82f74cc8e0319a7f317f0bbb572be41bd8065c394" -H  "Content-Type:application/x-www-form-urlencoded" --data-urlencode  "allowNonRestored=false&flameGraph=false&id=100026&savePoint=cc&savePointed=false" "http://hdfs-test03.yingzi.com:12345/flink/app/start"

### Error Exception

```log
The token was expected to have 3 parts, but got 1.
```

### Screenshots

![图片](https://user-images.githubusercontent.com/31583324/221518472-87bb34ae-fe48-4b4c-86a5-ea2fc89e6674.png)
![图片](https://user-images.githubusercontent.com/31583324/221518538-e12e011e-dd12-4b68-b961-78ef86a41d23.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
parameter key of token in header is: "Authorization", not "BearerToken"

**Comment by wolfboys** [comment]
parameter key of token in header is: "Authorization", not "BearerToken"
