### ISSUE TITLE
[Bug] lark alarm template can't cancelled

### ISSUE THREAD

**Issue by kangweihao0321** [apache/streampark#2373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.0_191

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.15.1

### deploy mode

yarn-application

### What happened

When I edit application, if the application has set an alarm template, this template will not be cancelled.

![](https://user-images.githubusercontent.com/69979507/221731815-a965a27c-e82f-4bc5-8687-e5634f6d3a31.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
No more detailed information provided for this issue, it is difficult for us to judge why it not work. You can check more detailed reasons from the backend service log and Feishu's access docs
