### ISSUE TITLE
[Bug] StreamPark application flink resource settings invalid

### ISSUE THREAD

**Issue by kangweihao0321** [apache/streampark#2374]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.0_191

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.15.1

### deploy mode

yarn-application

### What happened

set flink taskmanager.memory.managed.size can't set 0, min value 128
![image](https://user-images.githubusercontent.com/69979507/221734268-35f18521-bc00-464a-ba99-a300b990415f.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kick156** [comment]
Can I have a try？

**Comment by wolfboys** [comment]
> Can I have a try？

ok
