### ISSUE TITLE
[Feature] Streampark supports reverse proxy flink web ui

### ISSUE THREAD

**Issue by lintingbin** [apache/streampark#2381]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/5699014/222039919-0cb0356d-662f-4961-9599-88deb185f90b.png">
We can choose different types on the "Rest-Service Exposed Type" option on the interface, but if we choose clusterIp and NodePort, we will not be able to directly access the Flink Web UI. Although you can directly access the Flink Web UI by choosing loadbalancer, you need an independent external network IP to achieve access, which will increase additional costs and may also cause security problems. If StreamPark itself can reverse proxy access to Flink Web UI, each application can be deployed as a clusterIp type, and at the same time, it can combine StreamPark's url path to implement permission control.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Supported in new version
