### ISSUE TITLE
[Bug] StreamPark upgrade compatibility issues

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#2389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.14.4

### deploy mode

yarn-perjob

### What happened

My StreamPark is upgraded from StreamPark 1.2.4-SNAPSHOT (a package compiled by myself before 2022.11.03) to StreamPark 2.0.0. During the use, it is found that the job name encrypted by the Base64 algorithm will appear on Yarn after submitting the job Jar compiled with StreamPark 1.2.4-SNAPSHOT.

I check the submission record. The problem is that https://github.com/apache/incubator-streampark/commit/cc71e161bcd0c9808d17130318d3c1eda8ab8d17 This submission

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
At present, there is no particularly good solution, you can go through the job submission process again
