### ISSUE TITLE
streampark 2.0 version build.sh error

### ISSUE THREAD

**Issue by yimingtech** [apache/streampark#2393]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

![image](https://user-images.githubusercontent.com/4756021/222683087-71467da8-f65d-49f0-a96a-dcfbc5f152d1.png)

streampark 2.0 version build.sh error

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
hi, Thank you for your feedback, you can test this [pr](https://github.com/apache/incubator-streampark/pull/2398)
