### ISSUE TITLE
[Improve] Standardize the style of existing test cases.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2397]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Standardize the style of existing test cases. Include method name and class location @RocMarshal 

### Related issues

#2014 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Only for `console-service` module. 
1. Remove test classes in package org.apache.streampark.common.util in test dir.  
2. Rename `GitTest` located in org.apache.streampark.console.core.entity  to `ProjectTest`.  
3. Convert `sysout` to `assertion` statements or `LOG` if needed.  
4. Standarlize the test methods naming style  

CC @wolfboys @MonsterChenzhuo

**Comment by wolfboys** [comment]
> Only for `console-service` module.
> 
> 1. Remove test classes in package org.apache.streampark.common.util in test dir.
> 2. Rename `GitTest` located in org.apache.streampark.console.core.entity  to `ProjectTest`.
> 3. Convert `sysout` to `assertion` statements or `LOG` if needed.
> 4. Standarlize the test methods naming style
> 
> CC @wolfboys @MonsterChenzhuo

Looks good to me, BTW, I suggest methods in SenderEmailTest move to AlertServiceTest.

**Comment by RocMarshal** [comment]
> I suggest methods in SenderEmailTest move to AlertServiceTest.

@wolfboys Good proposal~

Updated in the MR.
