### ISSUE TITLE
[Feature] show sql history in application detail tab

### ISSUE THREAD

**Issue by zhoulii** [apache/streampark#2401]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

StreamPark saves the history of sql and config for one application, in configuration tab, we can see the history of all the configuration details, and we can also delete a specific config or compare two configs. 

![image](https://user-images.githubusercontent.com/23091870/223010540-88813978-4bdd-4309-b0f0-796169b5a8d6.png)

But for sql, the detail tab only show the effective sql content.

![image](https://user-images.githubusercontent.com/23091870/223001986-e22cf4f6-90d7-479f-bdb6-f12599babb39.png)

 I propose to support these features that configuration tab owned for sql through two steps :
1. provide list api (get by page) and delete api in [FlinkSqlController](https://github.com/apache/incubator-streampark/blob/dev/streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/controller/FlinkSqlController.java) 
2. modify the front refer to the design of the configuration tab.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
great proposal
