### ISSUE TITLE
[Feature] Remove the Chinese comment and group by the docs by language

### ISSUE THREAD

**Issue by Zheaoli** [apache/streampark#2407]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Based on #2296

I don't know if we chose English as the working language. Suppose English is the functional language in this community, I may have some suggestions:

First, multiple languages have been mixed in the demonstration in the README. It's not the best practice.

![image](https://user-images.githubusercontent.com/7054676/223616119-c80a5ad1-26cd-482b-9f12-30ecf34fa79a.png)

Second, I have noticed many docs with the wrong structure on the docs site. The English title and the Chinese content make all the wrong docs. FYI https://streampark.apache.org/docs/flinksql/2-performance-tuning. I think it would be suitable for people if the docs were pure English docs when they choose English as the doc site language.

<img width="1553" alt="CleanShot 2023-03-08 at 12 00 13@2x" src="https://user-images.githubusercontent.com/7054676/223616355-20f95979-d68b-4e14-bd4b-f27a92506177.png">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
We will improve them

**Comment by Zheaoli** [comment]
This issue is closed without any reason. Would you mind to tell me the reason?

**Comment by madper** [comment]
> use english
