### ISSUE TITLE
Flink restart does not start from checkpoint

### ISSUE THREAD

**Issue by denglhh** [apache/streampark#2438]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.13.2

### deploy mode

yarn-application

### What happened

Flink can be restarted after the task setting fails, but not from the checkpoint

### Screenshots

![图片](https://user-images.githubusercontent.com/31583324/224887316-4bc8d6c8-4da1-402f-ab2b-f9b9288da9f3.png)

![图片](https://user-images.githubusercontent.com/31583324/224887390-9b64a260-22fb-4dd4-ab3d-4c2fc1f593b9.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Trgree** [comment]
Bug still exists，Job restart does not recover from checkpoint。
streampark-2.1.0-SNAPSHOT 
flink on yarn application
