### ISSUE TITLE
[Feature] Support openapi3 

### ISSUE THREAD

**Issue by lvshaokang** [apache/streampark#2460]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support openapi3 & add unit AccessTokenServiceTest 

### Usage Scenario

e.g.
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/29084491/225953954-3eed6324-e8c4-4b5e-a465-b6a52667c9a7.png">
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/29084491/225954068-530eb1eb-ad9e-42c6-ae67-1ec15744b34f.png">

### Related issues

TODO
1. add unit tests for retains interface
2. complete openapi doc
3. refactor api use RestApi

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good job. great feature.

**Comment by MonsterChenzhuo** [comment]
@lvshaokang The Server layer of each interface is best to add a callback timeout, the logic of this callback timeout I had written a tool class, the latter was changed by Ben, you can look for
