### ISSUE TITLE
[Bug] Duplicate dependencies in console module.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#2512]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

lastest

### Flink Version

none

### deploy mode

None

### What happened

<img width="603" alt="企业微信截图_16799884044716" src="https://user-images.githubusercontent.com/13617900/228160603-553ef668-0ef8-4f45-9bb1-10aa213070c1.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
@wolfboys Pls add `good first issue` label.

**Comment by wolfboys** [comment]
> @wolfboys Pls add `good first issue` label.

done
