### ISSUE TITLE
[Polish] Delete tutorial backend code.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#2513]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

latest

### Flink Version

none

### deploy mode

None

### What happened

<img width="592" alt="企业微信截图_16799887702560" src="https://user-images.githubusercontent.com/13617900/228162055-fa5f8289-1ade-4e00-b82f-a6650db58d33.png">
`tutorial` was useless and should be deleted.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
@wolfboys Pls add good first issue label.

**Comment by wolfboys** [comment]
> @wolfboys Pls add good first issue label.

done

**Comment by Kick156** [comment]
the TutorialController involve TutorialServiceImpl、TutorialService、Tutorial，delete four of them，do I understand correctly?

**Comment by GOODBOY008** [comment]
> the TutorialController involve TutorialServiceImpl、TutorialService、Tutorial，delete four of them，do I understand correctly?

Mapper,sql also should be deleted. @Kick156 Would you take this issue? @wolfboys cc

**Comment by Kick156** [comment]
> > TutorialController涉及TutorialServiceImpl、TutorialService、Tutorial，删除其中四个，我理解对吗？
> 
> 映射器，sql也应该被删除。@Kick156你能接受这个问题吗？@狼人男孩复写的副本

Okay, I see. I can give it a try

**Comment by Kick156** [comment]
> > the TutorialController involve TutorialServiceImpl、TutorialService、Tutorial，delete four of them，do I understand correctly?
> 
> Mapper,sql also should be deleted. @Kick156 Would you take this issue? @wolfboys cc

Thank you for your reply. I can give it a try
