### ISSUE TITLE
[Improve] Optimize methods for Savepoint service.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2534]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Optimize the method arrange and split it into blocks for better test.

### Usage Scenario

N.A

### Related issues

N.A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Hi, @wolfboys @MonsterChenzhuo @GOODBOY008 
I want to optimize the service for two items: 
- Split the corresponding methods into new methods with small blocks
- Try to add the test cases.
Any suggestion is appreciated~
Thank you~

**Comment by wolfboys** [comment]
Good idea, looking forward to your optimization of this part
