### ISSUE TITLE
[Bug] If the first start of a task fails, even if the task restart successfully, the application Run Status is incorrect

### ISSUE THREAD

**Issue by jasonzhuV** [apache/streampark#2536]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

release-2.0.0

### Flink Version

1.14.5

### deploy mode

yarn-application

### What happened

1. I create a application in "Custom Code" Mode in Steampark and set the Fault Restart Size as 3.
2. I click  "Start Application" after "Launch Application".
3. Observe Option Logs，the application strat success, then jump to Flink Web UI, finally the job failed and jm is shutdown.
4. Streampark restart application according to Fault Restart Size.
5. Observe Option Logs angin, a new start log appears, jump to Flink Web UI, finally the job run successfully.
6. Check the "Run Status" of application in streampark, it's "FAILED", but the FlinkJob is running in yarn.

### Error Exception

```log
No response
```

### Screenshots

![image](https://user-images.githubusercontent.com/31977536/228822282-5bc93179-e80a-4ca7-9b49-beb8467bea5d.png)
![image](https://user-images.githubusercontent.com/31977536/228822364-3b860f00-8a85-45d2-8533-f962e387025c.png)
![image](https://user-images.githubusercontent.com/31977536/228822459-e38e406a-d4b1-453a-901a-05c1632732df.png)
![image](https://user-images.githubusercontent.com/31977536/228822537-bc8930bf-b389-4d5f-a2b2-1c13268a08e4.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
hi:
Thanks for your contribution, can you tell me why we need to add this enum value ?

**Comment by jasonzhuV** [comment]
In release-2.0.0, when getLaunchState was called, it will return LaunchState enum, the return might be null.
I didn't notice the problem has been fixed in dev, Sorry to interrupt.

**Comment by jasonzhuV** [comment]
I will switch to the dev branch to confirm this issue later.

**Comment by wolfboys** [comment]
fixed, see this [pr](https://github.com/apache/incubator-streampark/issues/2366)
