### ISSUE TITLE
[OnlineMeeting&April.1]StreamPark community meeting Topic collect

### ISSUE THREAD

**Issue by monrg** [apache/streampark#2544]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Description
benjobs invites you to a meeting on Tencent Meeting
Meeting Topic: StreamPark Community Meeting
Time: 2023/04/01 20:00-20:30 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/UJKkbCpHF46k

#TencentMeeting：590-1732-3973

Copy this invitation and open in Tencent Meeting app (V3.14 or later) to join the meeting
Everyone is very welcome to join:
If you have an issue, please submit it before the meeting, and provide a specific issue link and context.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Glad to view this topic. 
I'd like to be interested in the follows:
- Support *Flink version delete* https://github.com/apache/incubator-streampark/issues/2542
- What do we need to do before the next release? 
  - Would we have any specific plans for the todo-items? (May I get a few task to do?)
- Is any progress about the latest roadmap draft discussed on last meeting?

I'd love to hear anything about other topics, too.
Thank you so much~. 😁

**Comment by Kick156** [comment]
1.About the Code Quality Assurance System
    for Doris：Java Format Code https://doris.apache.org/community/developer-guide/java-format-code/
    for dolphinscheduler：Code of Conduct  https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/code-conduct.md
2.About verify the candidate version
3.About the arrangement of release notes
