### ISSUE TITLE
[Bug] externalLink form preview color feature not works

### ISSUE THREAD

**Issue by asuiah** [apache/streampark#2549]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

latest

### Flink Version

none

### deploy mode

None

### What happened

When creating/updating external link , color in preview is not working after clicking template badge.

### Screenshots

<img width="928" alt="image" src="https://user-images.githubusercontent.com/44203829/229348476-85c55125-912a-40d8-b015-9f3c24bdd4c8.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
