### ISSUE TITLE
[Bug] Docker image build failed

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#2555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.0.0

### Flink Version

1.14.5

### deploy mode

kubernetes-application

### What happened

![图片](https://user-images.githubusercontent.com/60029759/229431996-38132738-03ae-4e23-9d9b-9d152d7f9085.png)
<img width="1276" alt="图片" src="https://user-images.githubusercontent.com/60029759/229432018-78dd8b11-bc31-4bb1-b1ee-103b21c7644f.png">
I tried all the ways to make this task successful, such as clearing all docker images on the host, restarting streampark, copying a new one, and retrying to build after modification.
Add: Not all tasks, this situation will occur in this task. In the process of nearly half a year of use, this situation has been found four times.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CodingGPT** [comment]
Yes I am willing to submit a PR

**Comment by wolfboys** [comment]
> Yes I am willing to submit a PR

👍

**Comment by wolfboys** [comment]
fixed in new version
