### ISSUE TITLE
[Bug] Config of Application can't be copied

### ISSUE THREAD

**Issue by NightRunner** [apache/streampark#2600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.0.0

### Flink Version

all

### deploy mode

None

### What happened

When I copy a Application , the config not be copied. I guess it's a Bug.

[Because the condition is always false](https://github.com/NightRunner/incubator-streampark/blob/721a88f89dd07e6502285616a21645030125f638/streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/core/service/impl/ApplicationServiceImpl.java#L811)### 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, it is a bug.I think you already know how to fix it, welcome to fix this bug
