### ISSUE TITLE
[Feature] In the historical version selection box, you want to add the time field of the version

### ISSUE THREAD

**Issue by Observe-secretly** [apache/streampark#2604]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the Historical Version selection box, you want to increase the time field of the version. In this way, when the version is compared, the corresponding version can be located more quickly.

### Usage Scenario

Quickly locate historical versions for comparison

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
Hi  @wolfboys , feature added by [PR-2607](https://github.com/apache/incubator-streampark/pull/2607),  issue can be closed.
