### ISSUE TITLE
[Feature] support format scala code with spotless-maven-plugin

### ISSUE THREAD

**Issue by zhoulii** [apache/streampark#2611]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Streampark's inspection of scala code format is not strict, there are some inappropriate code format which are not detected. Besides, scala code format ofthen changes in pr which brings some unnecessary review work. Here we use the import order as an example (many scala classes in streampark have inappropriate import order):

![Snipaste_2023-04-13_11-13-28](https://user-images.githubusercontent.com/23091870/231644366-b16b6de4-60c8-49cd-b1ae-f611dfa8708d.png)

the left side is the import order of [FlinkClientTrait.scala](https://github.com/apache/incubator-streampark/blob/dev/streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/trait/FlinkClientTrait.scala#L20-L51) ，as we can see, the import package is decentralized. The right side is the reformated version, we put the imports from same project together, and make streampark's imports on the top. 

streampark uses `spotless-maven-plugin` to format java code, this plugin also can support format scala code by rules, maybe we can integrate this feature into stremaprk project.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Great,  we need this plugin

**Comment by senlizishi** [comment]
Agree. The existing scalastyle maven plugin in the Streamark project can only be used to detect scala formats and cannot be formatted.
