### ISSUE TITLE
[Feature] support dependency management

### ISSUE THREAD

**Issue by zhoulii** [apache/streampark#2681]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

StreamaPark supports users upload jar when editing application, It would more convenient if we provide a easy way to manage dependency. For example, the users in the same team can share all the dependencies, because the dependencies are reused in team, maybe we can save a lot disk space.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
## 1.home page of team dependency management

![dependency-1](https://user-images.githubusercontent.com/23091870/234503025-592db3db-e97e-451a-bb0d-e81137aa8585.png)
---
![dependency-2](https://user-images.githubusercontent.com/23091870/234503069-a8d93a06-47e5-4c56-87a9-f4b8c14aea47.png)

## 2.add dependency page

![dependency-3](https://user-images.githubusercontent.com/23091870/234503310-5ac4bd9d-1354-4627-8b32-42867cc9ad95.png)

## 3.edit dependency page

![dependency-4](https://user-images.githubusercontent.com/23091870/234503382-2d5d4237-15f3-485d-abaa-6ed32e6f9807.png)

## 4.support edit and delete action now

![dependency-5](https://user-images.githubusercontent.com/23091870/234503550-13801c17-2783-4785-a52f-cf65dc3e95ff.png)

## 5.when create or edit application, you can choose dependency from team dependency library

![dependency-6](https://user-images.githubusercontent.com/23091870/234503815-322595b2-3900-40a1-8f52-06ede67d3fbc.png)
---
![dependency-7](https://user-images.githubusercontent.com/23091870/234503863-072a93f2-afd3-4001-bb5c-e4f63529cac0.png)

**Comment by zhoulii** [comment]
Based on the meeting discussion, there are some changes about this issue.

## 1. Fine grained resource management

For better distinguishment, We divide user resources into 5 categories:

- **APP**: user jar, like `WordCount`
- **CONNECTOR**：flink connector, like `flink-connector-kafka`、`flink-connector-hbase`
- **FORMAT**：flink format, like `flink-orc`、`flink-avro`
- **UDF**：user defined function, including `UDF/UDAF/UDTF`
- **COMMON**：common dependency, like `mysql-connector-java`

when adding resource, we can choose the resource type:

![1](https://user-images.githubusercontent.com/23091870/235874365-9a737df7-6517-442a-9529-789158a925a1.png)

There's a slight difference with `APP`，When `APP` resource type is chosen, we need provide the entry class of the job:

![2](https://user-images.githubusercontent.com/23091870/235874444-e846a773-1c63-4d23-bc27-e71d602e0819.png)

the overview of resource management page is like：

![3](https://user-images.githubusercontent.com/23091870/235874509-aa5c71ff-1eb6-410c-9388-e15d1b6c4f5a.png)

## 2.integrate resource management with upload job

when we create a flink app, we can choose the jar from resources. we can select or search resource from the drop-down box, only `APP` resource type would be shown here.

![4](https://user-images.githubusercontent.com/23091870/235874578-49b0af12-1a16-4dd7-8b76-5af6080d448f.png)

when selected, the `Program Main` would be filled automatically.

![5](https://user-images.githubusercontent.com/23091870/235874695-d721ea2e-5c72-43c0-baf5-a429396fa524.png)

## 3.integrate resource management with sql dependency

We can add resources for flink sql application via the following way (`APP` resource type are excluded here.):

![6](https://user-images.githubusercontent.com/23091870/235874819-59e5aa2f-134e-4591-9f67-4300ef5b54a2.png)

We can search resource with `resource type` or `resource name`. For example，if we enter `format` in the drop-down box, the results are：

![7](https://user-images.githubusercontent.com/23091870/235874941-85188d1f-fcd8-49d5-a10a-a0b63e543258.png)

if we enter `kafka` in the drop-down box, the results are：

![8](https://user-images.githubusercontent.com/23091870/235875078-05a85d6b-f480-4794-b874-7e4e51ad1e41.png)

**Comment by xiaows08** [comment]
> ## 2.integrate resource management with upload job
Could `Program Main` be drop-dwon selected or modified? Because some jar's file contain many main-classes in a project.
@wolfboys @zhoulii
