### ISSUE TITLE
[Bug] The job status is always initializing

### ISSUE THREAD

**Issue by gtyi999** [apache/streampark#2701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java8

### Scala Version

2.11.x

### StreamPark Version

2.0.0

### Flink Version

1.16.0

### deploy mode

kubernetes-application

### What happened

作业状态一直卡在 初始化中

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by senlizishi** [comment]
Hi. This issus has been solved in #2579  , you can pull the latest code or or wait for the new version to be released to experience.
