### ISSUE TITLE
[Bug] job cannot be displayed

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#2712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.14.4

### deploy mode

None

### What happened

Background: Someone resigned from the company and the administrator deleted the streampark user.
Impact: Tasks created by deleted users cannot be displayed in the application management interface.

### Error Exception

```log
nothing
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xujiangfeng001** [comment]
Hi maintainers, this issue was discovered during my use of streampark.For this situation, I have come up with the following solution:

1. When deleting a user, determine whether the user has created a task, and if so, restrict the deletion of the user.
2. Add the function of transferring the ownership of homework to designated users.

 I look forward to your valuable suggestions from the maintainers.

**Comment by wolfboys** [comment]
Thanks for your feedback. This is a bug  and we need to discuss it. Currently, we need to address the following issues:

1. Only super admin can delete users.
2. Before deleting, we need to check if there are any jobs belongs to this user
3. If any jobs belongs to this user, we need to transfer all jobs to another user before deleting it.

**Comment by xujiangfeng001** [comment]
> Thanks for your feedback. This is a bug and we need to discuss it. Currently, we need to address the following issues:
> 
> 1. Only super admin can delete users.
> 2. Before deleting, we need to check if there are any jobs belongs to this user
> 3. If any jobs belongs to this user, we need to transfer all jobs to another user before deleting it.

Hi @wolfboys ，thank you very much for your feedback. I will organize a meeting soon and invite developers to discuss this issue.

**Comment by VampireAchao** [comment]
please assign me

**Comment by xujiangfeng001** [comment]
Hello everyone, after discussion, our solution for this issue is as follows:
Requirement: 

- The administrator cancels the user deletion function and replaces it with disabling users.

Detailed logic:

1. The administrator cancels the user deletion function.
2. When the user account is disabled, it cannot own resources (application and project ownership)
3. Add resource transfer function to transfer disabled user resources to new users
