### ISSUE TITLE
[Bug] The app run status is always STARTING

### ISSUE THREAD

**Issue by Jcodelove** [apache/streampark#2732]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

latest
DIGEST ：cb5b91963239

### Flink Version

1.15.3

### deploy mode

kubernetes-session

### What happened

The app run status is always STARTING when the app runing(JobManager can see the corresponding task also k8s can see the corresponding pod). The kubenetes-session and kubenetes-application both have this problem.

### Error Exception

```log
15:44:00.141 [ForkJoinPool-1-worker-0] WARN org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher - Failed to visit remote flink jobs on kubernetes-native-mode cluster, and the retry access logic is performed.
```

### Screenshots

![image](https://user-images.githubusercontent.com/76688605/236610609-d3406edc-dc27-4919-add5-97add6a96108.png)
![image](https://user-images.githubusercontent.com/76688605/236610726-f75a7e80-3ae8-44c0-9970-d7972b793078.png)

![image](https://user-images.githubusercontent.com/76688605/236610752-63d803a8-ae3c-40db-a026-e206e45c3d83.png)
![image](https://user-images.githubusercontent.com/76688605/236610769-5356d260-3b75-49cc-b1bf-412540576470.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Jcodelove** [comment]
![image](https://github.com/apache/incubator-streampark/assets/76688605/bba9a611-1760-4d64-9f64-9ec4e11a9f9a)
unimaginable!!

**Comment by wolfboys** [comment]
> ![image](https://user-images.githubusercontent.com/76688605/237382237-bba9a611-1760-4d64-9f64-9ec4e11a9f9a.png) unimaginable!!

Thanks for your feedback. I think you already know how to solve it. Could you fix this bug? We are looking forward to see your PR

**Comment by minchowang** [comment]
<img width="543" alt="image" src="https://github.com/apache/incubator-streampark/assets/33626973/0bac0774-0bd8-445b-86a6-ba8311ff42af">

```buildDate``` might also be an empty string.

**Comment by minchowang** [comment]
> <img alt="image" width="543" src="https://private-user-images.githubusercontent.com/33626973/285696579-0bac0774-0bd8-445b-86a6-ba8311ff42af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc4MDIsIm5iZiI6MTcwMTA0NzUwMiwicGF0aCI6Ii8zMzYyNjk3My8yODU2OTY1NzktMGJhYzA3NzQtMGJkOC00NDViLTg2YTYtYmE4MzExZmY0MmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjNhMDgzMGM2OTAwNzUwMTAzMDE0MmNjY2NiMDNlMzIzOWExZjRiNDJhNzI1M2I2NmQ5ODJlODgyMzJhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kn5rAb0ow3_NEn67zrIploPNxsExAOumI2lNaFbGvdo">
> `buildDate` might also be an empty string.

On TKE（Tencent cloud）

**Comment by tuoluzhe8521** [comment]
why i have the same problem when i use streampark2.1.2. And i also use TKE（Tencent cloud）?

**Comment by tuoluzhe8521** [comment]
Do you resolve it?

**Comment by tuoluzhe8521** [comment]
> <img alt="image" width="543" src="https://private-user-images.githubusercontent.com/33626973/285696579-0bac0774-0bd8-445b-86a6-ba8311ff42af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODQyMTAsIm5iZiI6MTcwMTY4MzkxMCwicGF0aCI6Ii8zMzYyNjk3My8yODU2OTY1NzktMGJhYzA3NzQtMGJkOC00NDViLTg2YTYtYmE4MzExZmY0MmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA5NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDU1MWI5YmQxOTdmMzYwMzI0MjkxNDBmZmQxMWEwNWM0ZDllMzMwMmZhZGZjMDM5MTYzNTc4N2ExODYzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqQVvJHF08EbY8pFxbPtDKeoxhCkUyfWY_TeDDp-Os4">
> `buildDate` might also be an empty string.

Do you resolve it?

**Comment by Jcodelove** [comment]
> > <img alt="图像" width="543" src="https://private-user-images.githubusercontent.com/33626973/285696579-0bac0774-0bd8-445b-86a6-ba8311ff42af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc4MDIsIm5iZiI6MTcwMTA0NzUwMiwicGF0aCI6Ii8zMzYyNjk3My8yODU2OTY1NzktMGJhYzA3NzQtMGJkOC00NDViLTg2YTYtYmE4MzExZmY0MmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjNhMDgzMGM2OTAwNzUwMTAzMDE0MmNjY2NiMDNlMzIzOWExZjRiNDJhNzI1M2I2NmQ5ODJlODgyMzJhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kn5rAb0ow3_NEn67zrIploPNxsExAOumI2lNaFbGvdo">
> > `buildDate` 也可能是一个空字符串。
> 
> 关于TKE（腾讯云）

Can't see picture....

**Comment by tuoluzhe8521** [comment]
> > > <img alt="图像" width="543" src="https://private-user-images.githubusercontent.com/33626973/285696579-0bac0774-0bd8-445b-86a6-ba8311ff42af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc4MDIsIm5iZiI6MTcwMTA0NzUwMiwicGF0aCI6Ii8zMzYyNjk3My8yODU2OTY1NzktMGJhYzA3NzQtMGJkOC00NDViLTg2YTYtYmE4MzExZmY0MmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MjNhMDgzMGM2OTAwNzUwMTAzMDE0MmNjY2NiMDNlMzIzOWExZjRiNDJhNzI1M2I2NmQ5ODJlODgyMzJhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kn5rAb0ow3_NEn67zrIploPNxsExAOumI2lNaFbGvdo">
> > > `buildDate` 也可能是一个空字符串。
> > 
> > 
> > 关于TKE（腾讯云）
> 
> Can't see picture....

i have this problem now, how can i resolve it?

**Comment by minchowang** [comment]
Call Tencent qcloud customer service, apply the upgrade TKE API-server
