### ISSUE TITLE
[Bug] ERROR: streampark.workspace.local

### ISSUE THREAD

**Issue by yinshan612** [apache/streampark#2752]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.0

### Flink Version

1.16.0

### deploy mode

None

### What happened

An error was reported when setting the streampark. workspace. local address. The address I set is not in the streampark directory and still reports an error when starting

### Error Exception

```log
ERROR: streampark.workspace.local: "/opt/streampark_workspace/" is invalid path, Please reconfigure in application.yml
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/85284614/d05bbb48-7beb-41e9-9fe4-155421b73a13)
local workspace, used to store source code and build dir etc

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
This error happens because `/opt/streampark_workspace/` is not exist, you may need create it first.

**Comment by yinshan612** [comment]
Okay, I looked at the startup script for streampark.sh yesterday and it has been resolved. Thank you
