### ISSUE TITLE
[Bug]    API documentation, click to jump to the default port issue

### ISSUE THREAD

**Issue by chen-mh** [apache/streampark#2753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.1

### Flink Version

1.13

### deploy mode

None

### What happened

Change the default port of 10000, click the API document in the job management directory, and the jump address port is still 10000

### Error Exception

```log
Change the default port of 10000, click the API document in the job management directory, and the jump address port is still 10000
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
