### ISSUE TITLE
[Bug] Click Application Id Column of Operation Log tab can't jump correct url

### ISSUE THREAD

**Issue by NightRunner** [apache/streampark#2754]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.0

### Flink Version

1.6.0

### deploy mode

yarn-application

### What happened

Click Application Id Column of Operation Log tab can't jump correct url

### Screenshots

Click Application Id Column of Operation Log tab should be jump to url like follow:
http://host:port/cluster/app/application_xxx_xxx/

but now is:
http://host:port/application_xxx_xxx/

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
@NightRunner , Thanls for your feedback, will fix soon.
