### ISSUE TITLE
[Feature] Support custom savepoint path

### ISSUE THREAD

**Issue by cygnusdark** [apache/streampark#2763]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently the application in Streampark platform can only restart from recorded savepoint. In some circumstances, user may need to restart from custom savepoint path.
A PRD looks like this:
<img width="550" alt="image" src="https://github.com/apache/incubator-streampark/assets/53288632/fab64eae-a596-4c72-b8b5-f8aab0a33bf6">

If this feature is not in plan, I am willing to submit a PR.

### Usage Scenario

For example, when the latest successful savepoint/checkpoint is not recorded by streampark, user can restart from appointed savepoint.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Good proposal, I think it is necessary to support this feature.

**Comment by wolfboys** [comment]
supported
