### ISSUE TITLE
[Bug] The value submitted for 'application type' is not consistent with the saved value

### ISSUE THREAD

**Issue by himper** [apache/streampark#2765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.1.0

### Flink Version

1.15.4

### deploy mode

remote

### What happened

The value submitted for 'application type' is not consistent with the saved value.
![image](https://github.com/apache/incubator-streampark/assets/134488881/67e353cf-3335-4fc8-b0ec-f5eaf8d96806)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VampireAchao** [comment]
please assign me

**Comment by wolfboys** [comment]
> please assign me

done
