### ISSUE TITLE
[Bug] remote  mode，job task lost

### ISSUE THREAD

**Issue by lwzhangMr** [apache/streampark#2768]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.0.0

### Flink Version

1.14.6

### deploy mode

remote

### What happened

In remote mode, if the active jobmanager stops, all tasks under streampark are lost，However, in fact, the flink task is running normally, but the IP on the accessed UI address becomes another jobmanager IP。

### Screenshots

![2330e6edff6004f023841d942858e56](https://github.com/apache/incubator-streampark/assets/31753959/7a9b7a23-dbaf-4f6e-9f49-5ef2e7d4f8f7)
![c584a55c6c5c8f9a02fcef5d0937a0f](https://github.com/apache/incubator-streampark/assets/31753959/bd61bfbd-34a8-4f68-b06b-959eb2880a74)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lwzhangMr** [comment]
To add, it happens in standalone HA mode，when one active jobmanager stop

**Comment by wolfboys** [comment]
Thanks for your feedback,  The issue has been identified and will be improved in the next version.

**Comment by lwzhangMr** [comment]
在补充个场景，当remote ha 集群整个重启，然后活动的jobmanager不变，任务也同样会失联，但是flink其实都已经自动拉起来了。jobid和jobmanager都没变
报错截图
![image](https://github.com/apache/incubator-streampark/assets/31753959/022ec004-081a-40e3-82dd-c9e6a6474a26)
![image](https://github.com/apache/incubator-streampark/assets/31753959/d6d64d17-884a-4870-a5dd-681463f9f6a8)

目前是重启streampark，或者手动把任务重新映射下（其实jobid未变，只是报任务重新放到监测的队列），才能关联起来。
猜测是某一次获取状态时，正好集群停止或者任务重启，然后判断成失联了，建议：程序能设置在时间范围内一直尝试连接。

**Comment by lwzhangMr** [comment]
看源码，想到一个简单方式，针对remote模式应该没啥问题，就是再新增一个定时任务，比如每3分钟加载一次，把跟踪状态是lost的任务在重新加入到WATCHING_APPS 任务里。这样既不影响性能、也不耽误因集群重启或者网络不稳定等造成的任务失联。

**Comment by wolfboys** [comment]
fixed in new version(2.1.2)
