### ISSUE TITLE
[Bug] Wrong job type

### ISSUE THREAD

**Issue by HYBG-1126** [apache/streampark#2770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.0

### Flink Version

1.15.2

### deploy mode

kubernetes-application

### What happened

When I edit the flink code job, I select the Apache Flink job type, but the job type automatically changes to Streampark  Flink after I submit it 

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/44338121/1ce2a84a-4c65-4b50-be1e-058c46c104b6)
![image](https://github.com/apache/incubator-streampark/assets/44338121/14267e93-2b54-4783-b80a-bbc930267b05)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
@wolfboys , I found a fixed pr #2767 , but this problem still exists in the latest code.

**Comment by HYBG-1126** [comment]
Will it be fixed in the next release?
