### ISSUE TITLE
[Bug] Bug title LDAP cannot be authenticated after it is enabled

### ISSUE THREAD

**Issue by HYBG-1126** [apache/streampark#2772]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1

### Flink Version

1.15.2

### deploy mode

kubernetes-application

### What happened

When I restart Streampark after configuring LDAP according to the official website, I cannot log in to Streampark through LDAP, and I find that the LDAP configuration of the official website is inconsistent with the configuration fields in version 2.1

### Screenshots

![Snipaste_2023-05-29_10-26-29](https://github.com/apache/incubator-streampark/assets/44338121/476e3462-933b-43d6-891e-dd82b589262f)
![Snipaste_2023-05-29_10-39-22](https://github.com/apache/incubator-streampark/assets/44338121/a14feff6-90a5-4cdb-8303-2125177af527)
![Snipaste_2023-05-29_10-39-56](https://github.com/apache/incubator-streampark/assets/44338121/7f146113-8740-4b6e-a970-f29f12e06f07)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
Thanks for your report, it's a bug, will fix soon.

**Comment by HYBG-1126** [comment]
Will it be fixed in the next release?

**Comment by zhoulii** [comment]
> Will it be fixed in the next release?

yes, will be fixed in release 2.1.1

**Comment by HYBG-1126** [comment]
thank you
