### ISSUE TITLE
版本1.2.3 运行flinksql时日志级别设置没有生效，一直打印akka的debug日志

### ISSUE THREAD

**Issue by moonService** [apache/streampark#2814]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jdk1.8.0_211-amd64

### Scala Version

2.11.x

### StreamPark Version

1.2.3

### Flink Version

1.13.2

### deploy mode

yarn-application

### What happened

启动日志如下：
`11:06:31.365 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  Starting YarnApplicationClusterEntryPoint (Version: 1.13.2, Scala: 2.11, Rev:5f007ff, Date:2021-07-23T04:35:55+02:00)
11:06:31.365 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  OS current user: yarn
11:06:31.598 [main] DEBUG org.apache.hadoop.security.authentication.util.KerberosName - Kerberos krb5 configuration not found, setting default realm to empty
11:06:31.656 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  Current Hadoop/Kerberos user: root
11:06:31.656 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  JVM: Java HotSpot(TM) 64-Bit Server VM - Oracle Corporation - 1.8/25.211-b12
11:06:31.656 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  Maximum heap size: 429 MiBytes
11:06:31.656 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  JAVA_HOME: /usr/java/jdk1.8.0_211-amd64
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  Hadoop version: 2.7.5
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -  JVM Options:
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -Xmx469762048
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -Xms469762048
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -XX:MaxMetaspaceSize=268435456
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -Dfile.encoding=UTF-8
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -Dlog.file=/data/yarn/container-logs/application_1686972607801_0069/container_e10_1686972607801_0069_01_000002/jobmanager.log
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -Dlog4j.configuration=file:log4j.properties
11:06:31.659 [main] INFO org.apache.flink.runtime.entrypoint.ClusterEntrypoint -     -Dlog4j.configurationFile=file:log4j.properties`
怀疑是没有找到正确的log4j.properties路径，这个路径应该在flink home里面，flink home已经配置了，不知道为什么这里加载不到这个路径，以下是日志中打印的akka配置信息
`11:06:33.159 [main] DEBUG org.apache.flink.runtime.rpc.akka.AkkaRpcServiceUtils - Using akka configuration
 Config(SimpleConfigObject({"akka":{"actor":{"default-dispatcher":{"executor":"thread-pool-executor","thread-pool-executor":{"core-pool-size-max":1,"core-pool-size-min":1},"thread-priority":1,"throughput":15,"type":"akka.dispatch.PriorityThreadsDispatcher"},"guardian-supervisor-strategy":"org.apache.flink.runtime.akka.EscalatingSupervisorStrategy","provider":"akka.remote.RemoteActorRefProvider","supervisor-dispatcher":{"executor":"thread-pool-executor","thread-pool-executor":{"core-pool-size-max":1,"core-pool-size-min":1},"type":"Dispatcher"},"warn-about-java-serializer-usage":"off"},"daemonic":"off","jvm-exit-on-fatal-error":"on","log-config-on-start":"off","log-dead-letters":"off","log-dead-letters-during-shutdown":"off","logger-startup-timeout":"30s","loggers":["akka.event.slf4j.Slf4jLogger"],"logging-filter":"akka.event.slf4j.Slf4jLoggingFilter","loglevel":"DEBUG","remote":{"log-remote-lifecycle-events":"off","netty":{"tcp":{"bind-hostname":"0.0.0.0","bind-port":0,"client-socket-worker-pool":{"pool-size-factor":1,"pool-size-max":2,"pool-size-min":1},"connection-timeout":"20000ms","hostname":"prod-hadoop2","maximum-frame-size":"10485760b","port":0,"server-socket-worker-pool":{"pool-size-factor":1,"pool-size-max":2,"pool-size-min":1},"tcp-nodelay":"on","transport-class":"akka.remote.transport.netty.NettyTransport"}},"retry-gate-closed-for":"50 ms","startup-timeout":"100000ms","transport-failure-detector":{"acceptable-heartbeat-pause":"6000 s","heartbeat-interval":"1000 s","threshold":300}},"serialize-messages":"off","stdout-loglevel":"OFF"}}))`

### Error Exception

```log
一直打印akka的debug日志
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by rcf666** [comment]
排掉这些依赖应该就可以了
streampark-flink/streampark-flink-sqlclient/pom.xml
`<dependency>
            <groupId>org.apache.streampark</groupId>
            <artifactId>streampark-flink-core_${scala.binary.version}</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-access</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>logback-classic</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by wolfboys** [comment]
fixed in new version
