### ISSUE TITLE
[Bug] jar version numbers in bin distribution license do not match the jars in the tar.gz

### ISSUE THREAD

**Issue by pjfanning** [apache/streampark#2815]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

n/a

### Scala Version

2.11.x

### StreamPark Version

https://dist.apache.org/repos/dist/dev/incubator/streampark/2.1.1-RC1

### Flink Version

n/a

### deploy mode

None

### What happened

https://github.com/apache/incubator-streampark/blob/dev/dist-material/release-docs/LICENSE#L208 -- all the jackson jars in https://dist.apache.org/repos/dist/dev/incubator/streampark/2.1.1-RC1/ bin tgz files are v2.13.5.

Can you update the license so that the version numbers are correct

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
hi PJ,
Thanks very much for your careful review work. We will fix this issue soon.
