### ISSUE TITLE
[Bug] 链接失效

### ISSUE THREAD

**Issue by climberCN** [apache/streampark#2831]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.1.1

### Flink Version

1.14.0

### deploy mode

None

### What happened

官方文档：Docker快速使用教程  
[沿用已有的 Mysql 服务]：https://raw.githubusercontent.com/apache/incubator-streampark/dev/deploy/docker/mysql/.env
此链接失效
[沿用已有的 Pgsql 服务]：https://raw.githubusercontent.com/apache/incubator-streampark/dev/deploy/docker/pgsql/.env
此链接失效

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by climberCN** [comment]
文档地址：https://streampark.apache.org/docs/user-guide/docker-deployment

**Comment by we39** [comment]
> 文档地址：https://streampark.apache.org/docs/user-guide/docker-deployment

# 文档中以下链接失效
# Mysql
![image](https://github.com/apache/incubator-streampark/assets/74486614/0004d55a-856a-41e7-8cfc-86c50cd33997)

![image](https://github.com/apache/incubator-streampark/assets/74486614/92c171f6-cdcf-46f8-8e4e-b89160246502)
# Pgsql
![image](https://github.com/apache/incubator-streampark/assets/74486614/fb260c95-eed0-427e-a481-0b8c4019ec8c)

![image](https://github.com/apache/incubator-streampark/assets/74486614/8a703847-b91c-4cf5-bb6f-dd4df4106f63)
