### ISSUE TITLE
[improvement] improvement flink cluster status update

### ISSUE THREAD

**Issue by xujiangfeng001** [apache/streampark#2851]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Based on this pr https://github.com/apache/incubator-streampark/issues/2498. In order to better adapt to `yarn state`, the `Flink cluster` is optimized here as follows:
 
yarn session:

![Yarn Session-Flink Cluster 状态梳理](https://github.com/apache/incubator-streampark/assets/104614523/adb87c67-1e05-4d35-bf5d-d3d44e1c8871)

remote:

![Remote-Flink Cluster 状态梳理](https://github.com/apache/incubator-streampark/assets/104614523/0909297a-a483-4d1b-88d6-ca980de5d0f7)

### Usage Scenario

Optimize `flink cluster` state update.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good job, looking forward to this PR.
