### ISSUE TITLE
[improvement] minor improvement about support for ARM64 architecture execution. 

### ISSUE THREAD

**Issue by onlyotdn** [apache/streampark#2853]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The current value of ThreadStackSize in the startup script is set to 512k. On ARM architecture, such as Apple M series chips, the JVM virtual machine requires a minimum of 640k. When running, the following error is encountered.

```
The stack size specified is too small, Specify at least 640k
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Usage Scenario

Running Streampark on a machine with ARM architecture.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
I have encountered this problem too. Looking forward to you fix it.
