### ISSUE TITLE
[Bug] Bug flink使用1.17.1版本的execution.savepoint-restore-mode选择NO_CLAIM会导致streampark内savepoint失效

### ISSUE THREAD

**Issue by Fu012345** [apache/streampark#2870]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.1.0

### Flink Version

1.17.1

### deploy mode

kubernetes-application

### What happened

flink使用1.17.1版本的execution.savepoint-restore-mode选择NO_CLAIM会导致streampark内savepoint失效

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhoulii** [comment]
Hi @Fu012345, Thanks for your report .  I tested with the latest code and cannot reproduce this issue. Actually, the default value of `execution.savepoint-restore-mode` is `NO_CLAIM`, it should not affect the savepoint file. 

But if the value is set as `CLAIM`, flink will delete the savepoint when restored.

**Comment by wolfboys** [comment]
supported, #2782
