### ISSUE TITLE
[Bug] Unable to correctly verify the Flink cluster URL

### ISSUE THREAD

**Issue by Gooch0922** [apache/streampark#2876]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.14.5

### deploy mode

remote

### What happened

When creating a new Flink cluster, if an incorrect cluster URL is entered, it can also pass the verification. Here is an example of a correct URL demonstration and two error demonstrations:
![image](https://github.com/apache/incubator-streampark/assets/41831810/469deb81-2373-447e-860a-7ef539271715)
When an incorrect cluster is configured, it can cause trouble for future use.

### Error Exception

```log
no exception
```

### Screenshots

as above

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed in new version
