### ISSUE TITLE
flink on k8s 服务用clusterId。Flink WebUI地址不对。

### ISSUE THREAD

**Issue by gaozhan333** [apache/streampark#2927]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.10

### Flink Version

1.16

### deploy mode

kubernetes-application

### What happened

flink  on k8s 

1. 服务用 clusterId .
2. 配置k8s Ingress 配置的地址 

启动的时候。点击项目-> 转的地址不是：https://[Ingress domain address]/[namespame]/[K8S ClusterId]/

![微信图片_20230807140854](https://github.com/apache/incubator-streampark/assets/141609811/f5a14993-f2d7-4555-9463-0899cd0953d9)

真是的地址应该是：https://Ingress domain address/[namespame]/[K8S ClusterId]/

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaozhan333** [comment]
![微信图片_20230807140854](https://github.com/apache/incubator-streampark/assets/141609811/50768862-e225-4a45-b465-795df02ca9c6)

**Comment by gaozhan333** [comment]
![微信图片_20230807142401](https://github.com/apache/incubator-streampark/assets/141609811/be307139-6684-4c0a-ba79-2b919b652d27)

**Comment by chenshaojin** [comment]
I encountered the same problem, because the code saved the service address to the database instead of the ingress proxy address. I will submit a PR to fix this later.

**Comment by wolfboys** [comment]
We only accept English request
