### ISSUE TITLE
[Bug] 无法删除flink项目任务

### ISSUE THREAD

**Issue by lawrence191** [apache/streampark#2935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jdk 1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.14.5

### deploy mode

kubernetes-session

### What happened

在web页面，任务一直显示“SILENT”中，无法进行任务的删除。
![image](https://github.com/apache/incubator-streampark/assets/15275116/81fe7bbb-10c5-435f-8797-4ba2615170f3)
任务在对应的seesion也没运行。
在数据表t_flink_project也删除了。页面也还是可以刷新出来。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
We only accept request in English
