### ISSUE TITLE
[Bug]  The main method caused an error: UpsertStreamTableSink requires that Table has a full primary keys if it is updated.

### ISSUE THREAD

**Issue by SkylerZhan** [apache/streampark#2949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java 1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.0

### Flink Version

flink 1.14.4-2.12

### deploy mode

yarn-application

### What happened

Running the flink sql task on streampark failed to start, and when I checked the error report, I was prompted ''The main method caused an error: UpsertStreamTableSink requires that Table has a full primary keys if it is updated.'' Search on the search engine, it said flink In 1.11, the definition of the primary key on the Query has been cancelled. You can define the primary key when creating the table. When creating the sink, you must also define the primary keys. After adding the parameter NOT ENFORCED, such errors will not be reported. My version is already flink1.14.4, and the primary key and NOT ENFORCED are also defined

在streampark上跑flink sql 任务,启动失败,查看报错,提示 ''The main method caused an error: UpsertStreamTableSink requires that Table has a full primary keys if it is updated.'' 在搜索引擎上搜索,上面说要flink 1.11上取消了Query上定义主键,在建表的时候定义主键即可,在建立sink时,也要定义primary keys 后面要加 NOT ENFORCED 这个参数就不会报此类错误。我的已经是flink1.14.4版本, 也定义了主键和NOT ENFORCED

### Error Exception

```log
The main method caused an error: UpsertStreamTableSink requires that Table has a full primary keys if it is updated
```

### Screenshots

![图片](https://github.com/apache/incubator-streampark/assets/96329691/d4d58776-bcd6-4aaf-9f43-c547e3dfe0e1)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback. It is an error with your flink SQL itself. If you have any issues related to StreamPark, please 
 feedback.

**Comment by SkylerZhan** [comment]
But tasks can be run on StreamX.
&nbsp;


kiritozhan
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月22日(星期二) 上午10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/incubator-streampark] [Bug]  The main method caused an error: UpsertStreamTableSink requires that Table has a full primary keys if it is updated. (Issue #2949)





 
Thanks for your feedback. It is an error with your flink SQL itself. If you have any issues related to StreamPark, please
 feedback.
