### ISSUE TITLE
[Bug] An error is reported when the source code is compiled

### ISSUE THREAD

**Issue by caicancai** [apache/streampark#2960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8/1.11

### Scala Version

2.12.x

### StreamPark Version

dev

### Flink Version

1.16

### deploy mode

None

### What happened

An error is reported when the source code is compiled

### Screenshots

![fa5c1858d8958d2f6b048257aa4e536](https://github.com/apache/incubator-streampark/assets/77189278/f32cf569-5044-47cd-9d87-09cdd7f557b1)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@wolfboys this

**Comment by VampireAchao** [comment]
I also encountered the same problem

**Comment by wolfboys** [comment]
I suspect it is related to the environment settings of Idea, and I haven't found a solution either.

**Comment by caicancai** [comment]
Looks like a sporadic problem, I'm rebooting now and it's fine again, but it feels like it's best to find out why, I have time to re-pull the code and test it separately for windows and linux

**Comment by ligenhw** [comment]
I have the same problem , too.
![image](https://github.com/apache/incubator-streampark/assets/7815460/309cc9ae-465d-4078-bef2-5c8208d3c873)

**Comment by caicancai** [comment]
@wolfboys 
As long as you annotate the buildApplication function in ApplicationBuildPipelineController, this error will not be reported, but I don’t know why. ApplicationController probably needs to annotate a function for the same reason, but I don’t know if this will affect the operation of the entire project. Influence

**Comment by caicancai** [comment]
Seems to be an occasional bug

**Comment by caicancai** [comment]
@ligenhw At present, you can comment these two files to compile, then uncomment and compile again.You can try it.

**Comment by caicancai** [comment]
I close this issue.For details, please see https://github.com/apache/incubator-streampark/issues/507
