### ISSUE TITLE
[Proposal] Upgrade Java version to 11

### ISSUE THREAD

**Issue by Al-assad** [apache/streampark#2961]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The current Java version of StreamPark is still 1.8, but Java 11 has become the mainstream version of Java. Many new versions of Java ecosystem libraries are compiled based on Java 11, including Flink and Spark, which have provided support for Java 11 early on.

StreamPark's upgrade to Java 11 is considered from the following aspects：

- **Flink**： Flink supports Java 11 starting from version 1.10, refer to [FLINK-10725](https://issues.apache.org/jira/browse/FLINK-10725)
- **Spark**： Spark 2.4.x and 3.x uses Scala version 2.12, so Java 11 will work with that version.
- **Streampark itself**：
	The Java code of StreamPark can be compiled successfully in Java 11, and the Scala code based on Scala 2.12 which naturally supports Java 11.
	Due to the extensive use of SPI and reflection mechanisms within StreamPark, it may be necessary to add additional JVM parameter `--add-opens`  in the program startup script to eliminate unsafe reflection warnings.

### Reference
[[Discussion] Upgrading JDK to 11 and removing support for Scala 2.11](https://lists.apache.org/thread/mx8vgq4jp8dk2wgm8m5g1mmq806wzjzg)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
+1, The topic of upgrading JDK has been discussed several times, and it is time to start this plan.

**Comment by wolfboys** [comment]
good job, I think we can vote in the mail list to better drive this proposal.

**Comment by caicancai** [comment]
After upgrading java 11, you can consider upgrading scala to scala2.13

**Comment by caicancai** [comment]
close ...
For details, please see : https://lists.apache.org/thread/mx8vgq4jp8dk2wgm8m5g1mmq806wzjzg
