### ISSUE TITLE
flink都不用scala了，这个项目还是scala，快用java重构吧

### ISSUE THREAD

**Issue by Cqz666** [apache/streampark#2968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

RT

### Flink Version

RT

### deploy mode

None

### What happened

RT

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your suggestion. More questions can be discussed via out email list.
