### ISSUE TITLE
[Improve] Using code style & quality rules to improve org.apache.streampark.common.enums  package of streampark-common module.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#2991]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Described in the title( or other more detailed description info) 

### Related issues

https://github.com/apache/incubator-streampark/issues/2986  

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VampireAchao** [comment]
Please assign me
