### ISSUE TITLE
[Improve] Using code style & quality rules to improve org.apache.streampark.console.base.config package of streampark-console module.

### ISSUE THREAD

**Issue by eagleli123** [apache/streampark#2992]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Described in the title

### Related issues

https://github.com/apache/incubator-streampark/issues/2986

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eagleli123** [comment]
@RocMarshal

**Comment by RocMarshal** [comment]
Hi, @eaglelihh Thanks for the ping & looking forward to your contribution~ :)
