### ISSUE TITLE
[Improve] Using code style & quality rules to improve org.apache.streampark.console.core package of streampark-console module.

### ISSUE THREAD

**Issue by wuchunfu** [apache/streampark#2993]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Using code style & quality rules to improve `org.apache.streampark.console.core` package of `streampark-console module`.

### Related issues

https://github.com/apache/incubator-streampark/issues/2986

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Hi, @wuchunfu thanks for your driving and glad to get your attention~
You can pick any sub-package  in the rest of children packages of `org.apache.streampark.console.base.config`. Becuase
the task of sub-package `org.apache.streampark.console.base.config` of `org.apache.streampark.console.base` had been assigned to a developer. 
Looking forward to your contribution~ :)

**Comment by wuchunfu** [comment]
Hi, @RocMarshal  , Thank you for your reminder, then I will choose the `org.apache.streampark.console.core` module, please @RocMarshal  assign this module to me, thank you

**Comment by RocMarshal** [comment]
Hi, @wuchunfu Thanks a lot for the ping.

I paste the pr link back to the `org.apache.streampark.console.core` package items in parent issue page.

Please follow the granularity-subtask to advance its~
Thank you very much.

- [ ] org.apache.streampark.console.core.annotation
- [ ] org.apache.streampark.console.core.aspect
- [ ] org.apache.streampark.console.core.bean
- [ ] org.apache.streampark.console.core.controller
   Note: do not modify the interfaces definition.
- [ ] org.apache.streampark.console.core.entity
- [ ] org.apache.streampark.console.core.enums
- [ ] org.apache.streampark.console.core.mapper
- [ ] org.apache.streampark.console.core.metrics.flink
- [ ] org.apache.streampark.console.core.metrics.yarn
- [ ] org.apache.streampark.console.core.runner
- [ ] org.apache.streampark.console.core.service.alert.impl
- [ ] org.apache.streampark.console.core.service.alert
- [ ] org.apache.streampark.console.core.service
    **exclude** children packages.   
    do not modify Application service & corresponding impls  
- [ ] org.apache.streampark.console.core.task
- [ ] org.apache.streampark.console.core.utils
- [ ] org.apache.streampark.console.core.websocket

**Comment by RocMarshal** [comment]
> Hi, @wuchunfu Thanks a lot for the ping.
> 
> I paste the pr link back to the `org.apache.streampark.console.core` package items in parent issue page.
> 
> Please follow the granularity-subtask to advance its~ Thank you very much.
> 
> * [ ]  org.apache.streampark.console.core.annotation
> * [ ]  org.apache.streampark.console.core.aspect
> * [ ]  org.apache.streampark.console.core.bean
> * [ ]  org.apache.streampark.console.core.controller
>   Note: do not modify the interfaces definition.
> * [ ]  org.apache.streampark.console.core.entity
> * [ ]  org.apache.streampark.console.core.enums
> * [ ]  org.apache.streampark.console.core.mapper
> * [ ]  org.apache.streampark.console.core.metrics.flink
> * [ ]  org.apache.streampark.console.core.metrics.yarn
> * [ ]  org.apache.streampark.console.core.runner
> * [ ]  org.apache.streampark.console.core.service.alert.impl
> * [ ]  org.apache.streampark.console.core.service.alert
> * [ ]  org.apache.streampark.console.core.service
>   **exclude** children packages.
>   do not modify Application service & corresponding impls
> * [ ]  org.apache.streampark.console.core.task
> * [ ]  org.apache.streampark.console.core.utils
> * [ ]  org.apache.streampark.console.core.websocket

The preview subtasks is deprecated. Please see https://github.com/apache/incubator-streampark/issues/2986 for more details about change and adjust the current issue title.

**Comment by wolfboys** [comment]
done
