### ISSUE TITLE
[Bug] get error when verify sql statement

### ISSUE THREAD

**Issue by cygnusdark** [apache/streampark#3005]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.2.0

### Flink Version

1.17

### deploy mode

yarn-application

### What happened

get error when verify sql statement for multiple sink;

```
CREATE TABLE students (name STRING, age INT, gpa DECIMAL(3, 2)) WITH (...);

EXECUTE STATEMENT SET;
BEGIN;
INSERT INTO students
  VALUES ('fred flintstone', 35, 1.28), ('barney rubble', 32, 2.32);
INSERT INTO students
  VALUES ('fred flintstone', 35, 1.28), ('barney rubble', 32, 2.32);
END;
```

### Screenshots

<img width="1201" alt="image" src="https://github.com/apache/incubator-streampark/assets/53288632/d8821777-ef37-4ec1-a346-8150042103a7">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cygnusdark** [comment]
Update: I resolved this problem by creating a temporary view.

**Comment by jkl0898** [comment]
> Update: I resolved this problem by creating a temporary view.

Hello. I had encountered a similar problem before, how did you solve it in detail? Thanks！

**Comment by rea1shane** [comment]
> > Update: I resolved this problem by creating a temporary view.
> 
> Hello. I had encountered a similar problem before, how did you solve it in detail? Thanks！

Delete `BEGIN STATEMENT SET ... END;`.

See #2201 .
