### ISSUE TITLE
[Improve] Introduce a utils to process conditions check and exceptions thrown.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3007]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 Introduce a premise utils to reduce conditions check and exceptions processing.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
Hi, @RocMarshal please assign this issues to me

**Comment by RocMarshal** [comment]
The `AssertUtils` was introduced to solve the issue.
