### ISSUE TITLE
[Bug] website community i18n not work

### ISSUE THREAD

**Issue by VampireAchao** [apache/streampark#3018]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

-

### Scala Version

2.11.x

### StreamPark Version

-

### Flink Version

-

### deploy mode

None

### What happened

has a translated document,but not work

<img width="1728" alt="image" src="https://github.com/apache/incubator-streampark/assets/52746628/00d1a81c-4d6c-4e05-9106-f5dd37c14711">

<img width="1728" alt="image" src="https://github.com/apache/incubator-streampark/assets/52746628/8b341c0c-ecbf-40e1-9ffa-e1095072b76e">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Thanks to your help, the internationalization of the official online community module has been fixed! 
For details, check out： https://github.com/apache/incubator-streampark-website/pull/231
