### ISSUE TITLE
[Deprecated] [Improve] Using code style & quality rules to improve org.apache.streampark.console.base.util package of streampark-console module.

### ISSUE THREAD

**Issue by VampireAchao** [apache/streampark#3026]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Using code style & quality rules to improve org.apache.streampark.console.base.util package of streampark-console module.

### Related issues

https://github.com/apache/incubator-streampark/issues/2986

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VampireAchao** [comment]
@wolfboys @RocMarshal Roc Request for assignment.

**Comment by RocMarshal** [comment]
Please see https://github.com/apache/incubator-streampark/issues/2986 for more details about change and adjust the current issue title.

**Comment by VampireAchao** [comment]
This issue was deprecated.
