### ISSUE TITLE
[Bug][Get Yarn Proxy] delete result data value '/cluster/app' 

### ISSUE THREAD

**Issue by sdhzwc** [apache/streampark#3030]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java version 1.8.0_321

### Scala Version

2.11.x

### StreamPark Version

apache-streampark_2.11-2.1.1

### Flink Version

flink-1.14.6

### deploy mode

yarn-application

### What happened

Version 2.1.1 has the following issues:
Backend:
1. Get Yarn proxy has added '/cluster/app', resulting in a failed redirect
Front end:
1. The documentation page has been written dead on port 10000, causing API documents to fail to jump. Currently, dev has fixed this issue
2. Directly using 'record. yarnAppId' in the Operation Log results in the use of a local port without using the Yarn proxy, and it is also unable to jump. Currently, dev has fixed this issue
I want to fix the above issue based on 2.1.1, but it cannot be submitted at present. Therefore, I fixed the issue of obtaining Yarn proxy based on dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
