### ISSUE TITLE
[Improve] Improve streampark-common module base on 3.1 Naming Style

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3044]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Improve streampark-common module base on [3.1 Naming Style](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#31-naming-style)

### Related issues

#2986 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kick156** [comment]
I would like to try to do it, can it be assigned to me.@RocMarshal
