### ISSUE TITLE
[Improve] Improve streampark-common module base on 3.2 Constant Variables Definition

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3045]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Improve streampark-common module base on [3.2 Constant Variables Definition](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#32-constant-variables-definition)

### Related issues

#2986 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jaslou** [comment]
I would like to try to do it, can it be assigned to me.@RocMarshal

**Comment by jaslou** [comment]
This improve issue seems to have been completed.

**Comment by RocMarshal** [comment]
thx @jaslou for the checking.
Closing...
