### ISSUE TITLE
[Improve] Improve streampark-common module base on 3.3 Methods Rule

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3046]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Improve streampark-common module base on [3.3 Methods Rule](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#33-methods-rule)

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
@RocMarshal  hi, i want to try this!

**Comment by RocMarshal** [comment]
Thanks for  @zzzk1 your attention, assigned!
