### ISSUE TITLE
[Feature] Hope to support Kubernetes multi-clustering

### ISSUE THREAD

**Issue by xiaohei88** [apache/streampark#3050]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

https://github.com/apache/incubator-streampark/issues/2383
https://github.com/apache/incubator-streampark/issues/1747

Hello, are there any plans to support multiple k8s clusters? There is a strong demand for this feature. I have seen someone mention it before, but there has been no response.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yangrong688** [comment]
+1

**Comment by wolfboys** [comment]
There are no current plans, please stay tuned for community updates.
