### ISSUE TITLE
[Improve] Improve `streampark-common` module base on [3.8 Java Lambdas]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3058]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Improve `streampark-common` module base on [3.8 Java Lambdas](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#38-java-lambdas)

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lukeyan2023** [comment]
I would like to try to do it, can it be assigned to me.@RocMarshal

**Comment by GOODBOY008** [comment]
@lukeyan2023 Assigned.

**Comment by zhengkezhou1** [comment]
@RocMarshal pls assigned this issues to me

**Comment by RocMarshal** [comment]
hi, @lukeyan2023 any progress here?

**Comment by RocMarshal** [comment]
N.A(checked)
