### ISSUE TITLE
[Improve] Improve `streampark-console` module base on [3.8 Java Lambdas]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3071]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-console` module base on [3.8 Java Lambdas](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#38-java-lambdas)

### Related issues

#2986 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuxiaotuan** [comment]
Please assign the current issue to me.

**Comment by Xuxiaotuan** [comment]
Hello, I have been looking for a long time in the project（streampark-console）, but I have not found any similar areas that need to be optimized

**Comment by caicancai** [comment]
cc @RocMarshal Excuse me, if you have time to take a look, thank you

**Comment by RocMarshal** [comment]
Thanks @Xuxiaotuan  for your hard work 
Closing the issue now~
CC @caicancai
