### ISSUE TITLE
[Improve] Improve `streampark-console` module base on [3.9 Java Streams]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3072]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-console` module base on [3.9 Java Streams](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#39-java-streams)

### Related issues

#2986 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuxiaotuan** [comment]
Please assign the current issue to me.

**Comment by Xuxiaotuan** [comment]
Hello, according to this requirement, I checked the code of streampark-console, streampark-console belongs to business code, and there is no scenario that requires a lot of calculation. There was no improper use of Java Streams

3.9 Java Streams
Avoid Java Streams in any performance critical code.

The main motivation to use Java Streams would be to improve code readability. As such, they can be a good match in parts of the code that are not data-intensive, but deal with coordination.

Even in the latter case, try to limit the scope to a method, or a few private methods within an internal class.

**Comment by RocMarshal** [comment]
Thank you @Xuxiaotuan  very much for your effort on the issue. 
Closing the issue now~
