### ISSUE TITLE
[Improve] Improve `streampark-console` module base on [3.10 Pre-Conditions Checking]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3073]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-console` module base on [3.10 Pre-Conditions Checking](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#310-pre-conditions-checking)

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jaslou** [comment]
I would like to try to do it, can it be assigned to me.@RocMarshal

**Comment by zhengkezhou1** [comment]
@RocMarshal  pls assigned this issues to me

**Comment by RocMarshal** [comment]
hi, @jaslou Just be curious about the progress,  any progress here?

**Comment by jaslou** [comment]
@RocMarshal pls assigned to zzzk1, thx!

**Comment by zhengkezhou1** [comment]
*hi,@RocMarshal It looks like this issue can be resolved in* #3513

**Comment by RocMarshal** [comment]
https://github.com/apache/incubator-streampark/issues/3007
