### ISSUE TITLE
源码编译失败- Failed to run task: 'pnpm run build:no-cache'

### ISSUE THREAD

**Issue by jkl0898** [apache/streampark#3081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

open-jdk1.8

### Scala Version

2.12.x

### StreamPark Version

release-2.1.1

### Flink Version

release-2.1.1 分支默认版本

### deploy mode

None

### What happened

none

### Error Exception

```log
[INFO] StreamPark : Console Parent 2.1.1 .................. SUCCESS [  0.113 s]
[INFO] StreamPark : Console Service 2.1.1 ................. FAILURE [ 36.216 s]
[INFO] StreamPark : Spark Parent 2.1.1 .................... SKIPPED
[INFO] StreamPark : Spark Core 2.1.1 ...................... SKIPPED
[INFO] StreamPark : Spark Connector 2.1.1 ................. SKIPPED
[INFO] StreamPark : Spark Connector Base 2.1.1 ............ SKIPPED
[INFO] StreamPark : Spark Connector Kafka 2.1.1 ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  08:37 min
[INFO] Finished at: 2023-09-14T17:42:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:pnpm (build) on project streampark-console-service: Failed to run task: 'pnpm run build:no-cache' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :streampark-console-service
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Thank you for your feedback. According to the screenshot, the branch you are currently using is 2.1.1, you can try to modify the package.json script under the streampark-console/streampark-console-webapp/ module, and change the "build": "cross-env NODE_ENV=production vite build && esno ./build/script/postBuild.ts", to "build": "vite build && esno ./build/script/postBuild.ts", and Deleting the node_modules directory and trying to recompile will hopefully resolve your issue. If that doesn't solve the problem, we'll close this issue a bit later.

path: streampark-console/streampark-console-webapp/package.json

before:

```shell
 "build": "cross-env NODE_ENV=production vite build && esno ./build/script/postBuild.ts",
```
after
```
 "build": "vite build && esno ./build/script/postBuild.ts",
```

**Comment by hackallan** [comment]
> o

not found  "build": "cross-env NODE_ENV=production vite build && esno ./build/script/postBuild.ts" in package.json

**Comment by hackallan** [comment]
"build": "cross-env NODE_ENV=production vite build && esno ./build/script/postBuild.ts"  doesn't work

**Comment by hackallan** [comment]
I use version 2.1.1 and modify  "build": "vite build && esno ./build/script/postBuild.ts", but doesn't work,also has the same build error

**Comment by hackallan** [comment]
> I use version 2.1.1 and modify "build": "vite build && esno ./build/script/postBuild.ts", but doesn't work,also has the same build error

**Comment by wangsizhu0504** [comment]
> > I use version 2.1.1 and modify "build": "vite build && esno ./build/script/postBuild.ts", but doesn't work,also has the same build error

You execute `npm run build` in the webapp directory and send the error log

**Comment by tuoluzhe8521** [comment]
i have the same problems when i compile 2.1.2rc3,but there  is no "build": "cross-env NODE_ENV=production vite build && esno ./build/script/postBuild.ts",

**Comment by tuoluzhe8521** [comment]
i save this problem by install npm. i don't have npm in my mac.
brew install node
