### ISSUE TITLE
[Improve] Improve `streampark-flink` module based on [3.3 Methods Rule]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3084]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-flink` module based on [3.3 Methods Rule](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#33-methods-rule)

### Related issues

#2986 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
i pick it

**Comment by Xuxiaotuan** [comment]
I'd like to try it. Can you assign it to me

**Comment by RocMarshal** [comment]
Excuse me , @Xuxiaotuan any progress here ?

**Comment by Xuxiaotuan** [comment]
> Excuse me , @Xuxiaotuan any progress here ?

Sorry for the delay. I'll just follow up

**Comment by caicancai** [comment]
@RocMarshal I think this issue can be closed

**Comment by RocMarshal** [comment]
thx @Xuxiaotuan @caicancai for the checking.
