### ISSUE TITLE
[Improve] Improve `streampark-flink` module based on [3.8 Java Lambdas]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3089]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-flink` module based on [3.8 Java Lambdas](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#38-java-lambdas)

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
i pick it

**Comment by caicancai** [comment]
@RocMarshal stremaprk-flink is scala code and does not apply to this rule. Please apply to close this issue

**Comment by RocMarshal** [comment]
thx ~ @caicancai 

closing now...
