### ISSUE TITLE
[Improve] Improve `streampark-flink` module based on [3.10 Pre-Conditions Checking]

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3091]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Improve] Improve `streampark-flink` module based on [3.10 Pre-Conditions Checking](https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide#310-pre-conditions-checking)

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
i pick it

**Comment by Xuxiaotuan** [comment]
I'd like to try it. Can you assign it to me

**Comment by RocMarshal** [comment]
Excuse me , @Xuxiaotuan any progress here ?

**Comment by Xuxiaotuan** [comment]
> Excuse me , @Xuxiaotuan any progress here ?

Sorry for the delay. I'll just follow up

**Comment by Xuxiaotuan** [comment]
**The previous rule was:**

 3.10 Pre-Conditions Checking
Use a unified Utils.requireXXX to complete the validation of the prerequisite, and if possible, replace the AlertXXException.throwIfXXX by new pre-conditions checking.

But now This method is not used as a handling point for global exceptions
![image](https://github.com/apache/incubator-streampark/assets/29968120/38e5f7c1-dcdf-493d-9d4a-d467a1a1fd7c)

How do we deal with this now?
@RocMarshal

**Comment by Xuxiaotuan** [comment]
Use a unified AssertUtils.require() to complete the validation of the prerequisite
