### ISSUE TITLE
[Improve] Unified enumeration comparison methods

### ISSUE THREAD

**Issue by wuchunfu** [apache/streampark#3129]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

**Project requirements:**
I checked that some of the comparison methods of the enumeration methods in the project are `==` and some are `equals`. I think we want to unify it into one comparison method and use `==` to compare whether two enumeration values are equal.

**Desired result:**
All enumeration values in the entire project are compared using `==`.

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuxiaotuan** [comment]
I would like to try to do it, can it be assigned to me.

**Comment by RocMarshal** [comment]
Thanks @wuchunfu for driving it and @Xuxiaotuan for the ping.
Assigned~
