### ISSUE TITLE
[Cleanup] Remove the redundant `Serializable` implementation for all Enums of the project.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3131]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Cleanup] Remove the redundant `Serializable` implementation for all Enums of the project.

<img width="756" alt="image" src="https://github.com/apache/incubator-streampark/assets/64569824/f0ee91f6-c71a-4dc5-b426-0503d7931b04">

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
i pick it

**Comment by xsymin** [comment]
Please assign the current issue to me.

**Comment by ligenhw** [comment]
i had submit a pr to fix it. please assign this issue to me.
