### ISSUE TITLE
[Cleanup] Remove the  package `org.apache.streampark.common.tuple` of `streampark-common` module.

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3132]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

[Cleanup] Remove the  package `org.apache.streampark.common.tuple` of `streampark-common` module.

Replace the old `tuplexx` with the `tuplexx` from `flink-core` dependency.

### Related issues

#2986 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ligenhw** [comment]
i had submit a pr to fix it. please assign this issue to me.
