### ISSUE TITLE
[Improve] Unified Naming Rules for Enumeration Classes

### ISSUE THREAD

**Issue by wuchunfu** [apache/streampark#3133]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

**Reference**

The enumeration class name must be suffixed with `Enum`. Enumeration member names must be in all uppercase letters, and words must be separated by underscores.

**Note**

Enumerations are actually special constant classes, and the constructor is forced to be private by default.

**Positive example**

The member name of the enumeration named `ProcessStatusEnum`: `SUCCESS / UNKNOWN_REASON`

### Related issues

#2986

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
Hi, @xsymin Would you like to get the task ? :)

**Comment by xsymin** [comment]
> 你好，@xsymin你想接任务吗？:)

Sure, I'm up for it.

**Comment by RocMarshal** [comment]
@xsymin nice~, Assigned.
Looking forward to the pr~
