### ISSUE TITLE
[Bug] Streampark flink Application status is in inconsistent with Flink web ui.

### ISSUE THREAD

**Issue by jkl0898** [apache/streampark#3138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jdk1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

13.1.1

### deploy mode

remote

### What happened

Strampark flink applicaiton status is inconsistent with the flink web ui . Flink web ui application got a exception and the status is change to restarting ， but the streampark flink application status is still running. 

Streampark 控制台flink application 的状态和 Flink web ui 控制台的任务状态不一致.  flink 应用出现异常后， Flink 控制台的状态转化为restarting ， 但是 streampark 控制台的flink 应用状态仍然为running.

如下图所示：

<img width="1248" alt="image" src="https://github.com/apache/incubator-streampark/assets/14175165/43bd9e37-3614-4944-925d-01bae43d26d6">

<img width="1486" alt="image" src="https://github.com/apache/incubator-streampark/assets/14175165/f3616bff-9050-4b1a-8abc-8f8d6bda8815">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Currently, a REST request is being sent to the Flink WebUI every 5 seconds to retrieve the status of a Flink job. This approach may result in missing some transient job statuses. You can verify if the final status of the job is correct.
