### ISSUE TITLE
[Feature] add contributor documentation to README

### ISSUE THREAD

**Issue by caicancai** [apache/streampark#3146]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

At present, StreamPark does not use contributor documentation, which may make contributors unclear about the Streampark community's PR specifications

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@wolfboys

**Comment by wolfboys** [comment]
> @wolfboys

There is already a documentation. If there are other rules, We can be further improved.  cc @RocMarshal 

https://streampark.apache.org/community/submit_guide/submit_code
https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide

**Comment by caicancai** [comment]
> > @wolfboys
> 
> There is already a documentation. If there are other rules, We can be further improved. cc @RocMarshal
> 
> https://streampark.apache.org/community/submit_guide/submit_code https://streampark.apache.org/community/submit_guide/code_style_and_quality_guide

Thanks for the reminder, I think it can be updated to Readme to make it easier for users, I found that other projects do this 
cc @RocMarshal
