### ISSUE TITLE
[Bug] Bug title

### ISSUE THREAD

**Issue by fi-ecavc** [apache/streampark#3210]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.17.1

### deploy mode

kubernetes-application

### What happened

The flink-sql editor often shows that the modified content cannot be saved, and the last resort is to rebuild the new job and the modification will take effect.

### Error Exception

```log
cannot be saved,
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
you must release the flinkjob for SQL to take effect
