### ISSUE TITLE
[Feature] when submit application to yarn , use the user logged in to streampark.

### ISSUE THREAD

**Issue by lordk911** [apache/streampark#3222]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

flink-1.17

### deploy mode

yarn-application

### What happened

when submit jar type application to yarn , the user is hadoop-user-name configed in application.yml 
can this use streampark logged in user , or maybe the streampark user could map to a system user?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Currently, hadoop-user is read from application.yml. I guess you need different login users to bind different user identities when submitting jobs, right?

**Comment by lordk911** [comment]
> Currently, hadoop-user is read from application.yml. I guess you need different login users to bind different user identities when submitting jobs, right?

Yes, For one reason, it is for security considerations, and for another reason, from the perspective of operation and maintenance, it can easily differentiate whose task it is through user identification.

**Comment by wolfboys** [comment]
We can support this feature by allowing the specification of hadoop-user in the job when it is running on yarn mode.

**Comment by saLeox** [comment]
@lordk911 Hi, if you have kerberos environment, you can consider to add keytab into your Flink application within streampark, so that your job will be runing on the behalf of the user you sepecify.

**Comment by zhaoyu810373097** [comment]
> 当作业在 yarn 模式下运行时，我们可以通过允许在作业中指定 hadoop-user 来支持此功能。

要如何指定hadoop-user呢？通过哪个配置参数

**Comment by lordk911** [comment]
hi, Is there any draft or progress on resolving this issue？ @wolfboys

**Comment by wolfboys** [comment]
> when submit jar type application to yarn , the user is hadoop-user-name configed in application.yml
> can this use streampark logged in user , or maybe the streampark user could map to a system user?

Thanks for your feedback. We have compiled [tracking issues of StreamPark 2.2.0](#3278)
 Currently, this feature is not included in the plan. After my evaluation, I found that implementing this feature is simple. We just need to add an input for the Hadoop-user in the job definition page and retrieve the specified Hadoop-user when start the job. This is a good first issue, and of course, welcome your contribution and participation. 😊

**Comment by lordk911** [comment]
我在useCreateAndEditSchema.ts里加了一个输入项，在编辑 Application 和新建 Application时，可以看到这个输入项目。
通过浏览器的调试工具可以看到，提交表单时的请求路径是：/flink/app/update，在app.ts可以找到。但是我在后端的代码里，没有看到相关的request mapping。我该怎么把新加的输入项的值保存到数据库？
@wolfboys 能否给些线索

**Comment by lordk911** [comment]
@wolfboys I've made a PR, I'm not familiar with front-end development. And I think the change about YarnApplicationClient is not good , but I don't know how to use ProxyUser.

**Comment by lordk911** [comment]
@wolfboys Is this Feature already supported or any plan about it?
