### ISSUE TITLE
[Bug] [LDAP]If the user does not have any more attributes, they will not be able to log in.

### ISSUE THREAD

**Issue by lordk911** [apache/streampark#3226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.1.1

### Flink Version

1.17

### deploy mode

None

### What happened

I use openldap, by default there are no additional attributes such as mail. In this case, even if the password is correct, you cannot log in unless an additional attribute is added to the corresponding user. When using LDAP for authentication, can we only verify the password?

https://github.com/apache/incubator-streampark/blob/095be65b7ac9ee7c71c4813fbbf0b2fc7b6be422/streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/LdapService.java#L100

The code runs to this point. If there are no additional attributes, the password will not be verified. However, if there are multiple attributes, does it require multiple password verifications?

https://github.com/apache/incubator-streampark/blob/095be65b7ac9ee7c71c4813fbbf0b2fc7b6be422/streampark-console/streampark-console-service/src/main/java/org/apache/streampark/console/system/security/impl/AuthenticatorImpl.java#L80

Email may not be necessary.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can try to set the email attribute and uid to the same settings and use them normally. This is missing in the document. I will fill it in a few days. @lordk911

**Comment by SbloodyS** [comment]
After take a deep look at this issue. I found that the email is not necessary. Would you like to fix it? @lordk911

**Comment by lordk911** [comment]
> After take a deep look at this issue. I found that the email is not necessary. Would you like to fix it? @lordk911

Sorry, I currently can't find time to do this. I have just started understanding this project and haven't set up a local compilation environment yet. Additionally, there are some new tasks that need to be handled at the moment.

**Comment by SbloodyS** [comment]
> Sorry, I currently can't find time to do this. I have just started understanding this project and haven't set up a local compilation environment yet. Additionally, there are some new tasks that need to be handled at the moment.

Okay. I'll fix it.
