### ISSUE TITLE
[Bug] In the K8S session mode, the operating LOG error is displayed as: nosuchmethoderror: IO.Fabric8.kubernetes.client.dsl.networkapigroupdsl.v1()

### ISSUE THREAD

**Issue by shiwendai** [apache/streampark#3230]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.13.6

### deploy mode

kubernetes-session

### What happened

In the K8S session mode, the operating LOG error is displayed as: nosuchmethoderror: IO.Fabric8.kubernetes.client.dsl.networkapigroupdsl.v1 ()

### Error Exception

```log
Caused by: java.lang.NoSuchMethodError: io.Fabric8.kubernetes.client.dsl.networkapigroupdsl.v1()
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/11675050/4068a17e-68f4-4962-81fa-ead4ddbfe0bc)
![image](https://github.com/apache/incubator-streampark/assets/11675050/961533f9-95d6-462e-b054-27a031a800d3)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ryze124** [comment]
how to fix this
