### ISSUE TITLE
[Feature] Translate the k8s blog module of incubator-streampark-website

### ISSUE THREAD

**Issue by caicancai** [apache/streampark#3242]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Translate the blog on the streampark official website into English
https://streampark.apache.org/blog/streampark-flink-on-k8s

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by saLeox** [comment]
Please assign to me, thank you

**Comment by caicancai** [comment]
@saLeox Hello, someone has translated this blog. You can verify the translated content. If there is no problem, you can apply to close this PR.
https://github.com/apache/incubator-streampark-website/pull/278
