### ISSUE TITLE
[Feature] Translate the framework blog module of incubator-streampark-website

### ISSUE THREAD

**Issue by caicancai** [apache/streampark#3243]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Translate the blog on the streampark official website into English
https://streampark.apache.org/blog/flink-development-framework-streampark

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by saLeox** [comment]
Please assign to me, thank you

**Comment by saLeox** [comment]
Please assign to @VampireAchao, and thanks for the contribution.
This blog is translated.
https://github.com/apache/incubator-streampark-website/pull/280

**Comment by VampireAchao** [comment]
Sorry,I missed this issue

**Comment by caicancai** [comment]
@saLeox Hi, you can check the two corresponding blogs. If there is no problem, you can apply to close these two issues. Thank you very much.
