### ISSUE TITLE
[OnlineMeeting&Oct.22] StreamPark community meeting Topic collect

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3262]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

benjobs invites you to a meeting on Tencent Meeting

Meeting Topic: StreamPark Community Meeting
Time: 2023/10/22 20:00-20:30 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/5lEGBTygo5R1

#TencentMeeting：631-7640-9594

Copy this invitation and open in Tencent Meeting app (V3.14 or later) to join the meeting
Everyone is very welcome to join:

If you have an issue, please submit it  before the meeting, and provide a specific issue link and context.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
[StreamPark version release 2.1.2](https://github.com/apache/incubator-streampark/issues/3263)

**Comment by wolfboys** [comment]
#3256

**Comment by VampireAchao** [comment]
https://github.com/apache/incubator-streampark/issues/3064

**Comment by ChengJie1053** [comment]
https://github.com/apache/incubator-streampark/issues/2437
