### ISSUE TITLE
[Feature] the publishing package can be automatically packaged with the latest version snapshot when job republished

### ISSUE THREAD

**Issue by sunnyday-sky** [apache/streampark#3271]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I have a flink sql job depends on a udf package, which is a snapshot version. Whenever I update udf, I have to delete the package in the maven directory under streampark workspace to re-download the latest version. Dependency packages need to be changed before re-publishing, and the publishing package will be re-packaged.

So, I hope if the flink sql job depends on a snapshot package, the publishing package can be automatically packaged with the latest version snapshot when job republished. ( flink sql 模式下，希望作业依赖的SNAPSHOT包更新后，作业重新发布时依赖包可以自动下载和打包最新版本。)

### Usage Scenario

flink sql job depends on a snapshot package

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Currently, When release a flink job, the dependencies of the job are checked to see if there have been any changes. Since your pom hasn't changed, it won't trigger a rebuild of the job. In future versions, we will make an improvement by adding a button that allows users to choose whether to rebuild the job or not.

**Comment by sunnyday-sky** [comment]
OK, Thanks for the explanation.

Another problem on job rebuild is that, when I change my pom twice by removing and adding dependencies which is need to be updated, and trigger a job rebuild, in many cases the latest version of the SNAPSHOT dependency will not necessarily be downloaded to the workspace.

The current discovery is that I updated my udf package twice a day. The new version was successfully downloaded during the first rebuild of the day. However, when the job was rebuilt after the second update, the SNAPSHOT dependency package was not updated to the latest version.

**Comment by wolfboys** [comment]
Answered
