### ISSUE TITLE
[Feature] website Application mamagement page,  add  query by status  condtion  

### ISSUE THREAD

**Issue by zhengyuan-cn** [apache/streampark#3355]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the Streampark website  Application mamagement page,  only display Running Jobs numbers, if you browse special status such as runing, shuld only browse page by page.
so, advice add  query by status  condtion,in this page.
![streamPark-PR](https://github.com/apache/incubator-streampark/assets/6375437/8226be7e-83ae-4219-89b0-760c508ab484)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Thank you for your feedback and look forward to your contribution

**Comment by wolfboys** [comment]
<img width="630" alt="image" src="https://github.com/apache/incubator-streampark/assets/13284744/7ad04a5e-6c70-4d09-a71a-3a14fa750106">
