### ISSUE TITLE
[Bug] findUserPermissions SQL execute bug 

### ISSUE THREAD

**Issue by minchowang** [apache/streampark#3361]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

all

### deploy mode

kubernetes-application

### What happened

After the user login web, the user web Aaert SQL executes an error

### Screenshots

<img width="1688" alt="image" src="https://github.com/apache/incubator-streampark/assets/33626973/c0462872-d854-4ba5-90d5-82d76705c667">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
