### ISSUE TITLE
[Bug] The SQL query was unexpectedly truncated.

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3370]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

all

### Scala Version

2.11.x

### StreamPark Version

latest

### Flink Version

all

### deploy mode

None

### What happened

Entering special characters on the job list page will cause an SQL query error. 

### Screenshots

![111131701440881_ pic](https://github.com/apache/incubator-streampark/assets/13284744/8d88b3b4-304e-4591-b5c0-8a325bc68ee7)

![111151701440881_ pic](https://github.com/apache/incubator-streampark/assets/13284744/b81ccb65-3bd9-41bf-b010-3adf97cc2ac8)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VampireAchao** [comment]
assign me

**Comment by wolfboys** [comment]
> assign me

done
