### ISSUE TITLE
[Bug] Flink SQL在线编辑窗口保存中文字符串后乱码

### ISSUE THREAD

**Issue by 929359291** [apache/streampark#3376]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

11

### Scala Version

2.11.x

### StreamPark Version

2.11

### Flink Version

1.17.1

### deploy mode

remote

### What happened

Flink SQL在线编辑窗口输入中文字符串，提交保存后变成重新打开会变成乱码
提交保存后再编辑
![Dingtalk_before](https://github.com/apache/incubator-streampark/assets/33850806/c6f006c8-e1ef-4bf9-ad52-29fd4fbc3da6)
提交前
![Dingtalk_after](https://github.com/apache/incubator-streampark/assets/33850806/128a3c51-1dec-4720-9f59-c41316f6348d)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 929359291** [comment]
this is issue fixed，vim /etc/locale.conf，update LANG="en_US.UTF-8"  to  LANG="zh_CN.UTF-8"
<img width="260" alt="utf-8" src="https://github.com/apache/incubator-streampark/assets/33850806/548e4719-2417-4b7e-aa3d-255584526303">
source /etc/locale/conf
then restart streampark

**Comment by 929359291** [comment]
success

**Comment by DingPengfei** [comment]
同样的问题，试过上面的方法还是不行
