### ISSUE TITLE
[Bug] yarnUtil restRequest error,illegal character in RM url

### ISSUE THREAD

**Issue by Mortal-dx** [apache/streampark#3379]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.1

### Flink Version

1.16

### deploy mode

yarn-application

### What happened

1、restart hadoop
2、start flink app on streampark
3、streampark  Unable to Capturethe normal state of the application,Actualy app is runing,But on streampark, it shows starting

### Error Exception

```log
yarnUtil restRequest error,illegal character in RM url
```

### Screenshots

![微信图片_20231206201733](https://github.com/apache/incubator-streampark/assets/86011086/18284854-38d0-494d-83f9-841c566766f2)
![微信图片_20231206201741](https://github.com/apache/incubator-streampark/assets/86011086/618a2d7a-c3bc-4437-8511-436a1db5a214)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Looks like a bug. 🐛
