### ISSUE TITLE
[Bug] After k8s submit fail, submit again cause  once submit multi-jobs.

### ISSUE THREAD

**Issue by minchowang** [apache/streampark#3388]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.1.2

### Flink Version

1.16

### deploy mode

kubernetes-application

### What happened

I guess I submit failed, real jobs had been submitted, but streampark did not get the running jobs state.

### Screenshots

<img width="1350" alt="image" src="https://github.com/apache/incubator-streampark/assets/33626973/23435fc3-378c-46e4-809c-185a2f7b0db3">
<img width="1861" alt="image" src="https://github.com/apache/incubator-streampark/assets/33626973/76d669e8-c203-4336-a22a-63adf6acc1e0">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@minchowang Hello, is flink-kubernetes-v2 enabled?

**Comment by minchowang** [comment]
> @minchowang Hello, is flink-kubernetes-v2 enabled?

Currently, I use default mode based on releases-2.1.2.
