### ISSUE TITLE
Internal server error: null

### ISSUE THREAD

**Issue by kaiwangleo** [apache/streampark#3410]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.1.2

### Flink Version

1.16

### deploy mode

kubernetes-application

### What happened

After the version is upgraded to 2.1.2, an internal server error: null is reported for new tasks

### Error Exception

```log
internal server error: null
```

### Screenshots

![企业微信截图_17029513924118](https://github.com/apache/incubator-streampark/assets/44354575/72fbda24-872b-47cb-ac1a-3dfdbaab79f7)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Current feedback information is missing. You can check for more log information in log/streampark.out. 😕
