### ISSUE TITLE
[Bug] Field 'modify_time' doesn't have a default value

### ISSUE THREAD

**Issue by zfzftt** [apache/streampark#3412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.17.1

### deploy mode

yarn-application

### What happened

After upgrading from 2.1.1 to 2.1.2, when I added a new application and submitted it, streampark told me that the field "modify_time" had no default value.
I found that modify_time has a default value in script/schema/mysql-schema.sql, but not in script/upgrade/mysql/2.1.2.sql.

### Error Exception

```log
2023-12-19 13:19:17 | INFO  | XNIO-1 task-6 | org.apache.streampark.console.base.handler.GlobalExceptionHandler:54] Internal server error：
org.springframework.dao.DataIntegrityViolationException: 
### Error updating database.  Cause: java.sql.SQLException: Field 'modify_time' doesn't have a default value
### The error may exist in org/apache/streampark/console/core/mapper/ApplicationMapper.java (best guess)
### The error may involve org.apache.streampark.console.core.mapper.ApplicationMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO t_flink_app  ( team_id, job_type,  user_id, job_name,    version_id,   k8s_namespace, state, `release`, build,   option_state,    options,  resolve_order, execution_mode,  app_type, tracking,                   create_time )  VALUES  ( ?, ?,  ?, ?
,    ?,   ?, ?, ?, ?,   ?,    ?,  ?, ?,  ?, ?,                   ? )
### Cause: java.sql.SQLException: Field 'modify_time' doesn't have a default value
; Field 'modify_time' doesn't have a default value; nested exception is java.sql.SQLException: Field 'modify_time' doesn't have a default value
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed in dev-2.1.3 branch
