### ISSUE TITLE
[Bug] streampark delete k8s deployment when JobManager restart

### ISSUE THREAD

**Issue by zhenyuT** [apache/streampark#3423]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Scala Version

2.12.x

### StreamPark Version

apache-streampark_2.12-2.1.1-incubating

### Flink Version

1.15.3

### deploy mode

kubernetes-application

### What happened

flink on k8s高可用采用zk，通过故障注入工具模拟JobManager访问zk节点超时(网络延时30s，持续120s后恢复)
通过命令行方式启动任务，JobManager会自动restart，网络延时故障结束后任务能自动恢复正常
通过streampark方式启动，JobManager重新启动的时候，突然整个deployment都被remove

查看streampark日志，发现是streampark监听到flink任务fail，触发了delete deployment操作
![1703233420947_125D8297-C2B0-462f-8A04-170833A89075](https://github.com/apache/incubator-streampark/assets/9477681/7a91cc72-a54b-4ca1-8402-c6430f25728b)
![1703233457034_5E41A593-3067-4eb3-A168-2D5A182D96DC](https://github.com/apache/incubator-streampark/assets/9477681/b439ee7b-5357-4f74-af73-d22dd6fab962)

个人认为除非用户手动需要删除任务的情况，streampark不应该从外部去强行删除deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
cc @Al-assad @wolfboys 
Thank you for your feedback. I am very sorry for taking so long to reply to you. We will discuss this issue within the community to see how to solve it.

**Comment by caicancai** [comment]
This seems to be a feature rather than a bug

**Comment by caicancai** [comment]
@zhenyuT Hello. It seems that this feature will not be completed in 2.1.3. The community is currently refactoring based on flink-operator, hoping to solve this problem by then.

**Comment by zhenyuT** [comment]
> This seems to be a feature rather than a bug

Yeah, it's a feature for StreamPark. But for me, really a surprised bug.

**Comment by zhenyuT** [comment]
> @zhenyuT Hello. It seems that this feature will not be completed in 2.1.3. The community is currently refactoring based on flink-operator, hoping to solve this problem by then.

Ok, maybe I will modify the source code myself to resolve it temporarily.

**Comment by caicancai** [comment]
> > @zhenyuT Hello. It seems that this feature will not be completed in 2.1.3. The community is currently refactoring based on flink-operator, hoping to solve this problem by then.
> 
> Ok, maybe I will modify the source code myself to resolve it temporarily.

Thank you for your feedback. I will consider your needs during the reconstruction process to improve it.

**Comment by youyangkou** [comment]
I think that when inferring the status of the flink k8s job, it is necessary to determine whether the job has HA enabled before cleaning up the flink deployment. Streampark only cleans up the deployment of failed jobs that do not enable HA. HA status can be obtained from flink-conf.yaml.

**Comment by caicancai** [comment]
> I think that when inferring the status of the flink k8s job, it is necessary to determine whether the job has HA enabled before cleaning up the flink deployment. Streampark only cleans up the deployment of failed jobs that do not enable HA. HA status can be obtained from flink-conf.yaml.

It seems that we only need to add a judgment to determine whether it is HA.

**Comment by Xuxiaotuan** [comment]
> > I think that when inferring the status of the flink k8s job, it is necessary to determine whether the job has HA enabled before cleaning up the flink deployment. Streampark only cleans up the deployment of failed jobs that do not enable HA. HA status can be obtained from flink-conf.yaml.
> 
> It seems that we only need to add a judgment to determine whether it is HA.

I'd like to try to modify it

**Comment by caicancai** [comment]
> I'd like to try to modify it

Thank you for your message. I hope this bug can be fixed in 2.1.3. I look forward to your PR.

**Comment by wolfboys** [comment]
Thanks for your feedback. The bug has been fixed.
