### ISSUE TITLE
[Bug] script/data/pgsql-data.sql is out of date

### ISSUE THREAD

**Issue by cobolbaby** [apache/streampark#3436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

dev

### Flink Version

1.17

### deploy mode

None

### What happened

The displayed webpage content is not as expected, the language pack hasn't fully loaded, and the menu categories are not up-to-date.

![2023-12-28 15-22-04屏幕截图](https://github.com/apache/incubator-streampark/assets/11460848/27960235-ef9b-4b7a-ae9a-240733f5e7af)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Thank you for your feedback. I’m very sorry for taking so long to reply to you. This question seems very strange. Is it still available?

**Comment by wolfboys** [comment]
fixed
