### ISSUE TITLE
[Bug] Searching for variables in streampark installed by postgresql report error

### ISSUE THREAD

**Issue by DimitriMok** [apache/streampark#3451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.15.3

### deploy mode

kubernetes-application

### What happened

We have installed streampark based on postgresql. Howerver, we found an error as following when searching for variables. There are some problems in page query variables by regexp match, but the version before 2.1.1 has nothing. By study source code, the sql changed from "'%${variable.variableCode}%'" to "concat ('%', #{variable.variableCode}, '%')" is not compatible with postgresql, though that can prevent the sql injection and compatible with mysql.

### Error Exception

```log
internal server error: ### Error querying database. Cause: org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $2 ### The error may exist in class path resource [mapper/core/VariableMapper.xml] ### The error may involve org.apache.streampark.console.core.mapper.VariableMapper.page-Inline ### The error occurred while setting parameters ### SQL: select count(*) as total from t_variable v inner join t_user u on v.creator_id = u.user_id and v.team_id = ? and v.variable_code like concat('%', ?, '%') ### Cause: org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $2 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $2
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/108189530/d8e42880-6af6-40ff-863b-e6a8e8c01346)
![image](https://github.com/apache/incubator-streampark/assets/108189530/c9fa6e96-1ea9-4448-86e0-102629edf0b0)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Thank you for your feedback, we will try to fix this issue

**Comment by caicancai** [comment]
@wolfboys @RocMarshal  This question looks like a good first issue, what do you think?

**Comment by VampireAchao** [comment]
assign me
