### ISSUE TITLE
[Bug] Wrong JobManager URL when config Application with Ingress LoadBalancer.And cancel Application cannot work

### ISSUE THREAD

**Issue by zhenyuT** [apache/streampark#3456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.15.3

### deploy mode

kubernetes-application

### What happened

![image](https://github.com/apache/incubator-streampark/assets/9477681/abb04132-1a70-438b-ae43-7a3285a02a4e)
![image](https://github.com/apache/incubator-streampark/assets/9477681/348e4144-0320-42b8-ad6f-5585e9646bd2)
![image](https://github.com/apache/incubator-streampark/assets/9477681/e39c09fd-506b-4179-9aea-81c953705b89)
Flink web ui link is right, but JobManager URL is wrong.

![image](https://github.com/apache/incubator-streampark/assets/9477681/13493c20-eb79-427f-adcb-b3adf287352f)
![image](https://github.com/apache/incubator-streampark/assets/9477681/a0478872-d2f5-4e89-9aa8-6a9abca25d1c)
Cancel Application feature cannot work, because it use the wrong JobManage URL.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed in 2.1.4
