### ISSUE TITLE
2.1.2版本在linux 无法启动

### ISSUE THREAD

**Issue by duchang9264** [apache/streampark#3483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

Java11 和 Java17

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

无

### deploy mode

None

### What happened

在linux解压完二进制包 修改完数据库配置完后 执行bash startup.sh 无法正常启动
Java17 不行 ，后改成Java11，报错信息多了些，详情见以下附件。
反正Java11和java17都不行。
[log.zip](https://github.com/apache/incubator-streampark/files/13884804/log.zip)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wyrm-gold** [comment]
是不是可以试试java8

**Comment by duchang9264** [comment]
> 是不是可以试试java8

我改完jdk1.8.0_131就可以启动了，但是页面比例不对，如下图：
![image](https://github.com/apache/incubator-streampark/assets/34643603/40a5fa56-b5af-4efe-ab43-1531a734f395)

**Comment by caicancai** [comment]
streampark has not been upgraded to java11 yet

**Comment by caicancai** [comment]
I tested it in the Linux environment and there was no problem. If it is a page problem, you are welcome to raise another issue. Thank you for your feedback.

**Comment by caicancai** [comment]
I'm sorry for replying so late.
