### ISSUE TITLE
[Bug] app_name 

### ISSUE THREAD

**Issue by jweicai** [apache/streampark#3490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.17.1

### deploy mode

None

### What happened

When creating a sparksql task, app_name can be a very long string. However, when you copy a task and have a very long app_name, an error will be reported, and the error level is relatively high. This should not be a reasonable operation.

### Error Exception

```log
internal server error: ### Error updating database. Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'cluster_id' at row 1 ### The error may exist in org/apache/streampark/console/core/mapper/ApplicationMapper.java (best guess) ### The error may involve org.apache.streampark.console.core.mapper.ApplicationMapper.insert-Inline ### The error occurred while setting parameters ### SQL: INSERT INTO t_flink_app ( team_id, job_type, user_id, job_name, version_id, cluster_id, flink_image, k8s_namespace, state, `release`, restart_size, option_state, alert_id, args, options, hot_params, resolve_order, execution_mode, dynamic_properties, app_type, tracking, cp_max_failure_interval, cp_failure_rate_interval, cp_failure_action, description, create_time, k8s_hadoop_integration, tags ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ) ### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'cluster_id' at row 1 ; Data truncation: Data too long for column 'cluster_id' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'cluster_id' at row 1
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ihadoop** [comment]
hi，i want to fix this bug。

**Comment by wolfboys** [comment]
> hi，i want to fix this bug。

Looking forward to your PR to fix this bug! 🛠️

**Comment by ihadoop** [comment]
> > hi，i want to fix this bug。
> 
> Looking forward to your PR to fix this bug! 🛠️

![image](https://github.com/apache/incubator-streampark/assets/5036560/6fa7eb71-1e4c-4de2-b599-0c0a83210ece)

hi，i viewed the code and  found that when  job is not session model, original job name  will be set as cluster_id.
i want to know when is not session model ,this value can be set as null

**Comment by caicancai** [comment]
> > > hi，i want to fix this bug。
> > 
> > 
> > Looking forward to your PR to fix this bug! 🛠️
> 
> ![image](https://private-user-images.githubusercontent.com/5036560/305353814-6fa7eb71-1e4c-4de2-b599-0c0a83210ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzYxNTksIm5iZiI6MTcwODIzNTg1OSwicGF0aCI6Ii81MDM2NTYwLzMwNTM1MzgxNC02ZmE3ZWI3MS0xZTRjLTRkZTItYjU5OS0wYzBhODMyMTBlY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDU1NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZjNWIzYzRlYTQzNTkzMjlmNGM4Y2U5NGFmZTgyZjExNDdhNjUyOTc1ZmRlZDZjZjU1YjA1YjEwNzg1MzBmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G192O2b8_jYVc9_CmHudqS9bF2h7qH_uCQ7xz-FXyQU)
> 
> hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null

Seems to be coming from the front end, maybe you need to debug to make sure

**Comment by ihadoop** [comment]
> > > > hi，i want to fix this bug。
> > > 
> > > 
> > > Looking forward to your PR to fix this bug! 🛠️
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/5036560/305353814-6fa7eb71-1e4c-4de2-b599-0c0a83210ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzYxNTksIm5iZiI6MTcwODIzNTg1OSwicGF0aCI6Ii81MDM2NTYwLzMwNTM1MzgxNC02ZmE3ZWI3MS0xZTRjLTRkZTItYjU5OS0wYzBhODMyMTBlY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDU1NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZjNWIzYzRlYTQzNTkzMjlmNGM4Y2U5NGFmZTgyZjExNDdhNjUyOTc1ZmRlZDZjZjU1YjA1YjEwNzg1MzBmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G192O2b8_jYVc9_CmHudqS9bF2h7qH_uCQ7xz-FXyQU)
> > hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null
> 
> Seems to be coming from the front end, maybe you need to debug to make sure

it’s not from front end，i means why set jobname as cluster_id if is not session  model

**Comment by jweicai** [comment]
I didn't modify the cluster_id, I just copied a task and filled in the app_name I needed.





在 2024-02-18 14:41:37，"sunshine" ***@***.***> 写道：

hi，i want to fix this bug。

Looking forward to your PR to fix this bug! ️


hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null

Seems to be coming from the front end, maybe you need to debug to make sure

it’s not from front end，i means why set jobname as cluster_id if is not session model

**Comment by ihadoop** [comment]
> I didn't modify the cluster_id, I just copied a task and filled in the app_name I needed. 在 2024-02-18 14:41:37，"sunshine" ***@***.***> 写道： hi，i want to fix this bug。 Looking forward to your PR to fix this bug! ️ hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null Seems to be coming from the front end, maybe you need to debug to make sure it’s not from front end，i means why set jobname as cluster_id if is not session model — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

but if old is session mode，it will set new job name as cluster_id,i want to know why ?


  ```
  newApp.setClusterId(
        FlinkExecutionMode.isSessionMode(oldApp.getFlinkExecutionMode())
            ? oldApp.getClusterId()
            : jobName);
```

**Comment by jweicai** [comment]
I just find this bug I don’t know why

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/18/2024 22:03 |
| To | apache/incubator-streampark ***@***.***> |
| Cc | charonjiang ***@***.***>,
Author ***@***.***> |
| Subject | Re: [apache/incubator-streampark] [Bug] app_name (Issue #3490) |

I didn't modify the cluster_id, I just copied a task and filled in the app_name I needed. 在 2024-02-18 14:41:37，"sunshine" @.> 写道： hi，i want to fix this bug。 Looking forward to your PR to fix this bug! ️ hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null Seems to be coming from the front end, maybe you need to debug to make sure it’s not from front end，i means why set jobname as cluster_id if is not session model — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

but if old is session mode，it will set new job name as cluster_id,i want to know why ?

newApp.setClusterId(
      FlinkExecutionMode.isSessionMode(oldApp.getFlinkExecutionMode())
          ? oldApp.getClusterId()
          : jobName);

**Comment by caicancai** [comment]
> > I didn't modify the cluster_id, I just copied a task and filled in the app_name I needed. 在 2024-02-18 14:41:37，"sunshine" _**@**_._**> 写道： hi，i want to fix this bug。 Looking forward to your PR to fix this bug! ️ hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null Seems to be coming from the front end, maybe you need to debug to make sure it’s not from front end，i means why set jobname as cluster_id if is not session model — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.**_>
> 
> but if old is session mode，it will set new job name as cluster_id,i want to know why ?
> 
> ```
> newApp.setClusterId(
>       FlinkExecutionMode.isSessionMode(oldApp.getFlinkExecutionMode())
>           ? oldApp.getClusterId()
>           : jobName);
> ```

？I'll take a look at it later

**Comment by ihadoop** [comment]
> > > I didn't modify the cluster_id, I just copied a task and filled in the app_name I needed. 在 2024-02-18 14:41:37，"sunshine" _**@**_._**> 写道： hi，i want to fix this bug。 Looking forward to your PR to fix this bug! ️ hi，i viewed the code and found that when job is not session model, original job name will be set as cluster_id. i want to know when is not session model ,this value can be set as null Seems to be coming from the front end, maybe you need to debug to make sure it’s not from front end，i means why set jobname as cluster_id if is not session model — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.**_>
> > 
> > 
> > but if old is session mode，it will set new job name as cluster_id,i want to know why ?
> > ```
> > newApp.setClusterId(
> >       FlinkExecutionMode.isSessionMode(oldApp.getFlinkExecutionMode())
> >           ? oldApp.getClusterId()
> >           : jobName);
> > ```
> 
> ？I'll take a look at it later

????

**Comment by wolfboys** [comment]
fixed
