### ISSUE TITLE
[Bug] Before initializing springboot, get enable-v2 and it will always be the default value

### ISSUE THREAD

**Issue by Xuxiaotuan** [apache/streampark#3494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

dev

### Flink Version

flink all version

### deploy mode

kubernetes-session

### What happened

When I wanted to start flink on k8s V2

I changed streampark.flink-k8s.enable-v2 to `true` in the configuration file but found that

`isV2Enabled` is of type `val`. After the class is initialized, it will be assigned false directly, 
![image](https://github.com/apache/incubator-streampark/assets/29968120/9097ae0b-2b6b-41cc-9d9b-3ca41f5d6669)

As a result, the values inside are refreshed even after springboot starts.

![image](https://github.com/apache/incubator-streampark/assets/29968120/60d09728-2f52-404c-8cf5-8761658a89a3)

However, there are two methods to get this value in advance, so in the initialization phase, you cannot get the value of springboot's yaml configuration, you get the initialization value (false)

The following is a method to use in advance when starting up

![image](https://github.com/apache/incubator-streampark/assets/29968120/ac72c661-8d17-4572-bab9-3be59a5457db)
![image](https://github.com/apache/incubator-streampark/assets/29968120/03549a28-6981-4f1f-94ca-b6d212c4b609)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@Al-assad If you have time, can you take a look at this issue? Thank you.

**Comment by caicancai** [comment]
I will check this issue over the weekend

**Comment by Xuxiaotuan** [comment]
I recommend loading these two parts after spring boot

Do not init during spring loading the bean， can put it in the ApplicationRunner phase
