### ISSUE TITLE
页面显示比例不正确

### ISSUE THREAD

**Issue by duchang9264** [apache/streampark#3496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.0_131

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

无

### deploy mode

kubernetes-application

### What happened

安装后 登录以后的页面比例不正确，如下：
![296911208-40a5fa56-b5af-4efe-ab43-1531a734f395](https://github.com/apache/incubator-streampark/assets/34643603/17a5cb74-3eb6-4078-bbc7-727217735c3f)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangsizhu0504** [comment]
Is it convenient to provide your node version and startup method?

**Comment by duchang9264** [comment]
> Is it convenient to provide your node version and startup method?
版本正确，启动命令用的就是官方的 bash startup.sh

**Comment by duchang9264** [comment]
> 方便提供一下你的node版本和启动方式吗？

启动方式：bash startup.sh  node版本：2.1.2 
![image](https://github.com/apache/incubator-streampark/assets/34643603/932cf92f-5828-44dc-bddd-dadd548d1647)

**Comment by wangsizhu0504** [comment]
> > 方便提供一下你的node版本和启动方式吗？
> 
> 启动方式：bash startup.sh node版本：2.1.2 ![image](https://private-user-images.githubusercontent.com/34643603/297566651-932cf92f-5828-44dc-bddd-dadd548d1647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDE2NDQsIm5iZiI6MTcwNTU0MTM0NCwicGF0aCI6Ii8zNDY0MzYwMy8yOTc1NjY2NTEtOTMyY2Y5MmYtNTgyOC00NGRjLWJkZGQtZGFkZDU0OGQxNjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAxMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNTUxYWE5NzVhZmY3ZGQ3MTk2ZDNmZjFlNDAxOGUzNjM4NTE4MGE2MjI2ZDVjNTcxN2Q1YTllZGMxMGFhY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t29jMQfgnCJ1HnBKHVWjRMl65kCUfJC8xuXdJE8tKag)

在浏览器中 f12 打开控制台，刷新一下页面，看下console 中有没有错误输出

![CleanShot 2024-01-18 at 09 36 29@2x](https://github.com/apache/incubator-streampark/assets/39726513/f7e5dc47-b847-4dc5-ab57-f841943f0661)

**Comment by duchang9264** [comment]
> > > 方便提供一下你的node版本和启动方式吗？
> > 
> > 
> > 启动方式：bash startup.sh node版本：2.1.2 ![image](https://private-user-images.githubusercontent.com/34643603/297566651-932cf92f-5828-44dc-bddd-dadd548d1647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDE2NDQsIm5iZiI6MTcwNTU0MTM0NCwicGF0aCI6Ii8zNDY0MzYwMy8yOTc1NjY2NTEtOTMyY2Y5MmYtNTgyOC00NGRjLWJkZGQtZGFkZDU0OGQxNjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAxMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNTUxYWE5NzVhZmY3ZGQ3MTk2ZDNmZjFlNDAxOGUzNjM4NTE4MGE2MjI2ZDVjNTcxN2Q1YTllZGMxMGFhY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t29jMQfgnCJ1HnBKHVWjRMl65kCUfJC8xuXdJE8tKag)
> 
> 在浏览器中 f12 打开控制台，刷新一下页面，看下console 中有没有错误输出
> 
> ![CleanShot 2024-01-18 at 09 36 29@2x](https://private-user-images.githubusercontent.com/39726513/297571515-f7e5dc47-b847-4dc5-ab57-f841943f0661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDMxMTYsIm5iZiI6MTcwNTU0MjgxNiwicGF0aCI6Ii8zOTcyNjUxMy8yOTc1NzE1MTUtZjdlNWRjNDctYjg0Ny00ZGM1LWFiNTctZjg0MTk0M2YwNjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAxNTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZTc4ZmRkYmJlN2RkYTkzMTAxMTVjNWM1MmU3ZTQ4ODY3Mjc0OWQwOWM2OWYxMThjNTllZTBkNmIwNTU0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1pzgvTPPCrxP1tyaTqvveNkt_7AEi2phdPIUWOzYnsc)

![image](https://github.com/apache/incubator-streampark/assets/34643603/639dd29b-b1ba-4714-96b2-046bd1bd11ec)

**Comment by wangsizhu0504** [comment]
更换一下浏览器试一下，使用edge 打开看一下

**Comment by duchang9264** [comment]
> 更换一下浏览器试一下，使用edge 打开看一下

用edge浏览器控制台没有报错，但是还是不行：
![image](https://github.com/apache/incubator-streampark/assets/34643603/1d6b10d9-d58f-40ae-a8d2-0f5c0d5f6c34)
![image](https://github.com/apache/incubator-streampark/assets/34643603/4a67fbc1-96ec-49b6-b33b-03693a3d32aa)

**Comment by wangsizhu0504** [comment]
下载这个版本的包到本地，https://github.com/apache/incubator-streampark/tree/release-2.1.2， 然后安装 nodejs (v16.15.0) 进入 streampark-console/streampark-console-webapp 目录，修改.env.development
中的
```shell
VITE_PROXY=[["/basic-api","http://localhost:10000"]]
```
将localhost:10000 换成你线上的后端地址，然后 执行 npm install -g pnpm && pnpm install --registry https://registry.npmmirror.com --ignore-script && npm run dev

**Comment by duchang9264** [comment]
> 下载这个版本的包到本地，[https://github.com/apache/incubator-streampark/tree/release-2.1.2，](https://github.com/apache/incubator-streampark/tree/release-2.1.2%EF%BC%8C) 然后安装 nodejs (v16.15.0) 进入 streampark-console/streampark-console-webapp 目录，修改.env.development 中的
> 
> ```shell
> VITE_PROXY=[["/basic-api","http://localhost:10000"]]
> ```
> 
> 将localhost:10000 换成你线上的后端地址，然后 执行 npm install -g pnpm && pnpm install --registry https://registry.npmmirror.com --ignore-script && npm run dev

这个意思是本地下源码打包试吗？现在咱们能确定问题所在吗

**Comment by wangsizhu0504** [comment]
> > 下载这个版本的包到本地，[https://github.com/apache/incubator-streampark/tree/release-2.1.2，](https://github.com/apache/incubator-streampark/tree/release-2.1.2%EF%BC%8C) 然后安装 nodejs (v16.15.0) 进入 streampark-console/streampark-console-webapp 目录，修改.env.development 中的
> 
> > 
> 
> > ```shell
> 
> > VITE_PROXY=[["/basic-api","http://localhost:10000"]]
> 
> > ```
> 
> > 
> 
> > 将localhost:10000 换成你线上的后端地址，然后 执行 npm install -g pnpm && pnpm install --registry https://registry.npmmirror.com --ignore-script && npm run dev
> 
> 
> 
> 这个意思是本地下源码打包试吗？现在咱们能确定问题所在吗

暂时无法定位问题

**Comment by duchang9264** [comment]
> > > 下载这个版本的包到本地，[https://github.com/apache/incubator-streampark/tree/release-2.1.2，](https://github.com/apache/incubator-streampark/tree/release-2.1.2%EF%BC%8C) 然后安装 nodejs (v16.15.0) 进入 streampark-console/streampark-console-webapp 目录，修改.env.development 中的
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > VITE_PROXY=[["/basic-api","http://localhost:10000"]]
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 将localhost:10000 换成你线上的后端地址，然后 执行 npm install -g pnpm && pnpm install --registry https://registry.npmmirror.com --ignore-script && npm run dev
> > 
> > 
> > 这个意思是本地下源码打包试吗？现在咱们能确定问题所在吗
> 
> 暂时无法定位问题

这个情况别人没有遇到吗？我让我们前端看了临时调试了下，发现有个元素好像影响到了，不知道还有没有其他地方影响到，以下为对比图：
![image](https://github.com/apache/incubator-streampark/assets/34643603/27bbc148-dc8f-472a-a9e8-7a3d274ba123)

![image](https://github.com/apache/incubator-streampark/assets/34643603/66457388-87b2-4179-bb80-04e15a59c9a2)

**Comment by wangsizhu0504** [comment]
目前你这个情况是 很多元素的样式缺失，或者样式优先级发生改变了，并不仅仅是这一个元素，比如左侧菜单高度应该是撑满浏览器的高度，顶部中间会有一个系统slogan , 顶部右侧用户名称那里好像也有点问题，如果你下载的是官网的release安装包，大概率不会发生这样的问题，每次发版我们都有专门的人员测试这个包的稳定性。你这个情况还是第一次得到反馈，我怀疑是编译时的错误，所以建议你用源码编译一下.

**Comment by duchang9264** [comment]
> 目前你这个情况是 很多元素的样式缺失，或者样式优先级发生改变了，并不仅仅是这一个元素，比如左侧菜单高度应该是撑满浏览器的高度，顶部中间会有一个系统slogan , 顶部右侧用户名称那里好像也有点问题，如果你下载的是官网的release安装包，大概率不会发生这样的问题，每次发版我们都有专门的人员测试这个包的稳定性。你这个情况还是第一次得到反馈，我怀疑是编译时的错误，所以建议你用源码编译一下.

我也是从官网下载的安装包：
![image](https://github.com/apache/incubator-streampark/assets/34643603/d6461ea2-c21a-495b-841b-992df19013a7)

**Comment by wangsizhu0504** [comment]
> > 目前你这个情况是 很多元素的样式缺失，或者样式优先级发生改变了，并不仅仅是这一个元素，比如左侧菜单高度应该是撑满浏览器的高度，顶部中间会有一个系统slogan , 顶部右侧用户名称那里好像也有点问题，如果你下载的是官网的release安装包，大概率不会发生这样的问题，每次发版我们都有专门的人员测试这个包的稳定性。你这个情况还是第一次得到反馈，我怀疑是编译时的错误，所以建议你用源码编译一下.
> 
> 我也是从官网下载的安装包： ![image](https://private-user-images.githubusercontent.com/34643603/297930489-d6461ea2-c21a-495b-841b-992df19013a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzMzMDEsIm5iZiI6MTcwNTYzMzAwMSwicGF0aCI6Ii8zNDY0MzYwMy8yOTc5MzA0ODktZDY0NjFlYTItYzIxYS00OTViLTg0MWItOTkyZGYxOTAxM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAyNTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTRmNzIyODI3MmZmOGNkM2U5NGIyZmRlMjQ5MWIwOTE5ZThjZjJkODUxNmY2NTY2NTJiY2VjNGZjMmQwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aAPnZITmfALvlQSUC8LWszicM4x5lh6u0rA4wJW8gao)

我下载了官网的2.1.2 版本，通过解包后，本地测试jar 包中的静态页面，并没有发现你的问题
![CleanShot 2024-01-19 at 10 59 01@2x](https://github.com/apache/incubator-streampark/assets/39726513/050a4e79-1a3f-4691-9f17-5be8f032d236)
你可以通过以上方式本地排查一下

**Comment by duchang9264** [comment]
> > > 目前你这个情况是 很多元素的样式缺失，或者样式优先级发生改变了，并不仅仅是这一个元素，比如左侧菜单高度应该是撑满浏览器的高度，顶部中间会有一个系统slogan , 顶部右侧用户名称那里好像也有点问题，如果你下载的是官网的release安装包，大概率不会发生这样的问题，每次发版我们都有专门的人员测试这个包的稳定性。你这个情况还是第一次得到反馈，我怀疑是编译时的错误，所以建议你用源码编译一下.
> > 
> > 
> > 我也是从官网下载的安装包： ![image](https://private-user-images.githubusercontent.com/34643603/297930489-d6461ea2-c21a-495b-841b-992df19013a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzMzMDEsIm5iZiI6MTcwNTYzMzAwMSwicGF0aCI6Ii8zNDY0MzYwMy8yOTc5MzA0ODktZDY0NjFlYTItYzIxYS00OTViLTg0MWItOTkyZGYxOTAxM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAyNTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTRmNzIyODI3MmZmOGNkM2U5NGIyZmRlMjQ5MWIwOTE5ZThjZjJkODUxNmY2NTY2NTJiY2VjNGZjMmQwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aAPnZITmfALvlQSUC8LWszicM4x5lh6u0rA4wJW8gao)
> 
> 我下载了官网的2.1.2 版本，通过解包后，本地测试jar 包中的静态页面，并没有发现你的问题 ![CleanShot 2024-01-19 at 10 59 01@2x](https://private-user-images.githubusercontent.com/39726513/297940725-050a4e79-1a3f-4691-9f17-5be8f032d236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQzNDMsIm5iZiI6MTcwNTYzNDA0MywicGF0aCI6Ii8zOTcyNjUxMy8yOTc5NDA3MjUtMDUwYTRlNzktMWEzZi00NjkxLTlmMTctNWJlOGYwMzJkMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZDM5YTg3ZjdjNzZkMWMxMmQ2NDA1OTRhYzllZjg4NWU5NjU5NjYwYzU4ZWQyZDJmNmRiNjI0YzE5NTVlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YA0c4pvM72BgqD7plqlRxn1psiXIAzBo8fmq2G6SYdY) 你可以通过以上方式本地排查一下

会不会是我下载的那个安装包有问题，你们本地用那个安装包有问题吗？我看css加载了：
![image](https://github.com/apache/incubator-streampark/assets/34643603/58848293-9bca-4ce8-b242-ed9dd8446c15)

**Comment by wangsizhu0504** [comment]
> > > > 目前你这个情况是 很多元素的样式缺失，或者样式优先级发生改变了，并不仅仅是这一个元素，比如左侧菜单高度应该是撑满浏览器的高度，顶部中间会有一个系统slogan , 顶部右侧用户名称那里好像也有点问题，如果你下载的是官网的release安装包，大概率不会发生这样的问题，每次发版我们都有专门的人员测试这个包的稳定性。你这个情况还是第一次得到反馈，我怀疑是编译时的错误，所以建议你用源码编译一下.
> > > 
> > > 
> > > 我也是从官网下载的安装包： ![image](https://private-user-images.githubusercontent.com/34643603/297930489-d6461ea2-c21a-495b-841b-992df19013a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzMzMDEsIm5iZiI6MTcwNTYzMzAwMSwicGF0aCI6Ii8zNDY0MzYwMy8yOTc5MzA0ODktZDY0NjFlYTItYzIxYS00OTViLTg0MWItOTkyZGYxOTAxM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAyNTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTRmNzIyODI3MmZmOGNkM2U5NGIyZmRlMjQ5MWIwOTE5ZThjZjJkODUxNmY2NTY2NTJiY2VjNGZjMmQwMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aAPnZITmfALvlQSUC8LWszicM4x5lh6u0rA4wJW8gao)
> > 
> > 
> > 我下载了官网的2.1.2 版本，通过解包后，本地测试jar 包中的静态页面，并没有发现你的问题 ![CleanShot 2024-01-19 at 10 59 01@2x](https://private-user-images.githubusercontent.com/39726513/297940725-050a4e79-1a3f-4691-9f17-5be8f032d236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQzNDMsIm5iZiI6MTcwNTYzNDA0MywicGF0aCI6Ii8zOTcyNjUxMy8yOTc5NDA3MjUtMDUwYTRlNzktMWEzZi00NjkxLTlmMTctNWJlOGYwMzJkMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZDM5YTg3ZjdjNzZkMWMxMmQ2NDA1OTRhYzllZjg4NWU5NjU5NjYwYzU4ZWQyZDJmNmRiNjI0YzE5NTVlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YA0c4pvM72BgqD7plqlRxn1psiXIAzBo8fmq2G6SYdY) 你可以通过以上方式本地排查一下
> 
> 会不会是我下载的那个安装包有问题，你们本地用那个安装包有问题吗？我看css加载了： ![image](https://private-user-images.githubusercontent.com/34643603/297943626-58848293-9bca-4ce8-b242-ed9dd8446c15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTg0NzIsIm5iZiI6MTcwNTY1ODE3MiwicGF0aCI6Ii8zNDY0MzYwMy8yOTc5NDM2MjYtNTg4NDgyOTMtOWJjYS00Y2U4LWIyNDItZWQ5ZGQ4NDQ2YzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA5NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTA2ZmJjNDhjNzljMjIwYzMyNTk1ZDgzMWU0MGVjMmVkYjMzMzVlMGM5NzQ3N2RlMzY2MDdmMmQ3ZGIyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ylotwmz8iRexXvySkvtTKC9ATaIEXz3KxoC4glLbIfA)

不会吧我和你下载的是一样的，只不过我把jar包解开了，然后用的nginx 代理访问，你可以试一下，把 lib下的streampark-console-service-2.1.2.jar 用压缩包解压，把里面的static 放到Nginx目录下 ，然后修改nginx 的配置

```shell
	location / {
	# 这里修改成streampark 后端启动的地址
      proxy_pass http://127.0.0.1:10000/;
    }

    location ~ \.(html|css|js|png|jpg|jpeg|gif|ico|svg)$ {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Content-Security-Policy' 'frame-ancestors *';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization';
        return 204;
      }
      rewrite ^/[^\.]*$ /index.html last;
	  # 这里指向你放到nginx 中的 static 目录
      root /opt/homebrew/var/www/streampark;
      index index.html index.htm;
    }
```
修改完成后重启nginx  看下你的页面还有问题没

**Comment by wolfboys** [comment]
answered
