### ISSUE TITLE
[Feature] Flowchart improvements to StreamPark documentation

### ISSUE THREAD

**Issue by caicancai** [apache/streampark#3500]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In the StreamPark English document, some pictures have Chinese text. Now it is necessary to complete the picture text into English.

![2024-01-18 21-16-16屏幕截图](https://github.com/apache/incubator-streampark/assets/77189278/aec71788-8f8d-49ca-a7ac-d99e4475d496)

Document main link: 
https://streampark.apache.org/docs/user-guide/platformInstall
https://streampark.apache.org/docs/user-guide/platformBasicUsage

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
@caicancai  pls assigned this issues to me

**Comment by caicancai** [comment]
@zzzk1 Thank you
