### ISSUE TITLE
[Bug] retrieve flink jobManager fail by k8s ingress

### ISSUE THREAD

**Issue by 531651225** [apache/streampark#3510]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

2.1.3

### Flink Version

1.14.4

### deploy mode

None

### What happened

retrieve flink jobManager fail by k8s ingress, because ingress config not configured spec.ingressClass.
K8S versionI is v1.27.4，version > 1.18 is needed

### Error Exception

15:00:30.972 [ForkJoinPool-1-worker-17] INFO org.apache.streampark.flink.kubernetes.KubernetesRetriever - retrieve flink jobManager rest url: http://flink.mfwdev.com/flink-cluster/side-pipline-web/
15:00:30.975 [ForkJoinPool-1-worker-17] WARN org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher - The retry fetch failed, final status failed, errorStack=status code: 404, reason phrase: Not Found.
15:00:31.149 [ForkJoinPool-1-worker-17] INFO org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher - Task Enter the initialization process.
15:00:35.778 [ForkJoinPool-1-worker-36] WARN org.apache.streampark.flink.kubernetes.watcher.FlinkJobStatusWatcher - Failed to visit remote flink jobs on kubernetes-native-mode cluster, and the retry access logic is performed.

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/33744252/d38dbe4e-bb98-4688-b09a-9ada33797443)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@531651225  finish？
