### ISSUE TITLE
[Bug] checkFlinkEnv do not refresh the hdfs flink lib dir while there are changes in local flink lib dir,

### ISSUE THREAD

**Issue by liuxinjie5211990** [apache/streampark#3524]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java 8

### Scala Version

2.11.x

### StreamPark Version

2.1.1

### Flink Version

1.16.2

### deploy mode

yarn-application

### What happened

while we have configured a flink home before and use it to start a flink job with our jar using yarn-application mode.At the same time, this JAR will use a new connector. Since we are building a source code JAR package, we are uploading the connector to the local lib directory of Flink.In this case, when executing the Flink JAR, an error occurs indicating that the class for the connector cannot be found.

The issue arises because the EnvInitializer.checkFlinkEnv method uploads the Flink directory to the HDFS StreamPark workspace only on certain occasions, such as when starting or deploying the application. In the YARN application mode, the /streampark/flink/flink-1.16.2/lib directory is included in the classpath. However, since the checkFlinkEnv method checks whether the directory exists before uploading files (if (!fsOperator.exists(flinkHome))), any subsequent modifications to the local Flink lib directory will not be updated in HDFS.

We can only manually upload any added JARs to HDFS, which is not very user-friendly. This is because, without inspecting the source code, users may not be aware that uploading to this directory（/streampark/flink/flink-1.16.2/lib） is required for working nomally.

### Error Exception

```log
Caused by: java.lang.NoClassDefFoundError: com/ververica/cdc/connectors/postgres/PostgreSQLSource

if (!fsOperator.exists(flinkHome)) {
      log.info("{} is not exists,upload beginning....", flinkHome);
      fsOperator.upload(flinkLocalHome, flinkHome, false, true);
 }
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/57188699/6573f97c-0abb-4d5c-94e2-7b3c56791a72)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ZHI-XINHUA** [comment]
i have the same problem

**Comment by caicancai** [comment]
Thank you for your report and look forward to your repair

**Comment by liuxinjie5211990** [comment]
> Thank you for your report and look forward to your repair

Thank you for your response. I am honored to receive your reply.
My idea is that in the application mode, it mainly uses the `/streampark/flink/flink-{version}/lib` and `/streampark/flink/flink-{version}/plugins` directories on HDFS as `yarn.provided.lib.dirs`. In the production environment, there might be a need to update third-party libraries in `flink/lib` to support the execution of new job JARs. I'm not sure if our project usage is correct, and I appreciate your guidance if there are alternative approaches.

Therefore, when there are changes in the `lib` directory of the local Flink home, it is necessary to update the files in these two directories on the remote HDFS. While manually uploading to these directories can solve the problem, it generally poses challenges for Streampark deployers: they may not be familiar with directly manipulating HDFS directories, might not be aware that files need to be uploaded to these two directories, or may not have the necessary permissions on the machines to operate HDFS.

1. My idea is whether it is possible to add a logic inside the if (!fsOperator.exists(flinkHome)) statement in the EnvInitializer.checkFlinkEnv method. When the mode is yarn application, use the HdfsOperator.fileMd5 method to verify whether the files in the local and HDFS lib directories are consistent, and then trigger the fsOperator.upload logic again if necessary.Just like the pseudocode below。

if (!fsOperator.exists(flinkHome)) {
    log.info("{} is not exists,upload beginning....", flinkHome);
    fsOperator.upload(flinkLocalHome, flinkHome, false, true);
}
//here is the pseudocode,upload the differences to the remote directory
if (mode == YarnApplicationMode && !HdfsOperator.fileMd5(localLibDir).equals(HdfsOperator.fileMd5(hdfsLibDir))) {
     // Files are not the same, trigger upload logic 
     fsOperator.upload(localLibDir, hdfsLibDir);
}

2. Alternatively, the web page could provide an option to manually upload and trigger the update of the Flink home's 'lib' directory.

**Comment by wolfboys** [comment]
Thanks for your feedback. The current design treats the local Flink as just a reference and mapping. It is not recommended to modify the local Flink files. If there are jobs running in yarn application mode and there are updates to the local Flink files, you would need to manually operate on HDFS to update the changed files into it.
