### ISSUE TITLE
[Bug] job start successed but  ingress create fail 

### ISSUE THREAD

**Issue by 531651225** [apache/streampark#3540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

2.1.3

### Scala Version

2.11.x

### StreamPark Version

2.1.3

### Flink Version

1.14.4

### deploy mode

kubernetes-application

### What happened

job start successed but  ingress create fail , because cluster_id is none

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
