### ISSUE TITLE
[improvement] make the ```create time``` equal to ```update time ``` when create a application

### ISSUE THREAD

**Issue by fuchanghai** [apache/streampark#3549]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<img width="932" alt="image" src="https://github.com/apache/incubator-streampark/assets/33984497/79f73754-b956-4a70-aa35-a06515dc6ed3">
i think use ```appParam.setCreateTime(new Date());
    appParam.setModifyTime(appParam.getCreateTime()); ``` is better

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
+1

**Comment by ihadoop** [comment]
i think it should set db column default as current time or update time。it not need set this value in code

**Comment by fuchanghai** [comment]
> i think it should set db column default as current time or update time。it not need set this value in code

hi @ihadoop  but this way also can case that the ```create time``` not equal to ```update time ```
cc @caicancai

**Comment by caicancai** [comment]
@ihadoop Maybe a good idea, but I am not responsible for this module, I think the current streampark table structure is very confusing, because you can see that a lot of users have recently encountered field problems in the table here and asked for pr, I don't think this is good news, because in my opinion the table structure should be very stable, I am wondering whether I need to refactor this part, and I think it can be handled in this way first

cc @VampireAchao @wolfboys

**Comment by caicancai** [comment]
> > i think it should set db column default as current time or update time。it not need set this value in code
> 
> hi @ihadoop but this way also can case that the `create time` not equal to `update time ` cc @caicancai

yes

**Comment by caicancai** [comment]
> i think it should set db column default as current time or update time。it not need set this value in code

Random changes to the table structure may also affect user upgrades

**Comment by VampireAchao** [comment]
@caicancai , thank you for your feedback and your concern for the project. I fully understand your worries about the current state of the streampark table structure, as well as your considerations for stability and user experience.

Regarding the part about refactoring that you mentioned, I agree that it's a matter worth discussing. However, in line with the principles of [Semantic Versioning (SemVer)](https://semver.org/lang/zh-CN/), I would suggest that any changes to the table structure that might break backward compatibility be reserved for a major version release. The rationale behind this approach is to ensure that minor version updates can be safely rolled out to existing users without introducing unexpected breaking changes.

For the upcoming major version update, we can thoroughly review and improve the table structure while also providing ample notice and guidance for migration to our users, ensuring a smooth transition. Until then, I recommend that we focus our efforts on maintaining the stability of the current table structure and addressing the specific issues our users are currently facing.

Thank you again for your suggestion. I look forward to further discussions with you and the community on this matter to find the most suitable solution for our project.

**Comment by VampireAchao** [comment]
I agree,
it appears there may be some confusion regarding the PR in question. It doesn't seem to include any changes to the table structure, but rather, it's about the values being modified—specifically, ensuring that the creation and modification timestamps are consistent when an entry is created. This adjustment is about maintaining data accuracy rather than altering the schema.

**Comment by VampireAchao** [comment]
> I agree the change, it appears there may be some confusion regarding the PR in question. It doesn't seem to include any changes to the table structure, but rather, it's about the values being modified—specifically, ensuring that the creation and modification timestamps are consistent when an entry is created. This adjustment is about maintaining data accuracy rather than altering the schema.

**Comment by VampireAchao** [comment]
> i think it should set db column default as current time or update time。it not need set this value in code我认为它应该将数据库列默认值设置为当前时间或更新时间。它不需要在代码中设置此值

I understand the point about setting default timestamps directly in the database. However, automatic updates are not feasible in our case since any changes to the 'status' would also trigger an update. That's why we removed the automatic update feature from the table.
