### ISSUE TITLE
[Improve] Format plugin support pom.xml

### ISSUE THREAD

**Issue by zhengkezhou1** [apache/streampark#3551]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add a formatting plugin to the pom.xml file to avoid formatting errors caused by manual formatting

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
This exists, you need to execute mvn spotless:apply
