### ISSUE TITLE
[Feature] StreamPark support submit spark task to yarn

### ISSUE THREAD

**Issue by ChengJie1053** [apache/streampark#3569]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, StreamPark only supports flink, but many users are using spark, so StreamPark was extended to support Spark

The features to be implemented include：
1.Submit the spark jar task to yarn
2.Submit the spark sql task to yarn
3.Spark yarn status tracing
4.Spark yarn task stop

Design documentation: https://www.yuque.com/chengjie-lhwqa/kb/sqok17szgtggndno?singleDoc# 《Streampark支持Spark任务提交至Yarn》

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Maybe you should show your plan

**Comment by ChengJie1053** [comment]
> Maybe you should show your plan

Ok, I'm writing the technical plan

**Comment by caicancai** [comment]
@wolfboys @ChengJie1053 We should find time to evaluate the plan. What do you think?

**Comment by caicancai** [comment]
@ChengJie1053 Can this large function be split into small tasks?

**Comment by ChengJie1053** [comment]
Ok, thanks for the advice

**Comment by caicancai** [comment]
This issue seems to be completed, closing
