### ISSUE TITLE
[Bug] mysql ddl "on update current_timestamp" compatibility improvements 

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3570]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

all

### Scala Version

2.11.x

### StreamPark Version

all

### Flink Version

all

### deploy mode

None

### What happened

Currently, there is a syntax "ON UPDATE CURRENT_TIMESTAMP" in StreamPark's MySQL DDL, This syntax is only supported starting from MySQL version 5.6.5. For users whose MySQL version is lower than 5.6, it will cause the execution ddl failed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by joyCurry30** [comment]
I'm willing to take on this issue, please assign it to me, thank you.
