### ISSUE TITLE
[Improve]  Refactor update setting interface

### ISSUE THREAD

**Issue by zhengkezhou1** [apache/streampark#3578]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

***Improve Setting update interface***
----------------------------------------------------------------------------------------------------------------
**Platforms such as Dcker Configuration and Alert Configuration lack parameter checks and are too arbitrary. Improve this by making the configurations for the different functions available as a complete form, so that they can be verified for completeness and compliance at submission time.**
----------------------------------------------------------------------------------------------------------------
<img width="1310" alt="微信图片_20240226174735" src="https://github.com/apache/incubator-streampark/assets/36791902/85adc69e-d05d-48c6-affa-7bcdadd03e70">
<img width="1320" alt="微信图片_20240226174729" src="https://github.com/apache/incubator-streampark/assets/36791902/ae5802f6-42d3-4648-b962-af46d8161a84">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengkezhou1** [comment]
Hi, @wangsizhu0504，can you help me to flish this?

**Comment by wangsizhu0504** [comment]
> Hi, @wangsizhu0504，can you help me to flish this?

OK, I'll submit the front-end p after you finish the task.

**Comment by wolfboys** [comment]
done
