### ISSUE TITLE
The functionality to build the flink jar is buggy

### ISSUE THREAD

**Issue by mezhangremoterepository** [apache/streampark#3602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.14.6

### deploy mode

yarn-application

### What happened

When I built the flink jar with version 2.1.2, I kept getting an error: there was no.mvn folder in the specified directory, but I checked the path and it actually did exist,bulid flink jar function I started to use from the 2.0.0 version, the function is very useful, but the 2.1.2 version of the function is not available, please fix it

### Error Exception

```log
Invalid maven setting path
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, can you provide error logs or screenshots?

**Comment by mezhangremoterepository** [comment]
Hello big guy, I fixed this bug yesterday 
Fix: Replace the file in the bin directory with mvnw in the bin directory of version 2.0.0

**Comment by mezhangremoterepository** [comment]
Big guy, I used version 2.0.0 before, using pg to do metadata management, plan to upgrade to 2.1.0, but after executing version 2.1.0 pg upgrade sql, all my data is unavailable, and the interface can not be logged in. After viewing the upgrade sql file, I found that there were operations to delete fields, it is these operations that lead to the failure of the upgrade I can't even get to the page. It's a suicide escalation.

**Comment by mezhangremoterepository** [comment]
s there any way to smoothly upgrade the version? Because I could not submit the yarn task in version 2.0.0, and there was no error reported, I could not find the repair method. So I tried to upgrade to version 2.1.0, but after the sql file was upgraded, all the functions were unavailable

**Comment by wolfboys** [comment]
It is recommended that upgrade streampark to 2.1.3 and try again.
