### ISSUE TITLE
Unstable test case

### ISSUE THREAD

**Issue by RocMarshal** [apache/streampark#3604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

N.A

### Flink Version

N.A

### deploy mode

None

### What happened

<img width="1530" alt="image" src="https://github.com/apache/incubator-streampark/assets/64569824/57e47d88-0d22-4520-bc1f-872e3e8c10e9">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RocMarshal** [comment]
CC @caicancai @VampireAchao

**Comment by caicancai** [comment]
If no one claims this issue in the past two days, I suggest that we need to fix this bug first, because this will affect the PR merge of the dev branch

**Comment by caicancai** [comment]
@RocMarshal I think you can fix it
