### ISSUE TITLE
[Feature] Add custom alert statements to alarm configuration.

### ISSUE THREAD

**Issue by tianqin69** [apache/streampark#3606]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When we configure the alert email, add the custom alert statement configuration. Now the situation is that when I get the email, I don't know whether the test or production tasks are down

### Usage Scenario

When the task is abnormal, it can quickly locate the abnormal task

### Related issues

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
We can't get what you mean from your description. Please provide more info or contact us by email-list.
