### ISSUE TITLE
[Improve] mybatis-plus updateStrategy improvements

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3607]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

StremaPark is using mybatis-plus as an ORM framework. Currently, many entities are annotated with @TableField(updateStrategy = FieldStrategy.IGNORED). As the number of entity classes grows, this has caused trouble for the code's readability and maintainability. This issue can be addressed by using mybatis-plus's global configuration to remove the updateStrategy annotation from all entity classes. However, this may result in some of the original data update operations failing, requiring us to make adjustments. The general approach to solving this is to retrieve and populate the entity from the database before updating. Do you have a better solution? Let's discuss! 😉
<img width="1040" alt="image" src="https://github.com/apache/incubator-streampark/assets/13284744/2f005538-4ba3-4080-a70a-184335d67b5e">

mybatis global update strategy:

<img width="1059" alt="image" src="https://github.com/apache/incubator-streampark/assets/13284744/c3e70112-f5c6-4896-9aa7-b92deaaafee5">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VampireAchao** [comment]
assign me please，I am sure I can finish this
