### ISSUE TITLE
[Feature] add support svn

### ISSUE THREAD

**Issue by LKK1535977706** [apache/streampark#3609]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

support svn 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, currently, no one is driving this feature. If you are interested in contributing to this feature, we will accept this feature

**Comment by wolfboys** [comment]
Currently, there is no plan to support this feature.
