### ISSUE TITLE
[Improve] Delete the invalid SECURITY.md file

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3610]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

## [Improve] Delete the invalid SECURITY.md file

the SECURITY.md file does not follow the ASF vulnerability handling process.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kick156** [comment]
good evening, friend。assign me please
