### ISSUE TITLE
[Bug] streampark页面上显示的flink任务状态和实际不一致

### ISSUE THREAD

**Issue by zhenyuT** [apache/streampark#3618]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Scala Version

2.12.x

### StreamPark Version

2.1.3

### Flink Version

1.15.3

### deploy mode

kubernetes-application

### What happened

k8s环境不稳定，导致flink pod自动重启，重启后flink任务恢复正常，但是streampark页面上显示任务状态为FAIL

![image](https://github.com/apache/incubator-streampark/assets/9477681/416c623c-0fae-45c9-bd96-72f35c4ee958)
![image](https://github.com/apache/incubator-streampark/assets/9477681/e608362a-6b2d-41e9-99fd-6540233b69d6)

查看代码和日志，发现主要问题在于，watch进程在进行flink任务状态监听时，请求flink web接口出现异常，再去请求k8s api server判断deployment是否存在的时候也发生了异常(etcd server leader发生了变更)。这里KubernetesRetriever.isDeploymentExists逻辑存在问题，发生异常时返回false，即认为deployment不存在，但是实际这时候deployment是存在的。由于错误的识别到deployment不存在，于是把任务状态更新为FAIL，并且终止了任务的监听，即使后面k8s恢复，streampark上的任务状态也不会恢复。

通过chaosblade工具模拟网络丢包，可以轻松的重现这个问题。
chaosblade文档见：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-network-loss

我这里的环境，k8s api server请求地址为https://172.18.64.242:8443, flink web接口的访问地址为https://172.18.64.242:443
于是我注入网络丢包的命令为：./blade create network loss --percent 100 --interface eth0 --remote-port 443,8443 --destination-ip 172.18.64.242 --timeout 200
简单解释下：这里是把请求到IP为172.18.64.242，端口为443和8443的网络请求丢包率设置为100%，持续200秒

启动flink任务后，再通过命令注入网络故障，再查看streampark页面，就会发现任务状态变为FAIL，即使后面网络故障恢复，任务状态也不会恢复为RUNNING(期间flink任务本身一直正常工作)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhenyuT** [comment]
除了上面说的，还有一个偶尔出现的问题：
任务状态不一致以后，在flink页面上cancel任务，此时任务状态变为CANCELD
然后streampark页面上点击启动任务，k8s上查看任务启动正常，但是页面上任务状态还是CANCELD

![image](https://github.com/apache/incubator-streampark/assets/9477681/8d486f1e-37e2-49ed-82f2-b8978f10f735)

![83b7a1370dff2df52a9ef2ab3979d0a7](https://github.com/apache/incubator-streampark/assets/9477681/74158a49-da4f-4186-b0a2-3fa67fde3239)

进行远程debug断点调试，发现是内存中缓存的jobStatuses状态和数据库不一致(数据库中状态时CANCELED，内存中时RUNNING)。然后watch进程监听到任务状态为RUNNING，和内存中缓存的状态进行比对，发现都是RUNNING，就不会去更新数据库状态

**Comment by zhenyuT** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22+sort%3Aupdated-desc) and found no similar issues.
> 
> ### Java Version
> java version "1.8.0_181" Java(TM) SE Runtime Environment (build 1.8.0_181-b13) Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
> 
> ### Scala Version
> 2.12.x
> 
> ### StreamPark Version
> 2.1.3
> 
> ### Flink Version
> 1.15.3
> 
> ### deploy mode
> kubernetes-application
> 
> ### What happened
> k8s环境不稳定，导致flink pod自动重启，重启后flink任务恢复正常，但是streampark页面上显示任务状态为FAIL
> 
> ![image](https://private-user-images.githubusercontent.com/9477681/315194275-416c623c-0fae-45c9-bd96-72f35c4ee958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTE1NzYsIm5iZiI6MTcxMTAxMTI3NiwicGF0aCI6Ii85NDc3NjgxLzMxNTE5NDI3NS00MTZjNjIzYy0wZmFlLTQ1YzktYmQ5Ni03MmYzNWM0ZWU5NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDg1NDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIyNTFlMmUyZjQ4YmNlY2FmY2ZmMTFkMGQ3YmI2ZmYxODVjMjk0ZDlkNDI4YzRjODFiYzRlNWZhMjhlODRlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H2iZE4eLkwCvjZLEON7QyLPJFpb4nJIZ1o4FfMcznlw) ![image](https://private-user-images.githubusercontent.com/9477681/315194346-e608362a-6b2d-41e9-99fd-6540233b69d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTE1NzYsIm5iZiI6MTcxMTAxMTI3NiwicGF0aCI6Ii85NDc3NjgxLzMxNTE5NDM0Ni1lNjA4MzYyYS02YjJkLTQxZTktOTlmZC02NTQwMjMzYjY5ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMDg1NDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzgxNTMzNDYxZDk2MTBiMGExYzJjOTJkZjNlYzIwZTUxZDUzMGRlOGQ3MDJiNTllMzRlNzk2ZjVjODUwMzE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AkjbJWMl0ccQjWgaMxwJTJGZFz515WByHqGgWnTEH-Q)
> 
> 查看代码和日志，发现主要问题在于，watch进程在进行flink任务状态监听时，请求flink web接口出现异常，再去请求k8s api server判断deployment是否存在的时候也发生了异常(etcd server leader发生了变更)。这里KubernetesRetriever.isDeploymentExists逻辑存在问题，发生异常时返回false，即认为deployment不存在，但是实际这时候deployment是存在的。由于错误的识别到deployment不存在，于是把任务状态更新为FAIL，并且终止了任务的监听，即使后面k8s恢复，streampark上的任务状态也不会恢复。
> 
> 通过chaosblade工具模拟网络丢包，可以轻松的重现这个问题。 chaosblade文档见：[chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-network-loss](https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-network-loss)
> 
> 我这里的环境，k8s api server请求地址为[172.18.64.242:8443](https://172.18.64.242:8443), flink web接口的访问地址为https://172.18.64.242:443 于是我注入网络丢包的命令为：./blade create network loss --percent 100 --interface eth0 --remote-port 443,8443 --destination-ip 172.18.64.242 --timeout 200 简单解释下：这里是把请求到IP为172.18.64.242，端口为443和8443的网络请求丢包率设置为100%，持续200秒
> 
> 启动flink任务后，再通过命令注入网络故障，再查看streampark页面，就会发现任务状态变为FAIL，即使后面网络故障恢复，任务状态也不会恢复为RUNNING(期间flink任务本身一直正常工作)
> 
> ### Error Exception
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!(您是否要贡献这个PR?)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

针对这个问题，修改两处代码：
1、KubernetesRetriever.isDeploymentExists中的false改为true
![image](https://github.com/apache/incubator-streampark/assets/9477681/0f995e43-1ff7-4d37-808b-aa04e98c5650)
2、FlinkK8sChangeEventListener.subscribeJobStatusChange中FlinkAppState.isEndState(app.getState())为true则return的条件去掉
![image](https://github.com/apache/incubator-streampark/assets/9477681/4a707104-dfef-49d4-af04-b8f56a919f24)

改完以后重新打包替换，再进行故障测试，任务状态会RUNNGING -> FAILED -> RUNNING，网络故障恢复后任务状态也能自动恢复

**Comment by DimitriMok** [comment]
This resolves #3634

**Comment by DimitriMok** [comment]
This resolves #3634

**Comment by wolfboys** [comment]
fixed
