### ISSUE TITLE
[Bug] The diffirent team can not create the same git project name in project manager.

### ISSUE THREAD

**Issue by DimitriMok** [apache/streampark#3635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.3

### Flink Version

1.15.3

### deploy mode

None

### What happened

I found that when I create the same project which has same name in diffrent team, I receive the message that 'the project exists'.
But it is not show in my team but create in other team.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DimitriMok** [comment]
fixed in #3648

**Comment by caicancai** [comment]
Thank you
