### ISSUE TITLE
[Feature] support flink-1.19.0

### ISSUE THREAD

**Issue by 929359291** [apache/streampark#3637]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

streampark not support flink-1.19.0
![image](https://github.com/apache/incubator-streampark/assets/33850806/c0f4e66e-add7-45c3-84b0-baa88090ee59)
<img width="690" alt="1711596828059_704477EF-89D8-4087-A4EA-FCC1FA39E86E" src="https://github.com/apache/incubator-streampark/assets/33850806/5dfd1560-9cf9-4920-ad17-48123da9a6eb">

### Usage Scenario

111

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@929359291 It is true that flink1.19 is not currently supported, but the community will support it later.

**Comment by 929359291** [comment]
> @929359291 It is true that flink1.19 is not currently supported, but the community will support it later.

Look forward to

**Comment by wolfboys** [comment]
done
