### ISSUE TITLE
Streampark connects multiple hadoop clusters

### ISSUE THREAD

**Issue by znnyqqzyq** [apache/streampark#3651]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Streampark connects multiple hadoop clusters

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thank you for your feedback. Currently, we do not have plans to support this feature. We would happy to see developers contribute this feature.
