### ISSUE TITLE
k8s native session： flink sql： 运行失败

### ISSUE THREAD

**Issue by mydq** [apache/streampark#367]
### k8s native session
* ** main 最新
* ** 1.8
* **  centos 

### Bug Description（Bug 描述）

k8s native session 模式下， flink  sql ，运行报错

![image](https://user-images.githubusercontent.com/42607771/137898564-28af0a27-8426-45bc-99d1-a6215bdea413.png)

![image](https://user-images.githubusercontent.com/42607771/137898601-dab8aa23-1d78-4c33-8937-80f5a96a25ce.png)

配置如下：

![image](https://user-images.githubusercontent.com/42607771/137899224-ad5caf90-04b1-4170-a80e-5d3a8e059ce9.png)
![image](https://user-images.githubusercontent.com/42607771/137899089-d3b9f187-a749-4164-b822-7b96032f60e0.png)
![image](https://user-images.githubusercontent.com/42607771/137899119-355caf42-80cb-40d8-9c0a-03881dcc1c7a.png)
![image](https://user-images.githubusercontent.com/42607771/137899146-beeebb1a-f280-412b-a8ca-66215b44aac1.png)
![image](https://user-images.githubusercontent.com/42607771/137899160-6add7230-dc93-433c-a0cf-5b328f2128d3.png)

**Comment by Al-assad** [comment]
#368
