### ISSUE TITLE
[Improve] Check the validity of the Docker image

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#3672]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

<img width="1148" alt="image" src="https://github.com/apache/incubator-streampark/assets/13284744/da1e9ab1-60d0-40ac-8bfe-e5d2e9bc665e">

In Flink on k8s-session and k8s-app mode, users need to type the Flink image name. Currently, there is no validation check for the image's validity, such as whether the flink image exists. We need to improvement this: 

1. in the backend-java, we need create new method to check the image exists. 
2. In the frontend, the backend API should be called either when the user finishes entering the image name or when the form is submitted, If the check fails, need to provide prompt information.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
@wolfboys assign me
