### ISSUE TITLE
[Bug] Could not find how to raise issues with the website

### ISSUE THREAD

**Issue by sebbASF** [apache/streampark#3690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.11.x

### StreamPark Version

N/A

### Flink Version

N/A

### deploy mode

None

### What happened

Where should issues with the website be raised?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
You can raise website issues in this repository

**Comment by sebbASF** [comment]
As far as I can tell, none of the issue types are suitable. Which one should I use?

**Comment by sebbASF** [comment]
It would be a lot easier to raise website issues in the website repo, because one can then make use of the GitHub bug linking feature.

**Comment by wolfboys** [comment]
Thanks for your feedback, Already allowed website repos [issues](https://github.com/apache/incubator-streampark-website/pull/355)
