### ISSUE TITLE
[Bug] 从2.1.3升级到2.1.4，启动报sql错误

### ISSUE THREAD

**Issue by zhenyuT** [apache/streampark#3714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.15.3

### deploy mode

None

### What happened

从2.1.3升级到2.1.4，启动直接报错

![image](https://github.com/apache/incubator-streampark/assets/9477681/e152f49b-e4e2-49ec-a5c2-c352662fa387)

数据库使用的是pg

结合日志查看代码，定位到是org.apache.streampark.console.core.entity.Application类中代码存在问题：
![image](https://github.com/apache/incubator-streampark/assets/9477681/f6a0af93-d34f-492c-9ab2-4b34e40b95b4)
这里@TableField("`release`")中的"`"在pg中不合法

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
