### ISSUE TITLE
[Bug] pgsql 

### ISSUE THREAD

**Issue by hezhi3f** [apache/streampark#3719]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

java 8

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.18.1

### deploy mode

None

### What happened

use pgsql

### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: operator does not exist: ` smallint
  Hint: No operator matches the given name and argument type. You might need to add an explicit type cast.
  Position: 134
### SQL: SELECT  id,team_id,job_type,project_id,user_id,job_name,job_id,job_manager_url,version_id,cluster_id,flink_image,k8s_namespace,state,`release`,build,restart_size,restart_count,option_state,alert_id,args,module,options,hot_params,resolve_order,exec
ution_mode,dynamic_properties,app_type,tracking,jar,jar_check_sum,main_class,dependency,start_time,end_time,duration,cp_max_failure_interval,cp_failure_rate_interval,cp_failure_action,TOTAL_TM,total_slot,available_slot,jm_memory,tm_memory,total_task,flink_
cluster_id,create_time,option_time,modify_time,k8s_rest_exposed_type,k8s_pod_template,k8s_jm_pod_template,k8s_tm_pod_template,ingress_template,default_mode_ingress,resource_from,k8s_hadoop_integration,tags,description  FROM t_flink_app     WHERE (tracking
= ? AND execution_mode NOT IN (?,?))

org.apache.streampark.console.core.task.FlinkAppHttpWatcher.initialize()
there is a `release` make error, I saw org.apache.streampark.console.base.mybatis.interceptor.PostgreSQLPrepareInterceptor handle '`' 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezhi3f** [comment]
'`'

**Comment by hezhi3f** [comment]
org.apache.streampark.console.core.entity.Application
```
 @TableField("`release`")
```

**Comment by wolfboys** [comment]
fixed. https://github.com/apache/incubator-streampark/issues/3714
