### ISSUE TITLE
Dingtalk告警配置异常问题

### ISSUE THREAD

**Issue by supergenge** [apache/streampark#3727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.11.x

### StreamPark Version

2.1.1

### Flink Version

1.17

### deploy mode

yarn-application

### What happened

Alarm Setting, 选择DingTalk时，DingTalk Url不能配置配置了就会提示token不存在的错误，我这边配置的是群机器人的Webhook
报错前：
![image](https://github.com/apache/incubator-streampark/assets/27846806/ce96bc69-38f4-47b3-b839-c0df20441b0a)
![image](https://github.com/apache/incubator-streampark/assets/27846806/90b0f993-12e2-4cf7-a32c-a0887cdd824b)
清除DingTalk url过后：
![image](https://github.com/apache/incubator-streampark/assets/27846806/c8313766-207c-4ce3-ab21-e49d68a5ca5c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can try setting like this ![MYpfeZbR7ykJoF5.png](https://cdn.sa.net/2024/05/31/MYpfeZbR7ykJoF5.png)

**Comment by wolfboys** [comment]
fixed.
