### ISSUE TITLE
[Bug] There was a malfunction with the Docker environment configuration feature when deploying Streampark on a k8s cluster.

### ISSUE THREAD

**Issue by SoWhat-ET** [apache/streampark#3742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.16.2

### deploy mode

None

## 1 Deploying on K8S according to the official guide
https://github.com/apache/incubator-streampark/tree/release-2.1.4/helm#readme

## 2 Error occurred when trying to log in to the system and configure the Docker service.
![image](https://github.com/apache/incubator-streampark/assets/62318683/63b3b336-c03b-4cc9-9cf7-d075bb82a569)
Failed to validate Docker registry, error: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:2375 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

## 3 I looked up relevant information and asked the LLM:

Q:
Error encountered while configuring Docker repository after successful deployment： 
`Failed to validate Docker registry, error: org.apache.hc.client5.http.HttpHostConnectException: Connect to [http://localhost:2375](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) [localhost/127.0.0.1] failed: Connection refused (Connection refused)`

是否需要修改`helm/streampark/values.yaml` 文件中的 `{ name: DOCKER_HOST, value: "tcp://localhost:2375" }`

A:
This configuration sets the environment variable DOCKER_HOST to tcp://localhost:2375, which means your application will try to connect to the Docker API on localhost:2375.

In Kubernetes, each Pod has its own network namespace, so localhost refers to the Pod itself, not the node. That's why your application can't find the Docker API on localhost:2375.

If you've enabled the Docker API on the node and want your application to access it, you need to change the value of DOCKER_HOST to the node's IP and Docker API port. For example, if your node's IP is 192.168.1.100, you can set the DOCKER_HOST value to tcp://192.168.1.100:2375.

Note that this is just an example. You need to replace 192.168.1.100 with your actual node IP.

Additionally, you need to make sure your application has permission to access the node's network. This might require setting hostNetwork: true in the Pod's specification.

Be aware that enabling the Docker API and using hostNetwork can pose security risks. You should ensure your network security and enable these options only in a trusted network.

### Error Exception

```log
Failed to validate Docker registry, error: org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:2375 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
```

### Screenshots

![image](https://github.com/apache/incubator-streampark/assets/62318683/f145bfc4-36c0-4207-81c9-7174055e4400)
![image](https://github.com/apache/incubator-streampark/assets/62318683/63b3b336-c03b-4cc9-9cf7-d075bb82a569)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
You can try using `docker login ${dockerUrl}` to test it locally. @SoWhat-ET

**Comment by zzj-always** [comment]
我在k8s上启动的一个streampark的pod，没有使用配置的docker的服务器

**Comment by zzj-always** [comment]
同样的问题 ，我是在k8s上启动的streampark的pod，但是没有连接上我物理机上的docker服务

**Comment by lintingbin** [comment]
@SbloodyS docker login ${dockerUrl}可以执行成功，但是就是会报这个错误。进去容器里面看端口，也没有发现有2375的端口。2.0.0版本的时候k8s部署是成功的，也可以打镜像，升级到2.1.4后就报这个错误了。

**Comment by 617450941** [comment]
2.1.4确实有这个问题
![Uploading image.png…]()

**Comment by 617450941** [comment]
2.1.4确实有这个问题
![image](https://github.com/user-attachments/assets/220df193-a404-45d8-8715-fae8cb5cc9d1)

**Comment by 617450941** [comment]
k8s 上部署的

**Comment by lintingbin** [comment]
可能是containerd不兼容的问题，我们目前的解决方案是自己在外部部署一个docker，开放2375的端口，把环境变量改成指向外部的这个docker。

**Comment by 617450941** [comment]
我的k8s 底层是docker的

**Comment by 617450941** [comment]
2375不知道是什么端口来的

**Comment by 617450941** [comment]
试了那么多flink 作业平台 没一个好用的 不是这bug就是文档不全 无法正常使用
