### ISSUE TITLE
添加ambari自定义服务

### ISSUE THREAD

**Issue by smileyboy2019** [apache/streampark#3744]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

安装部署是不是可以支持ambari 添加服务

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, We have no plan to implement this feature.
