### ISSUE TITLE
Code snippets supporting zeppelin

### ISSUE THREAD

**Issue by smileyboy2019** [apache/streampark#3745]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Can we support code snippets similar to zeppelin, support context, and assign tasks to the scheduling platform for scheduling

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Thanks for your feedback, We have no plan to implement this feature.
