### ISSUE TITLE
[Bug] 无法创建Flink SQL任务

### ISSUE THREAD

**Issue by mezhangremoterepository** [apache/streampark#3750]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.1.2
2.1.3
2.1.4

### Flink Version

1.18.1

### deploy mode

None

### What happened

大佬好，
2.1.2
2.1.3
2.1.4
版本均无法在Flink SQL文本框中编辑，导致均无法创建Flink SQL任务，我看没人报告这个问题，大佬给个排查方向吧，是权限控制导致的吗？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bigdata-zhang** [comment]
我们 都可以创建 flink sql任务， 还可以编辑 你至少得放点 截图 还有日志进来吧

**Comment by mezhangremoterepository** [comment]
请大佬忽略，堡垒机内浏览器版本过老，前端不适配导致的
