### ISSUE TITLE
[Feature] Docker-compose yaml with spark and flink

### ISSUE THREAD

**Issue by moresun** [apache/streampark#3787]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

StreamPark can support flink and spark. I successed to run docker-compose for flink. But I need to run both in the same yaml.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
> I need to run both in the same yaml.

The community currently has no plans to support spark running in Docker. If you have any opinions, please email us to discuss it.
