### ISSUE TITLE
[Discussion] Support generate flink job process logic by dragging and dropping

### ISSUE THREAD

**Issue by litiliu** [apache/streampark#3800]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, [streampark] only supports defining the data process logic by Flink SQL, it's good. However, some non-professional users prefer to describe the data process by dragging and dropping. And most of the use cases are simple ETL(Source, Map, Filter, Sink) logic.    It can make stream processing easier.

### Usage Scenario

Some non-professional users prefer to describe the data process by dragging and dropping. And most of the use cases are simple ETL(Source, Map, Filter, Sink).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Currently, the community does not have any plans. You are welcome to keep up with the community updates.
