### ISSUE TITLE
[Feature] Support gradle in project build

### ISSUE THREAD

**Issue by xiaows08** [apache/streampark#3814]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Build project support gradle like maven.
In many Flink job project, there are many job in one or more submodule, but those project is managed by gradle(`build.gradle[.kts]/settings.gradle[.kts]`), can we build it like maven project? (just different build command) ^.^

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
The streampark community has no plan for this yet, but it is a good suggestion. If you can contribute this feature, we will be happy to accept it.
