### ISSUE TITLE
[Bug] The application is always falling and cannot be stopped

### ISSUE THREAD

**Issue by SamuelBin** [apache/streampark#3836]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.2

### Flink Version

1.14.5

### deploy mode

None

### What happened

![image](https://github.com/apache/incubator-streampark/assets/34790156/29046a75-34a3-459a-a867-02c41e1d6d9c)

The application is always falling and cannot be stopped

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SbloodyS** [comment]
Can you provide more logs?

**Comment by wolfboys** [comment]
Please provide info about the error.
