### ISSUE TITLE
UnknownHostException: repo.maven.apache.org

### ISSUE THREAD

**Issue by sumghost** [apache/streampark#3925]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

jdk1.8.0_212

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.18.1

### deploy mode

yarn-application

### What happened

![2](https://github.com/user-attachments/assets/bb6bc3f8-2a34-44a0-968e-3a1161bfa42f)

Revised sentence: "When packaging the build project, I consistently encounter a prompt indicating that the host name cannot be resolved. In my settings.xml file, I have only configured the local repository without any remote repository and specified <offline>true</offline>. What could be causing this issue?"

### Error Exception

```log
2024-07-29 17:53:49.550 INFO  - Exception in thread "main" java.net.UnknownHostException: repo.maven.apache.org
2024-07-29 17:53:49.551 INFO  - 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zjialin** [comment]
我也遇到了同样的问题，不知晓如何解决

**Comment by wolfboys** [comment]
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/55412688-01ce-49db-a6a8-e6d796849d69">

You can specify the Maven setting.xml file and configure the repository in the setting.xml, such as:

```
<repository>
        <id>central</id>
        <name>Central Repository</name>
        <ur1>https://repo .maven.apache.org/maven2</ur1>
        <layout>default</layout>
        <snapshots>
        <enabled*false</enabled></snapshots>
</repository>

```
