### ISSUE TITLE
[Feature] Add proxy for flink web ui

### ISSUE THREAD

**Issue by lintingbin** [apache/streampark#3930]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Most Kubernetes and YARN cluster machines do not have a public IP, making it difficult to access the Flink Web UI. Adding a proxy in StreamPark can facilitate access to the Flink Web UI even when the cluster does not have a public IP.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
done
