### ISSUE TITLE
[Feature] Add registy module for streampark

### ISSUE THREAD

**Issue by SbloodyS** [apache/streampark#3934]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Registrar SPI, the user can specify the registration center method and specific related parameters in the configuration file. Zookeeper is used by default

todo list:

1. Provide a unified `RegistryClient` related interface (org.apache.streampark.registry), Including registration, offline, update and other operations. The external access registration center uniformly calls the Client interface.
The registration center currently only provides two registration center(MySql & Zookeeper). We need to load the corresponding plug-in according to the user configuration. When the user does not specify it, zookeeper is used by default.

At the same time, in order to transition, we need to provide the implementation of distributed locks. (This is just for transition)

2. Implementation of Zookeeper in the registry

3. Implementation of MySql in the registry 

4. Console Server supports the registration center. The console server must share the same registry with each other, and multiple registries are not currently supported.

## Function

SP use registry to do the below three things:

1. Store the metadata of console so that it can get notify when nodes up and down.
2. Store the metadata of console to do load balance.
3. Acquire a global lock when do failover.

So for SP, the registry need to notify the server when the server subscribe data have added/deleted/updated, support a way to create/release a global lock,
delete the server's metadata when server down.

## How to use

At present, we have implements two registry: Zookeeper(Default),Mysql. If you
want to use them, you should config it at resource/application.yaml. The configuration details
can be viewed in the README of plugin under Module streampark-registry-plugins

### streampark-registry-all

This module is used for exporting the implementation of registry.
If you want to add new registry,you should add the dependency in the pom.xml

### streampark-registry-api

This module contains the relevant interfaces involved in the use of the registry.
The following are several important interfaces
1. Registry Interface: If you want to implement your own registry, you just need to implement this interface
2. ConnectionListener Interface: This interface is responsible for the connection status between the client and the registry,
The connection state can be viewed in ConnectionState.java
3. SubscribeListener Interface: This interface is responsible for monitoring the state changes of child nodes under the specified prefix.
Event content can be viewed in event.java

### streampark-registry-plugins

This module contains all registry implementations in SP

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Mrart** [comment]
Based on the above design, we need to add a unified distributed lock interface, but also support zookeeper, mysql and other middleware， Jobs submitted by users may be clicked multiple times and executed on different nodes, requiring distributed locking support.

**Comment by wolfboys** [comment]
Thanks for your driving. At present, we need to clarify the role of the registration center. Let's reach an agreement first.

I understand that we need to implement two core capabilities: registration and subscription:

1. Registration: console-server report node info (e.g: mac + server_host + server_port) or job info (e.g: appId) to the registration center. The info will be stored in Mysql or Zookeeper

2. Subscription & Notification: This is the core capability; if a console-server node shuts down or can not work, the registration center needs to push the info to all other registered nodes in a timely manner. 

Do I understand the core competencies of this module correctly? If not, please discuss

**Comment by SbloodyS** [comment]
> Thanks for your driving. At present, we need to clarify the role of the registration center. Let's reach an agreement first.
> 
> I understand that we need to implement two core capabilities: registration and subscription:
> 
> 1. Registration: console-server report node info (e.g: mac + server_host + server_port) or job info (e.g: appId) to the registration center. The info will be stored in Mysql or Zookeeper
> 2. Subscription & Notification: This is the core capability; if a console-server node shuts down or can not work, the registration center needs to push the info to all other registered nodes in a timely manner.
> 
> Do I understand the core competencies of this module correctly? If not, please discuss

Yes. Your understanding coincides with mine.
