### ISSUE TITLE
[Feature] support flink 1.20.

### ISSUE THREAD

**Issue by Mrart** [apache/streampark#3940]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

support flink 1.20.

### Usage Scenario

support flink 1.20.

### Related issues

support flink 1.20.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Kick156** [comment]
I would like to try to contribute this.

**Comment by Mrart** [comment]
@Kick156  Try it， I will help you review.

**Comment by wolfboys** [comment]
done
