### ISSUE TITLE
[Improvement] The thread pool did not set queue size and expiration policy, resulting in OOM

### ISSUE THREAD

**Issue by hezhi3f** [apache/streampark#3947]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22improvement%22) and found no similar issues.

### Java Version

8

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.17.2

### deploy mode

yarn-session

### What happened

java.lang.OutOfMemoryError GC overhead limit exceeded.

Using jviewvm.exe to parse dump. hprof.
it was found to be 
`java.util.current LinkedBlockingQueue $Node`, 
`org. space. stresmpsrk.console.core.task.FlinkAppHttpWatcher$$Lambda$2896` 
occupies 86.2% of the heap memory size. 
Tracing has found that it is org. apache.streampark.console.core.task.FlinkAppHttpWatcher.
The ExecutorService watchExecutor does not have queue size and rejection policies set, 
but the issue of why the thread pool is stuck has not been found yet.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hezhi3f** [comment]
Why can't I upload screenshots!
You can see a screenshot in the chat record of the WeChat group Streampark社区群4 at 1 2024-08-07 13:38!

**Comment by wolfboys** [comment]
You can adjust the parameters in /bin/jvm_opts.sh in an attempt to resolve your issue. In addition, if your job is deployed on YARN, you must ensure that your Hadoop YARN services are not overloaded
