### ISSUE TITLE
[Bug] Kerberos authentication issues may occur in Flink on YARN mode.

### ISSUE THREAD

**Issue by Tidra** [apache/streampark#3949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.4

### Flink Version

1.16.2

### deploy mode

yarn-session

### What happened

Kerberos authentication cannot be achieved in the following scenarios:
1. Another user authenticated using the `kinit` command on the host machine, causing user permission changes.
2. StreamPark program is terminated and restarted without the host machine using the `kinit` command for authentication, resulting in the inability to execute functions such as stopping, canceling, and submitting in Flink on YARN.

Kerberos认证会在以下几种情况中无法实现：
1. 宿主机中使用了 `kinit` 命令认证了其他用户，导致用户权限变更
2. StreamPark 程序被终止再重启后，且宿主机未使用 `kinit` 命令获取认证，flink on yarn 中止、取消、提交等相关功能都无法实现

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
done
