### ISSUE TITLE
Scheduled tasks

### ISSUE THREAD

**Issue by damokelis** [apache/streampark#3957]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In StreamPark, when using Flink batch processing, I would like to schedule a job to run once a day. Currently, there is no built-in functionality for scheduling executions. I believe this feature should be achievable and is a fairly common use case.

### Usage Scenario

using Flink batch processing

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
There is currently no plan for this feature in the community. However, if you would like to contribute it, we would be more than happy to accept it.
