### ISSUE TITLE
[Bug]Checkpoint does not update automatically

### ISSUE THREAD

**Issue by chengyuan1029** [apache/streampark#3961]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.0_311

### Scala Version

2.12.x

### StreamPark Version

2.1.5

### Flink Version

1.17.0

### deploy mode

yarn-application

### What happened

I found that the checkpoint is not automatically updated and saved, occasionally it works, but most of the time it doesn't work and won't automatically update and save the checkpoint. Currently, I am using Flinksql and submitting in yarn application mode. Could you please help me take a look? What could be the possible reason?
![image](https://github.com/user-attachments/assets/bd891ae6-2ee9-4ea5-b972-a183dcdda943)

### Error Exception

```log
There are no obvious errors in the log, only the alarms related to the database are as follows. Will this alarm have any impact? How to eliminate this alarm?
```

### Screenshots

![image](https://github.com/user-attachments/assets/5e8baced-0cd7-44f4-ae2f-bec8c44ddc54)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
This is a known bug that has been fixed in version 2.1.5. Please refer to this [issue](https://github.com/apache/incubator-streampark/issues/3964)
