### ISSUE TITLE
使用yarn 提交任务找不到客户端类

### ISSUE THREAD

**Issue by xmm19960824** [apache/streampark#3963]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Scala Version

2.12.x

### StreamPark Version

2.14

### Flink Version

1.18

### deploy mode

yarn-application

### What happened

使用yarn application模式 提交任务找不到客户端类
![image](https://github.com/user-attachments/assets/e19c5e53-eb7f-4eb5-867b-e93297096d50)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please ensure that the job's Flink version and its related dependencies are compatible.
