### ISSUE TITLE
[WIP][Feature] Support Flink 1.20 application submit

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#3976]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support Flink 1.20 application submit

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by muchunjin** [comment]
@lizh501 I hope you can contribute this feature.

**Comment by lizh501** [comment]
> @lizh501 I hope you can contribute this feature.

I am glad to do it. Thank you.

**Comment by muchunjin** [comment]
> > @lizh501 I hope you can contribute this feature.
> 
> I am glad to do it. Thank you.



> > @lizh501 I hope you can contribute this feature.
> 
> I am glad to do it. Thank you.

After 2.1.5 is released, the release-2.1.5 code branch will be generated. The dev-2.1.6 branch will be pulled from release-2.1.5, and then development will be carried out based on dev-2.1.6.

**Comment by muchunjin** [comment]
> > > @lizh501 I hope you can contribute this feature.
> > 
> > 
> > I am glad to do it. Thank you.
> 
> > > @lizh501 I hope you can contribute this feature.
> > 
> > 
> > I am glad to do it. Thank you.
> 
> After 2.1.5 is released, the release-2.1.5 code branch will be generated. The dev-2.1.6 branch will be pulled from release-2.1.5, and then development will be carried out based on dev-2.1.6.

After completing this work, merge it into dev-2.1.6 and dev branches.

**Comment by lizh501** [comment]
> > > @lizh501 I hope you can contribute this feature.
> > 
> > 
> > I am glad to do it. Thank you.
> 
> > > @lizh501 I hope you can contribute this feature.
> > 
> > 
> > I am glad to do it. Thank you.
> 
> After 2.1.5 is released, the release-2.1.5 code branch will be generated. The dev-2.1.6 branch will be pulled from release-2.1.5, and then development will be carried out based on dev-2.1.6.

Roger that.

**Comment by lizh501** [comment]
> > > > @lizh501 I hope you can contribute this feature.
> > > 
> > > 
> > > I am glad to do it. Thank you.
> > 
> > 
> > > > @lizh501 I hope you can contribute this feature.
> > > 
> > > 
> > > I am glad to do it. Thank you.
> > 
> > 
> > After 2.1.5 is released, the release-2.1.5 code branch will be generated. The dev-2.1.6 branch will be pulled from release-2.1.5, and then development will be carried out based on dev-2.1.6.
> 
> After completing this work, merge it into dev-2.1.6 and dev branches.

OK, I will follow.

**Comment by wolfboys** [comment]
done
