### ISSUE TITLE
[Improvement] Job dependencies limit the default number of uploaded jars

### ISSUE THREAD

**Issue by jianjun159** [apache/streampark#3983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22improvement%22) and found no similar issues.

### Java Version

jdk8

### Scala Version

2.12.x

### StreamPark Version

dev

### Flink Version

flink 1.18.1

### deploy mode

kubernetes-application

### What happened

When I need to rely on external jars, because there are so many jars on the platform that I can't get any more than 25 jars, I want to put this limit in the setttings configuration and let the user decide how many dependencies to display or limit the number

### Screenshots

![image](https://github.com/user-attachments/assets/bfb7c9a8-f6dd-480e-a581-51084f0a5e0e)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
done
