### ISSUE TITLE
[Bug] Version 2.1.5 proxy link issue

### ISSUE THREAD

**Issue by OneTian1211** [apache/streampark#4119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

2.1.5

### Flink Version

flink1.16.2

### deploy mode

yarn-application

### What happened

Version 2.1.5 proxy link issue,Please refer to the screenshot for details.

### Screenshots

![image](https://github.com/user-attachments/assets/6e85c148-f374-4d97-be99-764c74d62b58)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
The description is unclear, please provide more information

**Comment by OneTian1211** [comment]
![Image](https://github.com/user-attachments/assets/fddd672c-8039-4407-9991-98206096f10c)

就是点击页面右上角的这个按钮跳转失败
