### ISSUE TITLE
我下载的dev版本提示缺一些依赖。源码启动不了。

### ISSUE THREAD

**Issue by 13093975260** [apache/streampark#4132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8+

### Scala Version

2.12.x

### StreamPark Version

2.12

### Flink Version

3.x

### deploy mode

None

### What happened

我下载的dev版本提示缺一些依赖。源码启动不了。

### Error Exception

```log
D:\MyBigData\incubator-streampark-dev\streampark-flink\streampark-flink-packer\src\main\java\org\apache\streampark\flink\packer\pipeline\PipelineTypeEnum.java:100:35
java: 找不到符号
  符号:   类 BuildResult
  位置: 类 org.apache.streampark.flink.packer.pipeline.PipelineTypeEnum
```

### Screenshots

![streampark-dev缺少部分依赖8](https://github.com/user-attachments/assets/d227cb1c-cacf-4124-ba8d-3ab3f4bfc86a)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
You should compile the project first and then try to start it. The local development environment causes this case.
