### ISSUE TITLE
[Bug] Failed to update savepoint status

### ISSUE THREAD

**Issue by succw** [apache/streampark#4134]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### Java Version

1.8.

### Scala Version

2.11.x

### StreamPark Version

2.1.1

### Flink Version

1.17.1

### deploy mode

None

### What happened

From version 2.1.1 to 2.1.5 update

### Error Exception

```log
### The error may exist in class path resource [mapper/core/SavepointMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: update t_flink_savepoint         set latest = 0         where app_id = ?
### Cause: org.postgresql.util.PSQLException: ERROR: column "latest" is of type boolean but expression is of type integer
  Hint: You will need to rewrite or cast the expression.
  Position: 47
]

---

UPDATE t_flink_savepoint
SET latest = CAST(0 AS BOOLEAN)  -- Explicitly cast 0 to BOOLEAN
WHERE app_id = ?;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed. https://github.com/apache/incubator-streampark/commit/8dab676feaec9db27c6abd3b7e4ae63cd7a217b4
