### ISSUE TITLE
[Improvement] The start time may be null

### ISSUE THREAD

**Issue by Forus0322** [apache/streampark#4140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22improvement%22) and found no similar issues.

### Java Version

1.8

### Scala Version

2.12.x

### StreamPark Version

dev

### Flink Version

1.17

### deploy mode

None

### What happened

The calculation duration ignores the condition that only start is null.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!(您是否要贡献这个PR?)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
