### ISSUE TITLE
[Bug] [main branch] can not get application conf on web ui

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/streampark#521]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: main branch
* **JVM version** (`java -version`): 1.2.1
* **OS version** (`uname -a` if on a Unix-like system):centos

### Bug Description

can not get flink application config on the web UI:

Development Mode : flink sql
Execution Mode : k8s application

### How to Reproduce 
Steps to reproduce the behavior, for example:

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.

**Comment by wolfboys** [comment]
fixed in new version
