### ISSUE TITLE
[Bug] can not add custom k8s Pod Template 

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/streampark#522]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: main branch
* **JVM version** (`java -version`): 1.8
* **OS version** (`uname -a` if on a Unix-like system): centos 

### Bug Description

can edit the k8s Pod Template  and add the hostalias in follow mode:
- Development Mode : custom code
- Execution Mode : k8s application
- Resource From : upload 

### How to Reproduce 
Steps to reproduce the behavior, for example:

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.

**Comment by wolfboys** [comment]
supported in new version
