### ISSUE TITLE
[Bug] Submit the same job multiple times and job status become lost

### ISSUE THREAD

**Issue by hackallan** [apache/streampark#525]
### Environment Description
* **StreamX Version**: 1.2.0
* **JVM version** (`java -version`):1.8.0_131
* **OS version** (`uname -a` if on a Unix-like system): 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Bug Description

When the job status changes to Lost, n identical jobs will be restarted according to the number of restarts, but the flink job did not die

### How to Reproduce
1. start a new job
2. Restart the YARN cluster or the job becomes Lost due to some reasons
3. N identical jobs are displayed in the YARN Application list

### Requirement or improvement
- hope to  fix this problem

**Comment by wolfboys** [comment]
fixed
