### ISSUE TITLE
[Enhancement] In the form of creating kubernetes application, it is recommended to verify the Kuberntes ClusterId parameter according to the naming convention of k8s deployment

### ISSUE THREAD

**Issue by xinzhuxiansheng** [apache/streampark#526]
## 优化建议（Enhancement）

![图片](https://user-images.githubusercontent.com/7881241/146480941-c999f492-f816-461d-b3ac-3d242fae2a60.png)

In the form of creating kubernetes application, it is recommended to verify the Kuberntes ClusterId parameter according to the naming convention of k8s deployment

在创建 kubernetes application的表单中，建议按照k8s的deployment的命名规范校验Kuberntes ClusterId 参数， 可以避免等作业部署失败了才通知用户

**Comment by xinzhuxiansheng** [comment]
assign to me

**Comment by wolfboys** [comment]
> assign to me

good job.

**Comment by Al-assad** [comment]
good idea 😃

**Comment by xinzhuxiansheng** [comment]
refer to this PR , https://github.com/streamxhub/streamx/pull/556
