### ISSUE TITLE
[Enhancement] StreamX Data Studio Feature

### ISSUE THREAD

**Issue by Al-assad** [apache/streampark#563]
### StreamX Data Studio Feature

For StreamX's Data Studio feature proposal, I have roughly designed a set of Figma prototypes.
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/22493821/147574396-78ff3d90-8c85-4494-b148-3886c1de2b71.png">

![Data Source](https://user-images.githubusercontent.com/22493821/147573942-803a05d5-7bcc-4eac-9e24-efe3b68090d3.png)

The Data Studio is mainly oriented to interactive data development scenarios, providing a collection of features for Flink SQL automatic completion, metadata integration, data lineage, data preview and cluster management . 
  
It contains the following 3 main combination modules:
* **Data Studio**: Provides interactive data development capabilities.
* **Data Source**:  Provide metadata integration and management capabilities.
* **Cluster Center**: Provide Flink cluster deployment and management capabilities.

<br>

###  Online Prototype
You can experience this interactive prototype directly through the following link:
[https://www.figma.com/file/IuLLEvfkyVhBB4SCjeaF1J/Data-Studio?node-id=0%3A1](https://www.figma.com/file/IuLLEvfkyVhBB4SCjeaF1J/Data-Studio?node-id=0%3A1)

<br>

### Further Discussion
I have not fully planned for the implementation of this feature and may need more than one person to help complete the plan, which we can discuss further in the current issue or in Github Discussion #565  in Chinese.

  <br>

**Comment by Narcasserun** [comment]
+1

**Comment by caicancai** [comment]
finish, close
