### ISSUE TITLE
[Bug] java.sql.SQLSyntaxErrorException: Table 'streamx.t_setting' doesn't exist

### ISSUE THREAD

**Issue by edwardhuanghz** [apache/streampark#569]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**:  streamx-console-service-1.2.1
* **JVM version** (`java -version`):
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

* **OS version** (`uname -a` if on a Unix-like system):
Linux app-xx 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Bug Description（Bug 描述）
请简要、清晰地对您遇到的 Bug 进行描述。
执行/opt/streamx/streamx-console-service-1.2.1/bin/startup.sh 初始化安装报错
报错如下
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### How to Reproduce（如何重现这个 Bug） 
1.更改/conf/application.yml配置文件
2.修改hadoop env参数
export HADOOP_HOME=/opt/cloudera/parcels/CDH-6.3.2-1.cdh6.3.2.p0.1605554/lib/hadoop
export HADOOP_CONF_DIR=/etc/hadoop/conf
export HIVE_CONF_DIR=/etc/hive/conf

3.执行startup.sh报错

### Additional context（额外的上下文信息）
添加额外有助于描述该问题的上下文信息，如 JVM 堆栈日志等

### Requirement or improvement（诉求 & 改进建议）
版本的文档希望更新下,谢谢~

**Comment by xinzhuxiansheng** [comment]
@edwardhuanghz   Please refer to FAQ doc https://github.com/streamxhub/streamx/issues/507

**Comment by edwardhuanghz** [comment]
thankyou verymuch
