### ISSUE TITLE
streamx console integrated Dingding group robot alarm function

### ISSUE THREAD

**Issue by haoziaigemao** [apache/streampark#579]
## Feature Request

**Is your feature request related to a problem? Please describe:**
streamx console  integrated Dingding group robot alarm function

**Describe the feature you'd like:**
After the task error is reported, the nail group robot alarm function is added on the basis of the original mail alarm

**Teachability, Documentation, Adoption, Migration Strategy:**

streamx/streamx-console/streamx-console-service/src/main/resources/application.yml file add the follow config
streamx:
  dingding:
    enabled: false
    secret:
    accessToken:
    url: https://oapi.dingtalk.com/robot/send?access_token=%s&timestamp=%s&sign=%s

Add Dingding alarm code in AlertServiceImpl.java alarm logic, alarm according to streamx.dingding.enabled = true, the default is false

**Comment by wolfboys** [comment]
supported
