### ISSUE TITLE
[Feature] New Official website construction

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#586]
## New Official website construction

At present, the overall structure of the new official website project has been completed, and the following work needs to be done:

1. The documents in the old official website project need to be migrated to the new official website

2. It is necessary to collect  "users" and improve the user module

3. more usage document.

current official website project:  https://github.com/streamxhub/streamx-docs

new  official  website  project:    https://github.com/streamxhub/streamx-website

-----

目前全新官网项目在大的框架上已经完成, 还有一些工作需要做:

1. 将老官网项目里的文档迁移至新的官网项目中
2. 收集使用用户,完善用户模块
3. 编写更多StreamX的使用文档

老的官网项目:     https://github.com/streamxhub/streamx-docs

全新官网项目:    https://github.com/streamxhub/streamx-website

新的官网项目是基于[docusaurus](https://docusaurus.io/) 是一个更专业的新一代开源项目建站框架,相关使用文档: https://docusaurus.io/docs

![StreamX-StreamX](https://user-images.githubusercontent.com/13284744/148558758-5f67cef4-35ae-4b41-b899-17931b39c400.png)

**Comment by chenshuai1995** [comment]
please assign to me

**Comment by HugoSayHi** [comment]
please assign to me +1

**Comment by wolfboys** [comment]
done
