### ISSUE TITLE
[Feature] add Dynamic Table Options support 

### ISSUE THREAD

**Issue by zhangjun0x01** [apache/streampark#591]
## Feature Request

I think we should add the Dynamic Table Options support for flink sql,like
  `select id, name from kafka_table1 /*+ OPTIONS('scan.startup.mode'='earliest-offset') */;`

Now, when we are writing the Flink SQL job with dynamic table option, the parser will throw an exception

the link is https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/queries/hints/

**Comment by wolfboys** [comment]
supported
