### ISSUE TITLE
[Bug] k8s application flinksql mode maven pom does not work 

### ISSUE THREAD

**Issue by edwardhuanghz** [apache/streampark#593]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**:  1.2.1
* **JVM version** (`java -version`): 1.8
* **OS version** (`uname -a` if on a Unix-like system):  centos 7.6
 Linux app-01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Bug Description
1. k8s application flinksql mode maven pom does not work,
when i added same jars  by Dependency Maven pom or upload jar,such as flink-sql-connector-kafka_2.11-1.14.2.jar. .
auto generate Dockerfille 
CP lib $FLINK_HOME/lib/ does not works

2. anyway ,i try another way ,i build  a images with depency jars,also does not work ,i suggest
CP lib $FLINK_HOME/lib/  need change to 
CP lib/*  FLINK_HOME/lib/ 

### How to Reproduce 
Steps to reproduce the behavior, for example:

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.

**Comment by wolfboys** [comment]
fixed in new version
