### ISSUE TITLE
Project name cannot be reused

### ISSUE THREAD

**Issue by oiupoiupga1** [apache/streampark#594]
After the streamx project is created and deleted, the old name cannot be used again.

**Comment by xinzhuxiansheng** [comment]
please assign to me

**Comment by wolfboys** [comment]
> please assign to me

good job! 👍 👏

**Comment by xinzhuxiansheng** [comment]
@oiupoiupga1  The problem cannot be reproduced in the dev branch And compare with the v1.2.0 version code, this problem should not occur .  Can you add more scenes? Or environmental information? Let's try to reproduce the problem。
