### ISSUE TITLE
flink sql提交依赖外部包  并没有添加到真实环境里

### ISSUE THREAD

**Issue by honghaoli9898** [apache/streampark#597]
![image](https://user-images.githubusercontent.com/43817517/149053824-1fc4240b-0d83-4989-8b67-137f2019860c.png)
![image](https://user-images.githubusercontent.com/43817517/149053862-81787300-ae40-4695-b7c1-42dab2e125ad.png)

**Comment by wolfboys** [comment]
请按照反馈格式,按照英文反馈问题.
