### ISSUE TITLE
[Bug]streamx sql on yarn application,but no upload dependency is brought into the program

### ISSUE THREAD

**Issue by honghaoli9898** [apache/streampark#599]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**:  1.2.0
* **JVM version** (`java -version`): jdk.1.8.0_192
* **OS version** (`uname -a` if on a Unix-like system): CentOS Linux release 7.6.1810

### Bug Description（Bug 描述）
请简要、清晰地对您遇到的 Bug 进行描述。
After uploading the external dependency, running SQL on yarn does not bring the package in the dependency upload into

### How to Reproduce（如何重现这个 Bug） 
重现 Bug 现场的步骤，比如：
1. Use the official SQL demo and upload the jar.
2. Click on run
3. View yarn log
4. search yarn.provided.lib.dirs,but The dependent package in upload is not included

### Additional context（额外的上下文信息）
添加额外有助于描述该问题的上下文信息，如 JVM 堆栈日志等
![image](https://user-images.githubusercontent.com/43817517/149058478-e60875c1-5c74-477d-8c9f-41bcf835ca3e.png)
![image](https://user-images.githubusercontent.com/43817517/149058538-5e5196c1-6863-4edd-8b32-16646276837d.png)

### Requirement or improvement（诉求 & 改进建议）
I analyzed the source code. On line 170 of YarnApplicationSubmit.scala .No upload package included

- 请描述您的诉求，或者对此的改进建议

**Comment by wolfboys** [comment]
fixed
