### ISSUE TITLE
StreamX 1.3.0 roadmap

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#602]
At present, StreamX has completed the hosting of flink tasks. This part of the work is very important and difficult. Thanks to all the developers for their hard work, but this is only the initial stage, and we will focus on `streaming-warehouse` and `cloud native`, the following is the roadmap of the next stage of StremaX: 

mind link: https://docs.qq.com/mind/DRUF0d1ZiTkhIaENv

Roadmap for 11/2021 ~ 07/2022:

- Documentation 
    - [x] #603
    - [x] #604

- **Streaming Warehouse**
    - [ ] #605 #563  
    - [x] #606
    - [x] #608
    - [x] #609
    - [x] #610
    - [x] #611
  
- **StremaX Console**
    - [x] #612
    - [x] #613
    - [x] #639
    - [x] #638
    - [x] #637
    - [x] #636
    - [x] #635
    - [x] #634
    - [ ] Standalone mode support 
    - [x] #633
    - [x] Support more alarm methods such as DingTalk and WeChat  #579

 - **Cloud Native**
    - [x] #631

- Core Framework
    - [x] #641
    - [x] #642

**Comment by baisui1981** [comment]
Awesome ,Let's work together

**Comment by wolfboys** [comment]
> Awesome ,Let's work together

cool, looking forward to our cooperation👌
