### ISSUE TITLE
Added DataSource module

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#609]

**Comment by Kyofin** [comment]
I am willing contribute this module.

**Comment by wolfboys** [comment]
> I am willing contribute this module.

great !!! 👍👍👍

**Comment by Whojohn** [comment]
@wolfboys 
> I can finish kafka datasource which inlclude : json auto infer and so on.

- The feature may include:
1.  (promise) flink kafka catalog .
2.  (promise) json -> flink sql logicalType infer.
3.  (non promise) user privilege 
> User privilege  depends on StreamGraph to analysis which need some trick which will change the sql commit way.(Difference with streamxpark done .)

- Detail 
## Catalog
1. Meta center  control physic column define.
2. Create / hints to support : (Schema# All schema type) . Such as : primary key define, watermark ,timestamp define and logical column.

## Json infer 
1. Auto infer json type to Flink sql logicalType.

**Comment by wolfboys** [comment]
Expired proposal
