### ISSUE TITLE
Open task operation API, support restapi mode to operate tasks, and facilitate the integration of other platforms and frameworks

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#612]

**Comment by xianweiY** [comment]
I want to develop this feature , could u pls assign to me  ?

**Comment by wolfboys** [comment]
> I want to develop this feature , could u pls assign to me ?

ok. good job.

**Comment by yang100455** [comment]
#926  pr for this isssue

**Comment by xianweiY** [comment]
> > I want to develop this feature , could u pls assign to me ?
> 
> ok. good job.



> > I want to develop this feature , could u pls assign to me ?
> 
> ok. good job.

#926  pr for this isssue

**Comment by wolfboys** [comment]
supported
