### ISSUE TITLE
Modifying the workspace remote path in the configuration does not take effect

### ISSUE THREAD

**Issue by VSMDD** [apache/streampark#615]
application.yml：
![image](https://user-images.githubusercontent.com/31095506/149127690-25cb5593-21b2-4eb4-af08-e3ef6da9672e.png)

error log：
![image](https://user-images.githubusercontent.com/31095506/149128622-02d04138-beba-4be7-a3f4-298922b4944d.png)

**Comment by wolfboys** [comment]
fixed in new version
