### ISSUE TITLE
[Feat] Batch task scheduling integration

### ISSUE THREAD

**Issue by wolfboys** [apache/streampark#640]

**Comment by waywtdcc** [comment]
Hello, do you want to ask about the progress of the offline task scheduling function? We need this function very much. @wolfboys

**Comment by shangeyao** [comment]
please assign to me.

**Comment by ChenpiDog** [comment]
@wolfboys Will the task scheduling function be implemented by other tools or by StreamPark itself?
As a user, I hope StreamPark can provide task scheduling function. After all, DolphinScheduler is a heavyweight scheduling tool, while our scenario only has SQL. In fact, the self implementation of the scheduling function does not conflict with the integration with other scheduling tools.

**Comment by wolfboys** [comment]
> please assign to me.

hello. Are you ready to continue advancing that feature?

**Comment by wolfboys** [comment]
There are no plans for this
