### ISSUE TITLE
[Question] The submission principle of FLINK SQL

### ISSUE THREAD

**Issue by LinMingQiang** [apache/streampark#648]
##（General Question）
1: Can page submission SQL be submitted to a remote Yarn cluster or Standalone cluster? (Similar to gateway) (I see that in the source code, sql execution is submitted through statementSet.execute() in FlinkSqlExecutor.executeSql, but as far as I know, execution.target = local will enable local miniCluster in this way). I don't know if my understanding is wrong

2: Does the project manage multiple users, such as whether multiple users are executed under different Envs, and whether the multiple users are isolated?

3 ：only support flink on yarn ? standalone dont support？

Thanks for answering

**Comment by wolfboys** [comment]
1. Currently supported submitte modes  are: `yarn-prejob, yarn-application, k8s-native-session, k8s-native-application`, Upcoming support `Standalone`, pr: https://github.com/streamxhub/streamx/pull/457

2.  At present, it supports multi-user and multi tenant, and has done a good job in terms of permissions,  multiple users and task are isolatedm.

**Comment by wolfboys** [comment]
1. Currently supported submitte modes  are: `yarn-prejob, yarn-application, k8s-native-session, k8s-native-application`, Upcoming support `Standalone`, pr: https://github.com/streamxhub/streamx/pull/457

2.  At present, it supports multi-user and multi tenant, and has done a good job in terms of permissions,  multiple users and tasks are isolated.

**Comment by wolfboys** [comment]
Answered
