### ISSUE TITLE
Solve the problem of flinksql error reporting in yarn application mode

### ISSUE THREAD

**Issue by honghaoli9898** [apache/streampark#670]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**:  1.2.1
* **JVM version** (`java -version`): 1.8.0
* **OS version** (`uname -a` if on a Unix-like system): 3.10.0-957.el7.x86_64 

### Bug Description
An error is reported when running flinksql in yarn application mode

![image](https://user-images.githubusercontent.com/43817517/151088449-d7379c86-74ff-44ff-ba16-89d68b9a15fa.png)

###Solution
重命名streamx/plugins/streamx-flink-sqlclient-1.2.1.jar 为streamx/plugins/streamx-flink-sqlclient-1.2.0.jar

**Comment by wolfboys** [comment]
fixed.
