### ISSUE TITLE
[Bug] Bug title 

### ISSUE THREAD

**Issue by EdQzz** [apache/streampark#675]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**:   
v1.2.1-release
* **JVM version** (`java -version`):
 jdk1.8_261
* **OS version** (`uname -a` if on a Unix-like system):
centos 7
### Bug Description
登录页面无法登录，/passport/signin可以正常使用，返回了token

**Comment by wolfboys** [comment]
fixed.
