### ISSUE TITLE
[Feat] hope to add the function of viewing the compilation log after the project fails to compile.

### ISSUE THREAD

**Issue by jinrong58** [apache/streampark#701]
![image](https://user-images.githubusercontent.com/26400243/153144783-3a7da76a-6515-4624-8ba5-5c1f74461a5b.png)
目前只有编译过程中能看编译日志，如果项目编译失败了，就没有办法在前台看到编译日志了。希望能够添加，项目编译失败后查看编译日志的功能。

**Comment by lvshaokang** [comment]
i will take this issue

**Comment by wolfboys** [comment]
support
