### ISSUE TITLE
[feature] StreamX On Kubernetes For Helm Deployment Charts

### ISSUE THREAD

**Issue by czy006** [apache/streampark#705]
## Feature Request

**功能简介**

【English】Due to the cumbersome deployment procedures of StreamX On K8s, users cannot quickly experience the functions of Flink On K8s and experience a complete cloud native application. Therefore, Helm Charts can be used to quickly deploy a StreamX application, shielding the required underlying JDK, Scala, front-end and other environments. A StreamX On K8s deployment can be completed by helm install [app-name] StreamX/streamx-app -f /XXXX /values.yaml.Now we are investigating whether there are users with this part of demand. If there is demand, welcome to join this issuse to discussion

【中】由于用户在StreamX On K8s 部署步骤繁琐，无法进行快速拥有体验Flink On K8S功能和体验完整的云原生应用，故使用Helm Charts 能快速部署一个StreamX应用，屏蔽所需的底层JDK、Scala、前端等环境，通过容器进行快速构建出StreamX所需的基本环境，用户只需要通过helm install [app-name] streamx/streamx-app -f /xxxx/values.yaml 即可完成一次StreamX On K8s部署。现在调研是否有用户有这一部分需求，如果有需求欢迎加入此ISSUSE讨论

**功能实现**

- StreamX DockerFiles From UI
- StreamX DockerFiles From Console
- StreamX Charts From Deployment.yaml
- StreamX Charts From ConfigMap.yaml
- StreamX Charts From Services.yaml
- StreamX Charts Values Demo Files demo-value.yaml
- Use helm charts to deployment streamX demo doc

**Comment by wolfboys** [comment]
Expired proposal
