### ISSUE TITLE
[Question] kafka2hive。use catalog myhive ; check报错

### ISSUE THREAD

**Issue by yixinGod** [apache/streampark#727]
## General Question

flink-sql测试写hive的时候，加入use catalog myhive;后，语句check报错，SQL parse failed. Non-query expression encountered in illegal context ， 是哪里没使用对吗
![image](https://user-images.githubusercontent.com/19711685/154637606-6692ee0b-fd10-4125-b780-5043e0685184.png)

**Comment by yixinGod** [comment]
不添加use catalog myhive;的话，报如下错误，请问如何处理呢
![image](https://user-images.githubusercontent.com/19711685/154638043-99d9aa90-f9be-481f-a1ee-c9177e182e98.png)

**Comment by wolfboys** [comment]
please use english.
