### ISSUE TITLE
[Bug] flink1.13，flink sql， start job always starting

### ISSUE THREAD

**Issue by mydq** [apache/streampark#730]
<img width="824" alt="a921686162bec72d8ac1f5e64d004c9" src="https://user-images.githubusercontent.com/42607771/154669395-72cdf10c-cc90-4673-943a-aad0bc88f4bd.png">
<img width="657" alt="c42d6dc9f80123d53efbd1563285c80" src="https://user-images.githubusercontent.com/42607771/154669415-78170b25-2668-4aea-a368-2866c1b09208.png">

**Comment by zqbird** [comment]
when the job have the problem,the job's status always in starting, have  some way to resolve this problem?

**Comment by JerryLen** [comment]
I have the same problem
