### ISSUE TITLE
Add user group (business group) to isolate Projects and Applications

### ISSUE THREAD

**Issue by daixiaoyu** [apache/streampark#743]
Background:

Some companies have the following business scenarios:

1. Both streamx and Flink clusters are managed by the data team and internally maintain jobs of many data teams

2. Streamx needs to be use by other business teams 

Problem with the current version: at present, streamx does not group and isolate project and application. Other business teams can see and operate the Applications of all teams, which is easy to cause misoperation, task failure and even data error

1. Add user group (business group) module under system

2. User groups (business groups) can manage employees (accounts) in each group, add, delete, etc

3. Users will only see project and application under their own group

4. If the user or administrator belongs to multiple business groups, adding project and application will let the user or administrator select the business group; If only belong to one group, does not have to select.

**Comment by wolfboys** [comment]
非常欢迎.可以关注下公众号,加入开发者群.

**Comment by daixiaoyu** [comment]
好的，感谢回复
