### ISSUE TITLE
[Question] Build Streamx - Sign in Failed

### ISSUE THREAD

**Issue by BakerYoung** [apache/streampark#774]
## General Question

I use independent packaging mode，The front-end and back-end deployment are completed and started normally
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/19159826/156290513-1c52bb27-c250-441e-aa83-0d2410f587db.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/19159826/156290547-9d805624-cac8-45c5-86e1-8e601c457bb6.png">

But, When I log in to the home page, I am prompted with failure, and The front-end error  like this **(failed)net::ERR_CONNECTION_REFUSED**
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/19159826/156290744-8d5c0a68-b467-488b-9519-914bf1c37533.png">

**Comment by BakerYoung** [comment]
Additional questions

I used 1.2.2 by Mixed package， home page can Login Success，Only Independent packaging Login Failed

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/19159826/156303439-5aaa391d-1299-45f2-9ea3-ef5199bb85e6.png">

**Comment by wolfboys** [comment]
see: https://www.streamxhub.com/docs/user-guide/deployment#2-%E5%89%8D%E7%AB%AF%E6%89%93%E5%8C%85

**Comment by wolfboys** [comment]
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/13284744/156305893-41809c69-6f01-489e-91b2-d1e42ec2778c.png">

**Comment by tisonkun** [comment]
Closed as answered.
