### ISSUE TITLE
[Question] The Options when restoring from savepoint 

### ISSUE THREAD

**Issue by FrankGaoi** [apache/streampark#794]
## General Question
My StreamX's version is 1.2.1.
I found there are some differences between applications when I tried to restore from savepoint. Sometime I can start application from the latest savepoint without appointing the savepoint manually.Sometime I can only start application by  assigning savepoint manually.
what is the rule about savepoint when I starting application?
![image](https://user-images.githubusercontent.com/94334609/157205889-6153a3fd-d1fa-4f30-9985-89b438a26af6.png)
![image](https://user-images.githubusercontent.com/94334609/157206007-7cc3d29e-0b61-4256-babc-4e3e1fa79543.png)

**Comment by wolfboys** [comment]
see #854
