### ISSUE TITLE
document description error

### ISSUE THREAD

**Issue by hxp0618** [apache/streampark#808]
document url:  http://www.streamxhub.com/zh-CN/docs/user-guide/development

The file name should be application.yml , not application.xml

![image](https://user-images.githubusercontent.com/30236140/157839590-7df1aac1-5028-47f4-9d8a-d552eed38f48.png)

**Comment by wolfboys** [comment]
> document url: http://www.streamxhub.com/zh-CN/docs/user-guide/development
> 
> The file name should be application.yml , not application.xml
> 
> ![image](https://user-images.githubusercontent.com/30236140/157839590-7df1aac1-5028-47f4-9d8a-d552eed38f48.png)

u can fix it.👍👍👍

**Comment by wolfboys** [comment]
fixed.
