### ISSUE TITLE
last complete checkpoint saved to db ,when task meet exception and will recover itself with the last successful checkpoint

### ISSUE THREAD

**Issue by gitfortian** [apache/streampark#854]
## Enhancement
in my production env,i use a scheduled task to get the flink job last complete checkpoint by http,and save the checkpoint path to db,when flink job meet an exception,i will try to recover it by the last chckpoint i saved before. do u think this should be supportted?

**Comment by gitfortian** [comment]
streamx now support stop job with savepoint ,and restart by the savepoint,but how does it handle the job when meet an exception

**Comment by wolfboys** [comment]
At present, the processing strategies of checkpoint and savepoint in streamx are as follows:

1. each checkpoint will be recorded to the database, and the last record will be recorded as "latest"
2. if savepoint is specified when stopping, it will be recorded to the database and set to "latest"
3. if the task is not stopped from streamx, e.g: cancel  from the flick webui, the latest flag will be clear
4. if the program is abnormal Or fail, the latest flag will be cleared automatically

When the task restarts next time, if it can read the latest record, it will automatically take the record as the recovery point. If no latest record is found, it needs to be specified manually by the user

---

目前streamx里对checkpoint和savepoint的处理策略如下:
1. 会记录每次checkpoint到数据库,并记录最后的记录为latest
2. 停止时如果指定savepoint则会记录到数据库,并设置为latest
3. 如果不是从streamx里停止的任务,如直接从flink webui里cancel了任务,则会取消latest标记
4. 如果程序发生异常.或者失败,会自动清除latest标记

任务在下次重启的时候,如果能读取到latest的记录,会自动从将该记录作为恢复点, 如果未发现latest的记录,则需要用户手动指定

**Comment by wolfboys** [comment]
At present, the processing strategies of checkpoint and savepoint in streamx are as follows:

1) : each checkpoint will be recorded to the database, and the last record will be recorded as "latest"

2) : if savepoint is specified when stopping, it will be recorded to the database and set to "latest"

3) : if the task is not stopped from streamx, e.g: cancel  from the flick webui, the latest flag will be clear

4) : if the program is abnormal Or fail, the latest flag will be cleared automatically


When the task restarts next time, if it can read the latest record, it will automatically take the record as the recovery point. If no latest record is found, it needs to be specified manually by the user

---

目前streamx里对checkpoint和savepoint的处理策略如下:
1): 会记录每次checkpoint到数据库,并记录最后的记录为latest
2): 停止时如果指定savepoint则会记录到数据库,并设置为latest
3): 如果不是从streamx里停止的任务,如直接从flink webui里cancel了任务,则会取消latest标记
4): 如果程序发生异常.或者失败,会自动清除latest标记

任务在下次重启的时候,如果能读取到latest的记录,会自动从将该记录作为恢复点, 如果未发现latest的记录,则需要用户手动指定

**Comment by gitfortian** [comment]
copy that

**Comment by wolfboys** [comment]
Answered
