### ISSUE TITLE
[Bug] The application will not update when I push code to the git and re-build it

### ISSUE THREAD

**Issue by ralph-wren** [apache/streampark#865]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: 1.2.2
* **JVM version** (`java -version`):jdk1.8.0_301.jdk
* **OS version** (`uname -a` if on a Unix-like system):Darwin macdeMacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

### Bug Description
I add a new project,then build it.when the building is finished,i add a new application.then lauch and start it.Until this step, everything is correct. However, when I  try to push my code,at this time,I will update the project updated previously. It will build successfuly without question.However,when I try launch and start the application got from the project for the second time, things develop towards an unexpected way! the application does not update at all! However ,I changed some code at the last push. That means , the behaviro of updating code does not  apply to the application.
I did not identify which stage has bug at the beginnig.but with my research from the start,push code,build project,and launch the application... I found the the jar home at hdfs only update once  when the directory is created ,it will not change when you try to update the jar.

### How to Reproduce 
you can see the update time of the jar ,at the host node,the update time is 17：26，but at the hdfs directory, the update time is 16:37, this is the create time of this directory,the jar is updated at 17:26 ,but is was not upload to the hdfs path,which I believe that should be used in the application.
![image](https://user-images.githubusercontent.com/65018890/160315088-a3057c0f-ad7f-4518-be04-d9d697a78b41.png)
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/65018890/160315150-1e26cda5-8516-4336-9a46-d6e628500fbe.png">

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

Maybe we should add some checks to make sure that the correct jar is uploaded to the remote path.

**Comment by wolfboys** [comment]
fixed.
