### ISSUE TITLE
how will streamx do when flink jobmaster failed and not set ha for it

### ISSUE THREAD

**Issue by gitfortian** [apache/streampark#866]
## Enhancement
when i set ha for jobmaster on yarn-application mode use high-availability: zookeeper,the job alway be 000000000000000000000,and the multi job will has the same checkpoint path such as hdfs://hadoop3/flink-checkpoints/00000000000000000000000000000000,this will cause job recover with a wrong checkpont data.
to avoid this problem,i chose to not set ha for jobmaster,then there is a normal jobId,but this may has another problem,how will streamx recover the job when jobmaster failed. is it recover the job with last-checkpoint-data when found job failed status.

**Comment by wolfboys** [comment]
This is the problem caused by the improper configuration of your flink.

**Comment by gitfortian** [comment]
If all online jobs are configured with the ha of the flip Jobmaster, you need to add a random UUID to the checkpoint path when streamx is submitted. Although the jobids are all 0000000000000000, the paths are inconsistent

**Comment by gitfortian** [comment]
Another problem is that I didn't take a closer look at streamx. I don't know how to save an app when it is accompanied by multiple jobs. I observed that multiple jobs will fail in checkpoint operation at the same time. I don't know how to recover

**Comment by wolfboys** [comment]
fixed. see #924
