### ISSUE TITLE
[Bug] The status does not change after the job submission fails

### ISSUE THREAD

**Issue by ethanlian** [apache/streampark#868]
### Environment Description
* **StreamX Version**: v1.2.2
* **JVM version** (`java -version`):java 8
* **OS version** (`uname -a` if on a Unix-like system): centos

### Bug Description
An exception is thrown after the job is submitted，the streamx job status keeps starting after  job failed

### How to Reproduce 

1 . create flink myql cdc sql job ，and mysql user password is incorrect
2.  run job with  remote(standalone) mode
3 . mysql connection failure throws exception  and causes the job to fail
4.streamx job's state  keeps starting

**Comment by wolfboys** [comment]
fixed. please use streamx 1.2.2+
