### ISSUE TITLE
[Feature] iceberg connector

### ISSUE THREAD

**Issue by lordk911** [apache/streampark#876]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

apache iceberg is a very popular data lake solution，it has a official release flink connector, it streamx could integration it internally, it will make streamx api fit much more scenario.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liuzhuang2017** [comment]
@lordk911 , It is a good idea, thanks.

**Comment by wolfboys** [comment]
Expired proposal
