### ISSUE TITLE
[Bug] FinkSQL Task always STATING state

### ISSUE THREAD

**Issue by JerryLen** [apache/streampark#885]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: 1.2.2-release
* **JVM version** (`java -version`): openjdk version "1.8.0_312"
* **OS version** (`uname -a` if on a Unix-like system): Linux 5.10.102-99.473.amzn2.x86_64

### Bug Description
* Flink version : 1.13.6
* Scala version of Flink : 2.11
* Hadoop version :  3.2.1-amzn-4 ( AWS EMR)

 FinkSQL Task always STATING state.
Other FlinkSQL task states can be detected normally, like failed FINISHED and FAILED.
Failed to modify `t_flink_app` 's column `state` to 5(RUNNING).
The value of `state` is modified to 3(STARTING) soon by streamx.

### How to Reproduce 
Steps to reproduce the behavior, for example:
1.  Run FLINK SQL DEMO directly  or Other FlinSQL Streaming Task.
2. Go to YARN web,  the state of application is RUNNING.
3. Go to StreamX web, the  state of application is STARTING.
4. The logs didn't occured ERROR

If you still lack information, please let me know.

**Comment by ZYZ0001** [comment]
遇到了相同的问题，有解决方案吗

**Comment by songkunhuang** [comment]
重启streamsets服务，或者直接修改数据库中f_flink_app表中对应任务的state

**Comment by wolfboys** [comment]
fixed in new version
