### ISSUE TITLE
[Feature] `Streamx` restapi support. (e.g: support `DS` scheduling)

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#886]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Need to provide interface to complete seamless access to `DS` scheduling process

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good job! 👏 👍
