### ISSUE TITLE
[Bug]options set already but it shows need to set value

### ISSUE THREAD

**Issue by gitfortian** [apache/streampark#891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

options set already but it shows need to set value

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.14.2

### Scala Version of Flink

2.11

### Error Exception

```log
options set already but it shows need to set value
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed.
