### ISSUE TITLE
If there are multiple modules under a project, there is some confusion in the prompt message that needs to compile the module configuration information

### ISSUE THREAD

**Issue by dwave** [apache/streampark#893]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

If there are multiple modules under a project, there is some confusion in the prompt message of the module configuration information that needs to be compiled, such as I want to compile some of the modules, but I don't know how to configure them, and I configure them after many attempts
![QQ截图20220402140316](https://user-images.githubusercontent.com/14970783/161369185-14a1161a-0b3f-4142-a5d4-450466686ae8.png)

### Usage Scenario

When using user-defined code

### Related issues

streamx1.2.2

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please specify the module of the pom.xml file relative to the project's root path.
