### ISSUE TITLE
[Feature]sql validate is too simple，could u support the table valid

### ISSUE THREAD

**Issue by gitfortian** [apache/streampark#896]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

sql validate now  is too simple，could u support the table valid.for example, i create table A ,table B,and i  select table C, sql validate returns ok,but i think it shold not ,i want it retuns table C not exists so i can fix the sql emidiatly instead of look up the sql error in yarn log.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
The proposal has not been updated for a long time, welcome to start again
