### ISSUE TITLE
[Bug] Flinksql job depended jar not changed when i reupload the dependended jar

### ISSUE THREAD

**Issue by gitfortian** [apache/streampark#897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when i reupload the flinksql jar and lauch the app and restart it ,i found the depandency not changed,it show job use the old jar.

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.14

### Scala Version of Flink

2.11

### Error Exception

```log
when i reupload the flinksql jar and lauch the app and restart it ,i found the depandency not changed,it show job use the old jar.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed, please use latest version
