### ISSUE TITLE
[Bug] jdbc sink needs to be optimized

### ISSUE THREAD

**Issue by syb853553110** [apache/streampark#918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

[Bug]
The jdbc sink currently reaches the batchSize or submits it once every 1 second. Assuming that the batchSize has not been reached in 0.9 seconds, and there is no data for a period of time, the data will not be inserted into the database.
A timer should be added, for example, every 5 seconds to determine whether there is unexecuted sql, this situation can be avoided.

[翻译] jdbc sink目前是达到batchSize或者1秒提交一次，假设0.9秒还没达到batchSize，并且一段时间没数据了，这些数据是不会被插入数据库的。
应该再加一个定时器，比如每隔5秒判断下，是否有未执行的sql，就可以避免这种情况发生。

### StreamX Version

1.2.3

### Java Version

1.8

### Flink Version

1.14.4

### Scala Version of Flink

2.12

### Error Exception

```log
no error exception
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed
