### ISSUE TITLE
[Bug] The submitted task failed streamx's front end did not change state, but was stuck in initialization

### ISSUE THREAD

**Issue by MonsterChenzhuo** [apache/streampark#921]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In the on k8s scenario, I submitted the task to the set, and through the backend interface of k8s, I saw that the task failed, while the client interface of streamx showed that the status was stalled to initialization, and I did not send to delete the current task

在on k8s的场景下，我向集提交了任务，通过k8s的后台界面，我看到了任务失败，而streamx的客户端界面显示是状态停滞到初始化，我没发删除当前任务

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.12.1

### Scala Version of Flink

2.11

### Error Exception

```log
无
```

### Screenshots

<img width="1198" alt="图片" src="https://user-images.githubusercontent.com/60029759/162150286-db09773e-d882-4f5d-9637-cbfd7f505a8b.png">
<img width="1161" alt="图片" src="https://user-images.githubusercontent.com/60029759/162151299-0e981c1f-973a-49c9-ba3f-0b8e6b8ab500.png">
<img width="1246" alt="图片" src="https://user-images.githubusercontent.com/60029759/162155328-49c91b8f-4f96-44cf-ad7d-dc6f96e41572.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
Please make sure to use the most recent version and keep sending us your feedback.
