### ISSUE TITLE
[Feature] Add hudi connector

### ISSUE THREAD

**Issue by cun8cun8** [apache/streampark#937]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

apache hudi is a very popular data lake solution，it has a official release flink connector, it streamx could integration it internally, it will make streamx api fit much more scenario.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
do you want to contribute this PR? welcome !😁

**Comment by Kick156** [comment]
Do streampark still need the hudi connector of datastream api version?
At the FFW2022 conference, I saw that Streammark wanted to integrate existing connectors to achieve data integration in its future planning.

**Comment by wolfboys** [comment]
Welcome to propose again
