### ISSUE TITLE
[Feature] add apache pulsar connector

### ISSUE THREAD

**Issue by cun8cun8** [apache/streampark#938]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Apache Pulsar is a cloud-native, distributed messaging and streaming platform originally created at Yahoo! and now a top-level Apache Software Foundation project

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
do you want to contribute this PR?  welcome !😁

**Comment by wolfboys** [comment]
Welcome to propose again
