### ISSUE TITLE
[Feature][Connector] Add Elasticsearch7 connector

### ISSUE THREAD

**Issue by lvshaokang** [apache/streampark#947]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add Elasticsearch7 connector

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good job.
