### ISSUE TITLE
[Bug] yarn application mode yarn queue not take effect

### ISSUE THREAD

**Issue by qjx1208** [apache/streampark#954]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Execution Mode:yarn application
after update 1.2.2, job yarn queue not take effect
1.2.1 is ok

### StreamX Version

1.2.2

### Java Version

jdk1.8

### Flink Version

flink1.13.5

### Scala Version of Flink

2.11

### Error Exception

```log
--------------------------------------- flink start ---------------------------------------
    userFlinkHome    : /opt/flink-1.13.5
    flinkVersion     : 1.13.5
    appName          : hive-connector-1
    devMode          : CUSTOMCODE
    execMode         : YARN_APPLICATION
    k8sNamespace     : default
    flinkExposedType : null
    clusterId        : null
    resolveOrder     : parent-first
    applicationType  : Apache Flink
    flameGraph       : false
    savePoint        : null
    option           : {}
    property         : {}
    dynamicOption    : 
    args             : null
    appConf          : json://{"$internal.application.main":"com.examples.HiveCatalogTest"}
    flinkBuildResult : ShadedBuildResponse(null,hdfs://hadoop3cluster/streamx/workspace/100178/hive-connector-1.0-SNAPSHOT.jar,true)
-------------------------------------------------------------------------------------------
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by SoberChina** [comment]
You need to specify the queue when configuring dynamic option

**Comment by qjx1208** [comment]
I modified the file ApplicationServiceImpl.java to fix it
