### ISSUE TITLE
[Feature] Support alarm template configurable

### ISSUE THREAD

**Issue by SoberChina** [apache/streampark#957]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

In multiple environments, it is difficult to directly distinguish the alarm email information from which environment. It is important to support the customization of templates,

### Usage Scenario

The alarm template is mentioned in the configuration file

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
good feature, I'm looking forward to it
