### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.flink.runtime.state.CheckpointStorage

### ISSUE THREAD

**Issue by JiangfeiLiu** [apache/streampark#971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when config checkpoints enable is true,throw a error Caused by: java.lang.ClassNotFoundException: org.apache.flink.runtime.state.CheckpointStorage
in Flink 1.12.x，not exists org.apache.flink.runtime.state.CheckpointStorage in flink-runtime.jar

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.12.7

### Scala Version of Flink

2.11

### Error Exception

```log
java.lang.ClassNotFoundException: org.apache.flink.runtime.state.CheckpointStorage
```

### Screenshots

![Snipaste_2022-04-23_13-10-07](https://user-images.githubusercontent.com/100289093/164878694-1d5654ff-5902-47e6-8eeb-a96c9a529a14.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
fixed in new version
