### ISSUE TITLE
[StreamX] can't found flink.state.checkpoint-storage from properties,now try found from flink-conf.yaml

### ISSUE THREAD

**Issue by JiangfeiLiu** [apache/streampark#976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

how to config flink.state.checkpoint-storage in application.ymal in project?
document not provided parameter to config

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.13.5

### Scala Version of Flink

2.11

### Error Exception

```log
[StreamX] can't found flink.state.checkpoint-storage from properties,now try found from flink-conf.yaml
```

### Screenshots

![Snipaste_2022-04-23_13-14-28](https://user-images.githubusercontent.com/100289093/164878835-6d54a62c-6425-4b7f-b902-8e3bb986913c.png)
![Snipaste_2022-04-23_13-15-33](https://user-images.githubusercontent.com/100289093/164878837-876420c3-e417-49bf-b040-236a372f5b56.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tisonkun** [comment]
Closed as stale. Please open a new issue if it's still relevant for the latest version.
