### ISSUE TITLE
[Bug] IDEA 本地部署问题

### ISSUE THREAD

**Issue by Su1024** [apache/streampark#982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

本地部署streamx 启动StreamXConsole主类时失败！

### StreamX Version

1.2.2

### Java Version

1.8

### Flink Version

1.13

### Scala Version of Flink

2.12

### Error Exception

```log
object TableExt is not a member of package com.streamxhub.streamx.flink.core.scala.ext
import com.streamxhub.streamx.flink.core.scala.ext.TableExt
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Su1024** [comment]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/23012179/165068597-db63a66b-d92e-45ef-a002-db149248140e.png">

**Comment by wolfboys** [comment]
please use english.
