### ISSUE TITLE
[Feature] Quickly copy an application

### ISSUE THREAD

**Issue by muchunjin** [apache/streampark#983]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When creating an application, if the configuration of this application is almost the same as that of an existing application, then if an application can be quickly copied from the existing application, the experience and efficiency will be improved at the same time; Can add a copy button in the operation bar of the application list. When you click this button, quickly generate a copy of the application, and then click the Edit button of the copy to edit.

### Usage Scenario

if the configuration of this application is almost the same as that of an existing application, then if an application can be quickly copied from the existing application, the experience and efficiency will be improved at the same time

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
this's a great feature!👍👍

**Comment by muchunjin** [comment]
Other small partners have achieved
