### ISSUE TITLE
[Feature]  streamx有汉化的计划吗

### ISSUE THREAD

**Issue by waywtdcc** [apache/streampark#995]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

 streamx有汉化的计划吗

### Usage Scenario

 streamx有汉化的计划吗

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
please use english on issues
